#!/bin/bash

# Build 71 - TestFlight Upload Script
# =====================================

echo "🚀 Build 71 TestFlight Upload"
echo "=============================="
echo ""
echo "✅ Build Status: SUCCESS"
echo "✅ Archive: build/PTPerformance.xcarchive"
echo "✅ IPA: build/export/PTPerformance.ipa"
echo "✅ Build Number: 71"
echo ""
echo "📋 Upload Options:"
echo ""
echo "OPTION 1: Xcode Transporter (Recommended - GUI)"
echo "------------------------------------------------"
echo "Run: open /Applications/Transporter.app"
echo "Then:"
echo "  1. Sign in with your Apple ID (paul@roma.ai)"
echo "  2. Click 'Add App'"
echo "  3. Select: build/export/PTPerformance.ipa"
echo "  4. Click 'Deliver'"
echo "  5. Wait 2-5 minutes for upload"
echo ""
echo "OPTION 2: Command Line with App-Specific Password"
echo "--------------------------------------------------"
echo "First, create an app-specific password:"
echo "  1. Go to https://appleid.apple.com"
echo "  2. Sign in with paul@roma.ai"
echo "  3. Generate app-specific password (App Passwords section)"
echo "  4. Save it to keychain:"
echo "     security add-generic-password -a paul@roma.ai -s altool -w"
echo ""
echo "Then upload:"
echo "  xcrun altool --upload-app \\"
echo "    --type ios \\"
echo "    --file build/export/PTPerformance.ipa \\"
echo "    --username paul@roma.ai \\"
echo "    --password @keychain:altool"
echo ""
echo "OPTION 3: App Store Connect API (Advanced)"
echo "-------------------------------------------"
echo "Requires API key setup in App Store Connect."
echo "See BUILD_71_DEPLOYMENT_READY.md for details."
echo ""
echo "════════════════════════════════════════════"
echo "Choose an option above to complete upload."
echo "════════════════════════════════════════════"
