/**
 * PCR Routes - Plan Change Request
 * ACP-90: Implement /plan-change-proposal endpoint
 *
 * Handles manual creation of Plan Change Requests in Linear
 * Creates issues with zone-4b label and "In Review" state
 */

import fetch from "node-fetch";
import { createAppError, sendApiError } from "../errors/api-error.js";

const LINEAR_API_KEY = process.env.LINEAR_API_KEY;
const LINEAR_TEAM_ID = process.env.LINEAR_TEAM_ID || "5296cff8-9c53-4cb3-9df3-ccb83601805e";
const LINEAR_API_URL = "https://api.linear.app/graphql";

/**
 * Get Linear label ID for zone-4b
 */
async function getZone4bLabelId() {
  const query = `
    query GetLabels($teamId: String!) {
      team(id: $teamId) {
        labels {
          nodes {
            id
            name
          }
        }
      }
    }
  `;

  const response = await fetch(LINEAR_API_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": LINEAR_API_KEY
    },
    body: JSON.stringify({
      query,
      variables: { teamId: LINEAR_TEAM_ID }
    })
  });

  const result = await response.json();

  if (result.errors) {
    throw new Error(`Linear API error: ${JSON.stringify(result.errors)}`);
  }

  const labels = result.data?.team?.labels?.nodes || [];
  const zone4bLabel = labels.find(label => label.name === "zone-4b");

  if (!zone4bLabel) {
    throw new Error("zone-4b label not found in Linear workspace");
  }

  return zone4bLabel.id;
}

/**
 * Get "In Review" workflow state ID
 */
async function getInReviewStateId() {
  const query = `
    query GetStates($teamId: String!) {
      team(id: $teamId) {
        states {
          nodes {
            id
            name
            type
          }
        }
      }
    }
  `;

  const response = await fetch(LINEAR_API_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": LINEAR_API_KEY
    },
    body: JSON.stringify({
      query,
      variables: { teamId: LINEAR_TEAM_ID }
    })
  });

  const result = await response.json();

  if (result.errors) {
    throw new Error(`Linear API error: ${JSON.stringify(result.errors)}`);
  }

  const states = result.data?.team?.states?.nodes || [];
  const inReviewState = states.find(state => state.name === "In Review");

  if (!inReviewState) {
    // Fallback to "started" type if "In Review" doesn't exist
    const startedState = states.find(state => state.type === "started");
    if (startedState) {
      return startedState.id;
    }
    throw new Error("In Review or started state not found in Linear workspace");
  }

  return inReviewState.id;
}

/**
 * Create Plan Change Request issue in Linear
 */
async function createPlanChangeRequest({ patientId, reason, suggested_changes, severity }) {
  const [zone4bLabelId, inReviewStateId] = await Promise.all([
    getZone4bLabelId(),
    getInReviewStateId()
  ]);

  const mutation = `
    mutation CreatePCR($input: IssueCreateInput!) {
      issueCreate(input: $input) {
        success
        issue {
          id
          identifier
          title
          url
        }
      }
    }
  `;

  const title = `Plan Change Request - Patient ${patientId.substring(0, 8)}`;

  const description = `## Plan Change Request

**Patient ID:** \`${patientId}\`
**Severity:** ${severity || "MEDIUM"}

### Reason
${reason || "No reason provided"}

### Suggested Changes
${suggested_changes || "No changes specified"}

---
*Generated by PT Assistant Agent*
*Created: ${new Date().toISOString()}*
`;

  const input = {
    teamId: LINEAR_TEAM_ID,
    title,
    description,
    stateId: inReviewStateId,
    labelIds: [zone4bLabelId]
  };

  const response = await fetch(LINEAR_API_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": LINEAR_API_KEY
    },
    body: JSON.stringify({
      query: mutation,
      variables: { input }
    })
  });

  const result = await response.json();

  if (result.errors) {
    throw new Error(`Linear API error: ${JSON.stringify(result.errors)}`);
  }

  if (!result.data?.issueCreate?.success) {
    throw new Error("Failed to create Linear issue");
  }

  return result.data.issueCreate.issue;
}

/**
 * Setup PCR routes
 */
export function setupPCRRoutes(app) {
  /**
   * POST /pt-assistant/plan-change-proposal/:patientId
   *
   * Create a Plan Change Request in Linear
   *
   * Body:
   * {
   *   "reason": "High pain levels detected (7/10) for 2 consecutive sessions",
   *   "suggested_changes": "Reduce throwing volume by 20%, add extra rest day",
   *   "severity": "HIGH" // Optional: LOW, MEDIUM, HIGH, CRITICAL
   * }
   *
   * Response:
   * {
   *   "success": true,
   *   "issue": {
   *     "id": "...",
   *     "identifier": "ACP-123",
   *     "title": "Plan Change Request - Patient 12345678",
   *     "url": "https://linear.app/..."
   *   }
   * }
   */
  app.post("/pt-assistant/plan-change-proposal/:patientId", async (req, res) => {
    const startTime = Date.now();
    const { patientId } = req.params;
    const { reason, suggested_changes, severity } = req.body;

    try {
      // Validate inputs
      if (!patientId) {
        return sendApiError(res, createAppError("patient_id_required", 400, "patientId is required"));
      }

      if (!reason && !suggested_changes) {
        return sendApiError(res, createAppError("reason_or_suggested_changes_required", 400, "reason or suggested_changes is required"));
      }

      // Create Linear issue
      const issue = await createPlanChangeRequest({
        patientId,
        reason,
        suggested_changes,
        severity: severity || "MEDIUM"
      });

      const responseTime = Date.now() - startTime;

      res.json({
        success: true,
        issue: {
          id: issue.id,
          identifier: issue.identifier,
          title: issue.title,
          url: issue.url
        },
        response_time_ms: responseTime
      });

    } catch (error) {
      const responseTime = Date.now() - startTime;

      console.error("Error creating PCR:", error);

      return sendApiError(res, createAppError("failed_to_create_pcr", 500, error.message, { response_time_ms: responseTime }));
    }
  });
}
