import Foundation

/// Fasting log entry (matches fasting_logs table in Supabase)
struct FastingLog: Identifiable, Codable, Hashable {
    let id: UUID
    let patientId: UUID
    let protocolType: String?  // Maps to protocol_type in database
    let startedAt: Date
    let endedAt: Date?
    let plannedHours: Int      // Maps to planned_hours in database
    let actualHours: Double?
    let completed: Bool
    let notes: String?
    let createdAt: Date
    let updatedAt: Date?

    enum CodingKeys: String, CodingKey {
        case id
        case patientId = "patient_id"
        case protocolType = "protocol_type"
        case startedAt = "started_at"
        case endedAt = "ended_at"
        case plannedHours = "planned_hours"
        case actualHours = "actual_hours"
        case completed
        case notes
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // MARK: - Backward Compatibility Properties

    /// Backward-compatible property for code using fastingType
    var fastingType: FastingType {
        FastingType(rawValue: protocolType ?? "intermittent") ?? .intermittent
    }

    /// Backward-compatible property for code using targetHours
    var targetHours: Int { plannedHours }

    /// Date formatter for Supabase (ISO8601)
    private static let dateFormatter: ISO8601DateFormatter = {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return formatter
    }()

    /// Custom encoder to format dates and UUIDs correctly for Supabase
    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        // Encode UUIDs as strings for Supabase compatibility
        try container.encode(id.uuidString, forKey: .id)
        try container.encode(patientId.uuidString, forKey: .patientId)
        try container.encodeIfPresent(protocolType, forKey: .protocolType)
        // Encode dates as ISO8601 strings for Supabase compatibility
        try container.encode(Self.dateFormatter.string(from: startedAt), forKey: .startedAt)
        try container.encodeIfPresent(endedAt.map { Self.dateFormatter.string(from: $0) }, forKey: .endedAt)
        try container.encode(plannedHours, forKey: .plannedHours)
        try container.encodeIfPresent(actualHours, forKey: .actualHours)
        try container.encode(completed, forKey: .completed)
        try container.encodeIfPresent(notes, forKey: .notes)
        // Note: createdAt/updatedAt are auto-generated by database
    }

    var isActive: Bool {
        endedAt == nil
    }

    var progressPercent: Double {
        guard let end = endedAt else {
            let elapsed = Date().timeIntervalSince(startedAt) / 3600
            return min(elapsed / Double(plannedHours), 1.0)
        }
        let actual = end.timeIntervalSince(startedAt) / 3600
        return min(actual / Double(plannedHours), 1.0)
    }

    // MARK: - Additional Backward Compatibility

    /// Backward-compatible property for code using startTime
    var startTime: Date { startedAt }

    /// Backward-compatible property for code using endTime
    var endTime: Date? { endedAt }

    /// Whether fast was broken early (inverse of completed)
    var wasBrokenEarly: Bool { !completed && endedAt != nil }
}

/// Fasting type enum matching Supabase database values
/// Database expects: intermittent, extended, water_only, modified, custom
enum FastingType: String, Codable, CaseIterable {
    case intermittent = "intermittent"
    case extended = "extended"
    case waterOnly = "water_only"
    case modified = "modified"
    case custom = "custom"

    var displayName: String {
        switch self {
        case .intermittent: return "Intermittent"
        case .extended: return "Extended"
        case .waterOnly: return "Water Only"
        case .modified: return "Modified"
        case .custom: return "Custom"
        }
    }

    var targetHours: Int {
        switch self {
        case .intermittent: return 16
        case .extended: return 24
        case .waterOnly: return 24
        case .modified: return 18
        case .custom: return 16
        }
    }

    var description: String {
        switch self {
        case .intermittent: return "Daily time-restricted eating (e.g., 16:8, 18:6)"
        case .extended: return "Extended fasting period (24+ hours)"
        case .waterOnly: return "Water-only fast with no caloric intake"
        case .modified: return "Modified fast allowing limited calories"
        case .custom: return "Custom fasting schedule"
        }
    }
}

/// Eating window recommendation based on training schedule
struct EatingWindowRecommendation: Identifiable, Codable {
    let id: UUID
    let suggestedStart: Date
    let suggestedEnd: Date
    let reason: String
    let trainingTime: Date?
    let confidence: Double
}

/// Fasting statistics
struct FastingStats: Codable {
    let totalFasts: Int
    let completedFasts: Int
    let averageHours: Double
    let longestFast: Double
    let currentStreak: Int
    let bestStreak: Int

    enum CodingKeys: String, CodingKey {
        case totalFasts = "total_fasts"
        case completedFasts = "completed_fasts"
        case averageHours = "average_hours"
        case longestFast = "longest_fast"
        case currentStreak = "current_streak"
        case bestStreak = "best_streak"
    }
}
