//
//  SupplementTests.swift
//  PTPerformanceTests
//
//  Comprehensive unit tests for Supplement, SupplementCategory, SupplementFrequency, TimeOfDay,
//  ScheduledSupplement, SupplementLog, and related models including validation and edge cases.
//

import XCTest
@testable import PTPerformance

// MARK: - Supplement Model Tests

final class SupplementTests: XCTestCase {

    // MARK: - Supplement Initialization Tests

    func testSupplementInitialization() {
        let id = UUID()
        let patientId = UUID()
        let createdAt = Date()

        let supplement = Supplement(
            id: id,
            patientId: patientId,
            name: "Creatine Monohydrate",
            brand: "Momentous",
            category: .creatine,
            dosage: "5g",
            frequency: .daily,
            timeOfDay: [.morning, .postWorkout],
            withFood: false,
            notes: "Take with water",
            momentousProductId: "creatine-001",
            isActive: true,
            createdAt: createdAt
        )

        XCTAssertEqual(supplement.id, id)
        XCTAssertEqual(supplement.patientId, patientId)
        XCTAssertEqual(supplement.name, "Creatine Monohydrate")
        XCTAssertEqual(supplement.brand, "Momentous")
        XCTAssertEqual(supplement.category, .creatine)
        XCTAssertEqual(supplement.dosage, "5g")
        XCTAssertEqual(supplement.frequency, .daily)
        XCTAssertEqual(supplement.timeOfDay.count, 2)
        XCTAssertTrue(supplement.timeOfDay.contains(.morning))
        XCTAssertTrue(supplement.timeOfDay.contains(.postWorkout))
        XCTAssertFalse(supplement.withFood)
        XCTAssertEqual(supplement.notes, "Take with water")
        XCTAssertEqual(supplement.momentousProductId, "creatine-001")
        XCTAssertTrue(supplement.isActive)
        XCTAssertEqual(supplement.createdAt, createdAt)
    }

    func testSupplementWithNilOptionals() {
        let supplement = Supplement(
            id: UUID(),
            patientId: UUID(),
            name: "Vitamin D3",
            brand: nil,
            category: .vitamins,
            dosage: "5000 IU",
            frequency: .daily,
            timeOfDay: [.morning],
            withFood: true,
            notes: nil,
            momentousProductId: nil,
            isActive: true,
            createdAt: Date()
        )

        XCTAssertNil(supplement.brand)
        XCTAssertNil(supplement.notes)
        XCTAssertNil(supplement.momentousProductId)
    }

    func testSupplementComputedProperties() {
        let supplement = createSupplement()

        XCTAssertEqual(supplement.recommendedDosage, supplement.dosage)
        XCTAssertEqual(supplement.shouldTakeWithFood, supplement.withFood)
        XCTAssertEqual(supplement.evidenceLevel, .moderate)
    }

    // MARK: - Supplement Codable Tests

    func testSupplementEncodeDecode() throws {
        // Note: Supplement has asymmetric encoding - createdAt is not encoded (for DB inserts)
        // but is expected when decoding (from DB responses). Test decoding from JSON.
        let json = """
        {
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "patient_id": "660e8400-e29b-41d4-a716-446655440001",
            "name": "Creatine Monohydrate",
            "brand": "Momentous",
            "category": "creatine",
            "dosage": "5g",
            "frequency": "daily",
            "time_of_day": ["morning"],
            "with_food": false,
            "is_active": true,
            "created_at": "2024-01-15T10:30:00Z"
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let decoded = try decoder.decode(Supplement.self, from: json)

        XCTAssertEqual(decoded.id.uuidString.lowercased(), "550e8400-e29b-41d4-a716-446655440000")
        XCTAssertEqual(decoded.name, "Creatine Monohydrate")
        XCTAssertEqual(decoded.brand, "Momentous")
        XCTAssertEqual(decoded.category, .creatine)
        XCTAssertEqual(decoded.dosage, "5g")
        XCTAssertEqual(decoded.frequency, .daily)
        XCTAssertEqual(decoded.withFood, false)
        XCTAssertEqual(decoded.isActive, true)
    }

    func testSupplementCodingKeysMapping() throws {
        let supplement = createSupplement()

        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(supplement)
        let jsonObject = try JSONSerialization.jsonObject(with: data) as! [String: Any]

        // Verify snake_case keys
        XCTAssertNotNil(jsonObject["patient_id"])
        XCTAssertNotNil(jsonObject["time_of_day"])
        XCTAssertNotNil(jsonObject["with_food"])
        // Note: momentous_product_id is optional and may be nil
        XCTAssertNotNil(jsonObject["is_active"])
        // Note: created_at is intentionally NOT encoded (auto-generated by database)
        XCTAssertNil(jsonObject["created_at"], "created_at should not be encoded (database auto-generates)")

        // Verify camelCase keys are NOT present
        XCTAssertNil(jsonObject["patientId"])
        XCTAssertNil(jsonObject["timeOfDay"])
        XCTAssertNil(jsonObject["withFood"])
        XCTAssertNil(jsonObject["momentousProductId"])
        XCTAssertNil(jsonObject["isActive"])
    }

    func testSupplementDecodingFromJSON() throws {
        let json = """
        {
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "patient_id": "660e8400-e29b-41d4-a716-446655440001",
            "name": "Creatine Monohydrate",
            "brand": "Momentous",
            "category": "creatine",
            "dosage": "5g",
            "frequency": "daily",
            "time_of_day": ["morning", "post_workout"],
            "with_food": false,
            "notes": "Mix with water",
            "momentous_product_id": "creatine-500",
            "is_active": true,
            "created_at": "2024-01-15T10:30:00Z"
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let supplement = try decoder.decode(Supplement.self, from: json)

        XCTAssertEqual(supplement.name, "Creatine Monohydrate")
        XCTAssertEqual(supplement.brand, "Momentous")
        XCTAssertEqual(supplement.category, .creatine)
        XCTAssertEqual(supplement.dosage, "5g")
        XCTAssertEqual(supplement.frequency, .daily)
        XCTAssertEqual(supplement.timeOfDay, [.morning, .postWorkout])
        XCTAssertEqual(supplement.withFood, false)
        XCTAssertEqual(supplement.notes, "Mix with water")
        XCTAssertEqual(supplement.momentousProductId, "creatine-500")
        XCTAssertEqual(supplement.isActive, true)
    }

    func testSupplementDecodingWithNullOptionals() throws {
        let json = """
        {
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "patient_id": "660e8400-e29b-41d4-a716-446655440001",
            "name": "Vitamin D3",
            "brand": null,
            "category": "vitamins",
            "dosage": "5000 IU",
            "frequency": "daily",
            "time_of_day": ["morning"],
            "with_food": true,
            "notes": null,
            "momentous_product_id": null,
            "is_active": true,
            "created_at": "2024-01-15T10:30:00Z"
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let supplement = try decoder.decode(Supplement.self, from: json)

        XCTAssertNil(supplement.brand)
        XCTAssertNil(supplement.notes)
        XCTAssertNil(supplement.momentousProductId)
    }

    func testSupplementHashable() {
        let supplement1 = createSupplement()
        let supplement2 = createSupplement()

        var set = Set<Supplement>()
        set.insert(supplement1)
        set.insert(supplement2)

        XCTAssertEqual(set.count, 2)
    }

    func testSupplementEquatable() {
        let id = UUID()
        let patientId = UUID()
        let date = Date()

        let supplement1 = Supplement(
            id: id,
            patientId: patientId,
            name: "Test",
            brand: nil,
            category: .protein,
            dosage: "1 scoop",
            frequency: .daily,
            timeOfDay: [.morning],
            withFood: false,
            notes: nil,
            momentousProductId: nil,
            isActive: true,
            createdAt: date
        )
        let supplement2 = Supplement(
            id: id,
            patientId: patientId,
            name: "Test",
            brand: nil,
            category: .protein,
            dosage: "1 scoop",
            frequency: .daily,
            timeOfDay: [.morning],
            withFood: false,
            notes: nil,
            momentousProductId: nil,
            isActive: true,
            createdAt: date
        )

        XCTAssertEqual(supplement1, supplement2)
    }

    // MARK: - SupplementCategory Tests

    func testSupplementCategoryAllCases() {
        let allCases = SupplementCategory.allCases
        XCTAssertEqual(allCases.count, 10)
        XCTAssertTrue(allCases.contains(.protein))
        XCTAssertTrue(allCases.contains(.creatine))
        XCTAssertTrue(allCases.contains(.vitamins))
        XCTAssertTrue(allCases.contains(.minerals))
        XCTAssertTrue(allCases.contains(.omega3))
        XCTAssertTrue(allCases.contains(.preworkout))
        XCTAssertTrue(allCases.contains(.recovery))
        XCTAssertTrue(allCases.contains(.sleep))
        XCTAssertTrue(allCases.contains(.adaptogens))
        XCTAssertTrue(allCases.contains(.other))
    }

    func testSupplementCategoryRawValues() {
        XCTAssertEqual(SupplementCategory.protein.rawValue, "protein")
        XCTAssertEqual(SupplementCategory.creatine.rawValue, "creatine")
        XCTAssertEqual(SupplementCategory.vitamins.rawValue, "vitamins")
        XCTAssertEqual(SupplementCategory.minerals.rawValue, "minerals")
        XCTAssertEqual(SupplementCategory.omega3.rawValue, "omega3")
        XCTAssertEqual(SupplementCategory.preworkout.rawValue, "preworkout")
        XCTAssertEqual(SupplementCategory.recovery.rawValue, "recovery")
        XCTAssertEqual(SupplementCategory.sleep.rawValue, "sleep")
        XCTAssertEqual(SupplementCategory.adaptogens.rawValue, "adaptogens")
        XCTAssertEqual(SupplementCategory.other.rawValue, "other")
    }

    func testSupplementCategoryDisplayNames() {
        XCTAssertEqual(SupplementCategory.protein.displayName, "Protein")
        XCTAssertEqual(SupplementCategory.creatine.displayName, "Creatine")
        XCTAssertEqual(SupplementCategory.vitamins.displayName, "Vitamins")
        XCTAssertEqual(SupplementCategory.minerals.displayName, "Minerals")
        XCTAssertEqual(SupplementCategory.omega3.displayName, "Omega-3")
        XCTAssertEqual(SupplementCategory.preworkout.displayName, "Pre-Workout")
        XCTAssertEqual(SupplementCategory.recovery.displayName, "Recovery")
        XCTAssertEqual(SupplementCategory.sleep.displayName, "Sleep")
        XCTAssertEqual(SupplementCategory.adaptogens.displayName, "Adaptogens")
        XCTAssertEqual(SupplementCategory.other.displayName, "Other")
    }

    func testSupplementCategoryDisplayNamesNotEmpty() {
        for category in SupplementCategory.allCases {
            XCTAssertFalse(category.displayName.isEmpty)
            XCTAssertTrue(category.displayName.first?.isUppercase == true,
                          "Display name should start with uppercase: \(category.displayName)")
        }
    }

    func testSupplementCategoryIcons() {
        XCTAssertEqual(SupplementCategory.protein.icon, "figure.strengthtraining.traditional")
        XCTAssertEqual(SupplementCategory.creatine.icon, "bolt.fill")
        XCTAssertEqual(SupplementCategory.vitamins.icon, "pill.fill")
        XCTAssertEqual(SupplementCategory.minerals.icon, "leaf.fill")
        XCTAssertEqual(SupplementCategory.omega3.icon, "drop.fill")
        XCTAssertEqual(SupplementCategory.preworkout.icon, "flame.fill")
        XCTAssertEqual(SupplementCategory.recovery.icon, "heart.fill")
        XCTAssertEqual(SupplementCategory.sleep.icon, "moon.fill")
        XCTAssertEqual(SupplementCategory.adaptogens.icon, "brain.head.profile")
        XCTAssertEqual(SupplementCategory.other.icon, "pills.fill")
    }

    func testSupplementCategoryIconsNotEmpty() {
        for category in SupplementCategory.allCases {
            XCTAssertFalse(category.icon.isEmpty)
        }
    }

    func testSupplementCategoryInitFromRawValue() {
        XCTAssertEqual(SupplementCategory(rawValue: "protein"), .protein)
        XCTAssertEqual(SupplementCategory(rawValue: "omega3"), .omega3)
        XCTAssertNil(SupplementCategory(rawValue: "invalid"))
        XCTAssertNil(SupplementCategory(rawValue: ""))
    }

    func testSupplementCategoryCodable() throws {
        let encoder = JSONEncoder()
        let decoder = JSONDecoder()

        for category in SupplementCategory.allCases {
            let data = try encoder.encode(category)
            let decoded = try decoder.decode(SupplementCategory.self, from: data)
            XCTAssertEqual(decoded, category)
        }
    }

    func testSupplementCategoryUniqueDisplayNames() {
        let names = SupplementCategory.allCases.map { $0.displayName }
        let uniqueNames = Set(names)
        XCTAssertEqual(names.count, uniqueNames.count, "Each category should have a unique display name")
    }

    // MARK: - SupplementFrequency Tests

    func testSupplementFrequencyAllCases() {
        let allCases = SupplementFrequency.allCases
        XCTAssertEqual(allCases.count, 6)
        XCTAssertTrue(allCases.contains(.daily))
        XCTAssertTrue(allCases.contains(.twiceDaily))
        XCTAssertTrue(allCases.contains(.threeTimesDaily))
        XCTAssertTrue(allCases.contains(.weekly))
        XCTAssertTrue(allCases.contains(.asNeeded))
        XCTAssertTrue(allCases.contains(.trainingDaysOnly))
    }

    func testSupplementFrequencyRawValues() {
        XCTAssertEqual(SupplementFrequency.daily.rawValue, "daily")
        XCTAssertEqual(SupplementFrequency.twiceDaily.rawValue, "twice_daily")
        XCTAssertEqual(SupplementFrequency.threeTimesDaily.rawValue, "three_times_daily")
        XCTAssertEqual(SupplementFrequency.weekly.rawValue, "weekly")
        XCTAssertEqual(SupplementFrequency.asNeeded.rawValue, "as_needed")
        XCTAssertEqual(SupplementFrequency.trainingDaysOnly.rawValue, "training_days_only")
    }

    func testSupplementFrequencyDisplayNames() {
        XCTAssertEqual(SupplementFrequency.daily.displayName, "Daily")
        XCTAssertEqual(SupplementFrequency.twiceDaily.displayName, "Twice Daily")
        XCTAssertEqual(SupplementFrequency.threeTimesDaily.displayName, "Three Times Daily")
        XCTAssertEqual(SupplementFrequency.weekly.displayName, "Weekly")
        XCTAssertEqual(SupplementFrequency.asNeeded.displayName, "As Needed")
        XCTAssertEqual(SupplementFrequency.trainingDaysOnly.displayName, "Training Days Only")
    }

    func testSupplementFrequencyDisplayNamesNotEmpty() {
        for frequency in SupplementFrequency.allCases {
            XCTAssertFalse(frequency.displayName.isEmpty)
            XCTAssertTrue(frequency.displayName.first?.isUppercase == true,
                          "Display name should start with uppercase: \(frequency.displayName)")
        }
    }

    func testSupplementFrequencyInitFromRawValue() {
        XCTAssertEqual(SupplementFrequency(rawValue: "daily"), .daily)
        XCTAssertEqual(SupplementFrequency(rawValue: "twice_daily"), .twiceDaily)
        XCTAssertEqual(SupplementFrequency(rawValue: "training_days_only"), .trainingDaysOnly)
        XCTAssertNil(SupplementFrequency(rawValue: "invalid"))
    }

    func testSupplementFrequencyCodable() throws {
        let encoder = JSONEncoder()
        let decoder = JSONDecoder()

        for frequency in SupplementFrequency.allCases {
            let data = try encoder.encode(frequency)
            let decoded = try decoder.decode(SupplementFrequency.self, from: data)
            XCTAssertEqual(decoded, frequency)
        }
    }

    // MARK: - TimeOfDay Tests

    func testTimeOfDayAllCases() {
        let allCases = TimeOfDay.allCases
        XCTAssertEqual(allCases.count, 8) // morning, afternoon, evening, night, beforeBed, preWorkout, postWorkout, withMeals
        XCTAssertTrue(allCases.contains(.morning))
        XCTAssertTrue(allCases.contains(.afternoon))
        XCTAssertTrue(allCases.contains(.evening))
        XCTAssertTrue(allCases.contains(.night))
        XCTAssertTrue(allCases.contains(.beforeBed))
        XCTAssertTrue(allCases.contains(.preWorkout))
        XCTAssertTrue(allCases.contains(.postWorkout))
        XCTAssertTrue(allCases.contains(.withMeals))
    }

    func testTimeOfDayRawValues() {
        XCTAssertEqual(TimeOfDay.morning.rawValue, "morning")
        XCTAssertEqual(TimeOfDay.afternoon.rawValue, "afternoon")
        XCTAssertEqual(TimeOfDay.evening.rawValue, "evening")
        XCTAssertEqual(TimeOfDay.night.rawValue, "night")
        XCTAssertEqual(TimeOfDay.beforeBed.rawValue, "before_bed")
        XCTAssertEqual(TimeOfDay.preWorkout.rawValue, "pre_workout")
        XCTAssertEqual(TimeOfDay.postWorkout.rawValue, "post_workout")
        XCTAssertEqual(TimeOfDay.withMeals.rawValue, "with_meals")
    }

    func testTimeOfDayDisplayNames() {
        XCTAssertEqual(TimeOfDay.morning.displayName, "Morning")
        XCTAssertEqual(TimeOfDay.afternoon.displayName, "Afternoon")
        XCTAssertEqual(TimeOfDay.evening.displayName, "Evening")
        XCTAssertEqual(TimeOfDay.night.displayName, "Night")
        XCTAssertEqual(TimeOfDay.beforeBed.displayName, "Before Bed")
        XCTAssertEqual(TimeOfDay.preWorkout.displayName, "Pre-Workout")
        XCTAssertEqual(TimeOfDay.postWorkout.displayName, "Post-Workout")
        XCTAssertEqual(TimeOfDay.withMeals.displayName, "With Meals")
    }

    func testTimeOfDayDisplayNamesNotEmpty() {
        for timeOfDay in TimeOfDay.allCases {
            XCTAssertFalse(timeOfDay.displayName.isEmpty)
            XCTAssertTrue(timeOfDay.displayName.first?.isUppercase == true,
                          "Display name should start with uppercase: \(timeOfDay.displayName)")
        }
    }

    func testTimeOfDayIcons() {
        XCTAssertEqual(TimeOfDay.morning.icon, "sunrise.fill")
        XCTAssertEqual(TimeOfDay.afternoon.icon, "sun.max.fill")
        XCTAssertEqual(TimeOfDay.evening.icon, "sunset.fill")
        XCTAssertEqual(TimeOfDay.night.icon, "moon.stars.fill")
        XCTAssertEqual(TimeOfDay.beforeBed.icon, "moon.fill")
        XCTAssertEqual(TimeOfDay.preWorkout.icon, "figure.run")
        XCTAssertEqual(TimeOfDay.postWorkout.icon, "figure.cooldown")
        XCTAssertEqual(TimeOfDay.withMeals.icon, "fork.knife")
    }

    func testTimeOfDayIconsNotEmpty() {
        for timeOfDay in TimeOfDay.allCases {
            XCTAssertFalse(timeOfDay.icon.isEmpty)
        }
    }

    func testTimeOfDayInitFromRawValue() {
        XCTAssertEqual(TimeOfDay(rawValue: "morning"), .morning)
        XCTAssertEqual(TimeOfDay(rawValue: "before_bed"), .beforeBed)
        XCTAssertEqual(TimeOfDay(rawValue: "post_workout"), .postWorkout)
        XCTAssertNil(TimeOfDay(rawValue: "invalid"))
    }

    func testTimeOfDayCodable() throws {
        let encoder = JSONEncoder()
        let decoder = JSONDecoder()

        for timeOfDay in TimeOfDay.allCases {
            let data = try encoder.encode(timeOfDay)
            let decoded = try decoder.decode(TimeOfDay.self, from: data)
            XCTAssertEqual(decoded, timeOfDay)
        }
    }

    func testTimeOfDayUniqueDisplayNames() {
        let names = TimeOfDay.allCases.map { $0.displayName }
        let uniqueNames = Set(names)
        XCTAssertEqual(names.count, uniqueNames.count, "Each time of day should have a unique display name")
    }

    // MARK: - ScheduledSupplement Tests

    func testScheduledSupplementInitialization() {
        let id = UUID()
        let supplement = createSupplement()
        let scheduledTime = Date()
        let takenAt = Date()

        let scheduled = ScheduledSupplement(
            id: id,
            supplement: supplement,
            scheduledTime: scheduledTime,
            taken: true,
            takenAt: takenAt
        )

        XCTAssertEqual(scheduled.id, id)
        XCTAssertEqual(scheduled.supplement.id, supplement.id)
        XCTAssertEqual(scheduled.scheduledTime, scheduledTime)
        XCTAssertTrue(scheduled.taken)
        XCTAssertEqual(scheduled.takenAt, takenAt)
    }

    func testScheduledSupplementNotTaken() {
        let scheduled = ScheduledSupplement(
            id: UUID(),
            supplement: createSupplement(),
            scheduledTime: Date(),
            taken: false,
            takenAt: nil
        )

        XCTAssertFalse(scheduled.taken)
        XCTAssertNil(scheduled.takenAt)
    }

    func testScheduledSupplementCodable() throws {
        // Note: ScheduledSupplement contains Supplement which has asymmetric encoding.
        // Test decoding from JSON (as received from database).
        let json = """
        {
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "supplement": {
                "id": "660e8400-e29b-41d4-a716-446655440001",
                "patient_id": "770e8400-e29b-41d4-a716-446655440002",
                "name": "Creatine",
                "category": "creatine",
                "dosage": "5g",
                "frequency": "daily",
                "time_of_day": ["morning"],
                "with_food": false,
                "is_active": true,
                "created_at": "2024-01-15T10:30:00Z"
            },
            "scheduled_time": "2024-01-15T08:00:00Z",
            "taken": true,
            "taken_at": "2024-01-15T08:05:00Z"
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let decoded = try decoder.decode(ScheduledSupplement.self, from: json)

        XCTAssertEqual(decoded.id.uuidString.lowercased(), "550e8400-e29b-41d4-a716-446655440000")
        XCTAssertTrue(decoded.taken)
        XCTAssertNotNil(decoded.takenAt)
        XCTAssertEqual(decoded.supplement.name, "Creatine")
    }

    func testScheduledSupplementCodingKeysMapping() throws {
        let scheduled = ScheduledSupplement(
            id: UUID(),
            supplement: createSupplement(),
            scheduledTime: Date(),
            taken: true,
            takenAt: Date()
        )

        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(scheduled)
        let jsonObject = try JSONSerialization.jsonObject(with: data) as! [String: Any]

        // Verify snake_case keys
        XCTAssertNotNil(jsonObject["scheduled_time"])
        XCTAssertNotNil(jsonObject["taken_at"])

        // Verify camelCase keys are NOT present
        XCTAssertNil(jsonObject["scheduledTime"])
        XCTAssertNil(jsonObject["takenAt"])
    }

    // MARK: - SupplementLog Tests

    func testSupplementLogInitialization() {
        let id = UUID()
        let supplementId = UUID()
        let patientId = UUID()
        let takenAt = Date()

        let log = SupplementLog(
            id: id,
            supplementId: supplementId,
            patientId: patientId,
            takenAt: takenAt,
            dosage: "5g",
            notes: "Taken with breakfast"
        )

        XCTAssertEqual(log.id, id)
        XCTAssertEqual(log.supplementId, supplementId)
        XCTAssertEqual(log.patientId, patientId)
        XCTAssertEqual(log.takenAt, takenAt)
        XCTAssertEqual(log.dosage, "5g")
        XCTAssertEqual(log.notes, "Taken with breakfast")
    }

    func testSupplementLogWithNilNotes() {
        let log = SupplementLog(
            id: UUID(),
            supplementId: UUID(),
            patientId: UUID(),
            takenAt: Date(),
            dosage: "1000mg",
            notes: nil
        )

        XCTAssertNil(log.notes)
    }

    func testSupplementLogCodable() throws {
        let original = SupplementLog(
            id: UUID(),
            supplementId: UUID(),
            patientId: UUID(),
            takenAt: Date(),
            dosage: "5g",
            notes: "Test notes"
        )

        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(original)

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let decoded = try decoder.decode(SupplementLog.self, from: data)

        XCTAssertEqual(original.id, decoded.id)
        XCTAssertEqual(original.supplementId, decoded.supplementId)
        XCTAssertEqual(original.patientId, decoded.patientId)
        XCTAssertEqual(original.dosage, decoded.dosage)
        XCTAssertEqual(original.notes, decoded.notes)
    }

    func testSupplementLogCodingKeysMapping() throws {
        let log = SupplementLog(
            id: UUID(),
            supplementId: UUID(),
            patientId: UUID(),
            takenAt: Date(),
            dosage: "5g",
            notes: nil
        )

        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(log)
        let jsonObject = try JSONSerialization.jsonObject(with: data) as! [String: Any]

        // Verify snake_case keys
        XCTAssertNotNil(jsonObject["supplement_id"])
        XCTAssertNotNil(jsonObject["patient_id"])
        XCTAssertNotNil(jsonObject["taken_at"])

        // Verify camelCase keys are NOT present
        XCTAssertNil(jsonObject["supplementId"])
        XCTAssertNil(jsonObject["patientId"])
        XCTAssertNil(jsonObject["takenAt"])
    }

    func testSupplementLogDecoding() throws {
        let json = """
        {
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "supplement_id": "660e8400-e29b-41d4-a716-446655440001",
            "patient_id": "770e8400-e29b-41d4-a716-446655440002",
            "taken_at": "2024-01-15T07:30:00Z",
            "dosage": "5g",
            "notes": "With breakfast"
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let log = try decoder.decode(SupplementLog.self, from: json)

        XCTAssertEqual(log.dosage, "5g")
        XCTAssertEqual(log.notes, "With breakfast")
    }

    // MARK: - Dosage Validation Tests

    func testValidDosageFormats() {
        // Test various valid dosage formats
        let validDosages = [
            "5g",
            "500mg",
            "1000 IU",
            "2 capsules",
            "1 scoop",
            "5000 mcg",
            "2.5g",
            "100-200mg"
        ]

        for dosage in validDosages {
            let supplement = Supplement(
                id: UUID(),
                patientId: UUID(),
                name: "Test",
                brand: nil,
                category: .vitamins,
                dosage: dosage,
                frequency: .daily,
                timeOfDay: [.morning],
                withFood: false,
                notes: nil,
                momentousProductId: nil,
                isActive: true,
                createdAt: Date()
            )
            XCTAssertEqual(supplement.dosage, dosage, "Dosage format '\(dosage)' should be valid")
        }
    }

    func testEmptyDosage() {
        let supplement = Supplement(
            id: UUID(),
            patientId: UUID(),
            name: "Test",
            brand: nil,
            category: .vitamins,
            dosage: "",
            frequency: .daily,
            timeOfDay: [.morning],
            withFood: false,
            notes: nil,
            momentousProductId: nil,
            isActive: true,
            createdAt: Date()
        )
        XCTAssertTrue(supplement.dosage.isEmpty)
    }

    // MARK: - Timing Validation Tests

    func testMultipleTimesOfDay() {
        let supplement = Supplement(
            id: UUID(),
            patientId: UUID(),
            name: "Multi-dose Supplement",
            brand: nil,
            category: .vitamins,
            dosage: "1 capsule",
            frequency: .threeTimesDaily,
            timeOfDay: [.morning, .afternoon, .evening],
            withFood: true,
            notes: nil,
            momentousProductId: nil,
            isActive: true,
            createdAt: Date()
        )

        XCTAssertEqual(supplement.timeOfDay.count, 3)
        XCTAssertTrue(supplement.timeOfDay.contains(.morning))
        XCTAssertTrue(supplement.timeOfDay.contains(.afternoon))
        XCTAssertTrue(supplement.timeOfDay.contains(.evening))
    }

    func testEmptyTimeOfDay() {
        let supplement = Supplement(
            id: UUID(),
            patientId: UUID(),
            name: "As Needed Supplement",
            brand: nil,
            category: .adaptogens,
            dosage: "500mg",
            frequency: .asNeeded,
            timeOfDay: [],
            withFood: false,
            notes: nil,
            momentousProductId: nil,
            isActive: true,
            createdAt: Date()
        )

        XCTAssertTrue(supplement.timeOfDay.isEmpty)
    }

    func testAllTimesOfDay() {
        let allTimes = TimeOfDay.allCases
        let supplement = Supplement(
            id: UUID(),
            patientId: UUID(),
            name: "All Day Supplement",
            brand: nil,
            category: .adaptogens,
            dosage: "100mg",
            frequency: .asNeeded,
            timeOfDay: allTimes,
            withFood: false,
            notes: nil,
            momentousProductId: nil,
            isActive: true,
            createdAt: Date()
        )

        XCTAssertEqual(supplement.timeOfDay.count, allTimes.count)
    }

    // MARK: - Edge Cases Tests

    func testInactiveSupplement() {
        let supplement = Supplement(
            id: UUID(),
            patientId: UUID(),
            name: "Old Supplement",
            brand: nil,
            category: .other,
            dosage: "1g",
            frequency: .daily,
            timeOfDay: [.morning],
            withFood: false,
            notes: nil,
            momentousProductId: nil,
            isActive: false,
            createdAt: Date()
        )

        XCTAssertFalse(supplement.isActive)
    }

    func testSupplementWithLongName() {
        let longName = String(repeating: "A", count: 500)
        let supplement = Supplement(
            id: UUID(),
            patientId: UUID(),
            name: longName,
            brand: nil,
            category: .other,
            dosage: "1g",
            frequency: .daily,
            timeOfDay: [.morning],
            withFood: false,
            notes: nil,
            momentousProductId: nil,
            isActive: true,
            createdAt: Date()
        )

        XCTAssertEqual(supplement.name.count, 500)
    }

    func testSupplementWithSpecialCharactersInName() {
        let supplement = Supplement(
            id: UUID(),
            patientId: UUID(),
            name: "Vitamin D3 (5000 IU) - High Potency",
            brand: "Nature's Bounty",
            category: .vitamins,
            dosage: "5000 IU",
            frequency: .daily,
            timeOfDay: [.morning],
            withFood: true,
            notes: "Take with fatty meal for better absorption",
            momentousProductId: nil,
            isActive: true,
            createdAt: Date()
        )

        XCTAssertEqual(supplement.name, "Vitamin D3 (5000 IU) - High Potency")
        XCTAssertEqual(supplement.brand, "Nature's Bounty")
    }

    func testSupplementWithUnicodeCharacters() {
        let supplement = Supplement(
            id: UUID(),
            patientId: UUID(),
            name: "Ashwagandha (アシュワガンダ)",
            brand: nil,
            category: .adaptogens,
            dosage: "300mg",
            frequency: .daily,
            timeOfDay: [.evening],
            withFood: false,
            notes: nil,
            momentousProductId: nil,
            isActive: true,
            createdAt: Date()
        )

        XCTAssertTrue(supplement.name.contains("アシュワガンダ"))
    }

    // MARK: - EvidenceLevel Tests

    func testEvidenceLevelAllCases() {
        let allCases = EvidenceLevel.allCases
        XCTAssertEqual(allCases.count, 4)
        XCTAssertTrue(allCases.contains(.high))
        XCTAssertTrue(allCases.contains(.moderate))
        XCTAssertTrue(allCases.contains(.low))
        XCTAssertTrue(allCases.contains(.emerging))
    }

    func testEvidenceLevelRawValues() {
        XCTAssertEqual(EvidenceLevel.high.rawValue, "high")
        XCTAssertEqual(EvidenceLevel.moderate.rawValue, "moderate")
        XCTAssertEqual(EvidenceLevel.low.rawValue, "low")
        XCTAssertEqual(EvidenceLevel.emerging.rawValue, "emerging")
    }

    func testEvidenceLevelDisplayNames() {
        XCTAssertEqual(EvidenceLevel.high.displayName, "Strong Evidence")
        XCTAssertEqual(EvidenceLevel.moderate.displayName, "Moderate Evidence")
        XCTAssertEqual(EvidenceLevel.low.displayName, "Limited Evidence")
        XCTAssertEqual(EvidenceLevel.emerging.displayName, "Emerging Research")
    }

    func testEvidenceLevelShortNames() {
        XCTAssertEqual(EvidenceLevel.high.shortName, "Strong")
        XCTAssertEqual(EvidenceLevel.moderate.shortName, "Moderate")
        XCTAssertEqual(EvidenceLevel.low.shortName, "Limited")
        XCTAssertEqual(EvidenceLevel.emerging.shortName, "Emerging")
    }

    func testEvidenceLevelIcons() {
        XCTAssertEqual(EvidenceLevel.high.icon, "checkmark.seal.fill")
        XCTAssertEqual(EvidenceLevel.moderate.icon, "checkmark.seal")
        XCTAssertEqual(EvidenceLevel.low.icon, "questionmark.circle")
        XCTAssertEqual(EvidenceLevel.emerging.icon, "sparkle")
    }

    func testEvidenceLevelCodable() throws {
        let encoder = JSONEncoder()
        let decoder = JSONDecoder()

        for level in EvidenceLevel.allCases {
            let data = try encoder.encode(level)
            let decoded = try decoder.decode(EvidenceLevel.self, from: data)
            XCTAssertEqual(decoded, level)
        }
    }

    // MARK: - Helpers

    private func createSupplement() -> Supplement {
        Supplement(
            id: UUID(),
            patientId: UUID(),
            name: "Creatine Monohydrate",
            brand: "Momentous",
            category: .creatine,
            dosage: "5g",
            frequency: .daily,
            timeOfDay: [.morning],
            withFood: false,
            notes: "Take with water",
            momentousProductId: "creatine-001",
            isActive: true,
            createdAt: Date()
        )
    }
}

// MARK: - Duplicate Supplement Tests

final class DuplicateSupplementTests: XCTestCase {

    func testDuplicateSupplementsInSet() {
        let supplement1 = createSupplement(name: "Vitamin D3")
        let supplement2 = createSupplement(name: "Vitamin D3")
        let supplement3 = createSupplement(name: "Omega-3")

        var set = Set<Supplement>()
        set.insert(supplement1)
        set.insert(supplement2)
        set.insert(supplement3)

        // All should be inserted since they have different IDs
        XCTAssertEqual(set.count, 3)
    }

    func testDuplicateSupplementsWithSameId() {
        let id = UUID()
        let patientId = UUID()
        let date = Date()

        let supplement1 = Supplement(
            id: id,
            patientId: patientId,
            name: "Vitamin D3",
            brand: nil,
            category: .vitamins,
            dosage: "5000 IU",
            frequency: .daily,
            timeOfDay: [.morning],
            withFood: true,
            notes: nil,
            momentousProductId: nil,
            isActive: true,
            createdAt: date
        )

        let supplement2 = Supplement(
            id: id,
            patientId: patientId,
            name: "Vitamin D3",
            brand: nil,
            category: .vitamins,
            dosage: "5000 IU",
            frequency: .daily,
            timeOfDay: [.morning],
            withFood: true,
            notes: nil,
            momentousProductId: nil,
            isActive: true,
            createdAt: date
        )

        var set = Set<Supplement>()
        set.insert(supplement1)
        set.insert(supplement2)

        // Should only have one since they're identical
        XCTAssertEqual(set.count, 1)
    }

    func testFilterDuplicateSupplementsByName() {
        let supplements = [
            createSupplement(name: "Vitamin D3"),
            createSupplement(name: "Vitamin D3"),
            createSupplement(name: "Omega-3"),
            createSupplement(name: "Creatine"),
            createSupplement(name: "Creatine")
        ]

        let uniqueByName = Dictionary(grouping: supplements, by: { $0.name })
            .compactMap { $0.value.first }

        XCTAssertEqual(uniqueByName.count, 3)
    }

    private func createSupplement(name: String) -> Supplement {
        Supplement(
            id: UUID(),
            patientId: UUID(),
            name: name,
            brand: nil,
            category: .vitamins,
            dosage: "500mg",
            frequency: .daily,
            timeOfDay: [.morning],
            withFood: false,
            notes: nil,
            momentousProductId: nil,
            isActive: true,
            createdAt: Date()
        )
    }
}
