#!/bin/bash
# Full Build Deployment Automation
# Usage: ./scripts/deploy_build_local.sh 40

set -e  # Exit on any error

BUILD_NUMBER=$1

if [ -z "$BUILD_NUMBER" ]; then
    echo "❌ Error: Build number required"
    echo "Usage: ./scripts/deploy_build_local.sh 40"
    exit 1
fi

echo "🚀 Deploying Build $BUILD_NUMBER"
echo ""

# ==================== STEP 1: QC CHECKS ====================
echo "📋 Step 1: Running QC checks..."
./scripts/run_qc_checks.sh
echo "✅ QC checks passed!"
echo ""

# ==================== STEP 2: BUILD IN XCODE ====================
echo "📱 Step 2: Building in Xcode..."
echo ""
echo "MANUAL STEPS REQUIRED:"
echo "1. Archive: Product → Archive (⌘⌥B)"
echo "2. Upload: Organizer → Distribute App → App Store Connect"
echo "3. Wait for upload to complete (~10 min)"
echo ""

# Open Xcode project
cd ios-app/PTPerformance
open PTPerformance.xcodeproj

# Wait for user confirmation
echo -n "Press ENTER after upload completes..."
read

echo ""

# ==================== STEP 3: UPDATE LINEAR ====================
echo "📝 Step 3: Updating Linear..."

# Check if LINEAR_API_KEY is set
if [ -z "$LINEAR_API_KEY" ]; then
    echo "⚠️  LINEAR_API_KEY not set - skipping Linear update"
    echo "   To enable Linear automation, set LINEAR_API_KEY in .env"
else
    # Find the build issue (assuming naming convention: ACP-XXX)
    echo "Enter Linear issue ID for this build (e.g., ACP-107):"
    read ISSUE_ID

    if [ -n "$ISSUE_ID" ]; then
        python scripts/linear/update_issue.py \
            --issue "$ISSUE_ID" \
            --status "Done" \
            --comment "Build $BUILD_NUMBER deployed to TestFlight"

        # Create testing issue
        python scripts/linear/create_issue.py \
            --title "Test Build $BUILD_NUMBER on TestFlight" \
            --status "In Progress"
    fi
fi

echo ""

# ==================== STEP 4: CREATE HANDOFF ====================
echo "📄 Step 4: Creating handoff document..."

HANDOFF_FILE=".outcomes/BUILD${BUILD_NUMBER}_DEPLOYMENT_$(date +%Y-%m-%d).md"

cat > "$HANDOFF_FILE" <<EOF
# Build $BUILD_NUMBER Deployment

**Date:** $(date +"%Y-%m-%d %H:%M:%S")
**Build:** $BUILD_NUMBER
**Status:** Deployed to TestFlight

## Summary

Build $BUILD_NUMBER has been deployed to TestFlight successfully.

## QC Checks

- ✅ Unit tests passed
- ✅ Build compilation succeeded
- ✅ Code signing valid
- ✅ Build number incremented
- ✅ Migrations applied

## Next Steps

1. Wait for TestFlight processing (15-30 min)
2. Test on device
3. Update Linear testing issue with results
4. Plan Build $(($BUILD_NUMBER + 1))

---

Generated by: deploy_build_local.sh
EOF

echo "✅ Handoff created: $HANDOFF_FILE"
echo ""

# ==================== COMPLETE ====================
echo "🎉 Build $BUILD_NUMBER deployment complete!"
echo ""
echo "Next steps:"
echo "1. Check App Store Connect for build status"
echo "2. Wait for TestFlight processing"
echo "3. Test on device"
echo "4. Update Linear with test results"
