/**
 * Linear Plan Change Request (PCR) Service
 * Auto-creates Linear issues for HIGH severity flags
 *
 * Zone: 4b (Plan Change Requests), 3c (Backend Service)
 */

import fetch from 'node-fetch';
import { getRecentSessions } from './flags.js';

const LINEAR_API_URL = 'https://api.linear.app/graphql';
const LINEAR_API_KEY = process.env.LINEAR_API_KEY;
const LINEAR_TEAM_ID = process.env.LINEAR_TEAM_ID || '5296cff8-9c53-4cb3-9df3-ccb83601805e';

/**
 * Create a Plan Change Request in Linear for a HIGH severity flag
 * @param {Object} flag - Flag object with severity, rationale, etc.
 * @param {Object} patient - Patient object
 * @returns {Promise<Object>} - Created Linear issue
 */
export async function createPlanChangeRequest(flag, patient) {
  if (!flag || flag.severity !== 'HIGH') {
    throw new Error('Only HIGH severity flags should trigger PCR creation');
  }

  if (!LINEAR_API_KEY) {
    console.error('LINEAR_API_KEY not set - cannot create PCR');
    return null;
  }

  try {
    // Get recent session context
    const recentSessions = await getRecentSessions(flag.patient_id, 3);

    // Get zone-4b label ID
    const zone4bLabelId = await getOrCreateLabel('zone-4b');

    // Get "In Review" state ID
    const inReviewStateId = await getWorkflowState('In Review');

    // Build issue title
    const title = `Plan Change: ${patient.first_name} ${patient.last_name} - ${formatFlagType(flag.flag_type)}`;

    // Build issue description
    const description = buildPCRDescription(flag, patient, recentSessions);

    // Create Linear issue
    const issue = await createLinearIssue({
      title,
      description,
      teamId: LINEAR_TEAM_ID,
      labelIds: zone4bLabelId ? [zone4bLabelId] : [],
      stateId: inReviewStateId,
      priority: 1 // Urgent
    });

    console.log(`✅ Created Plan Change Request: ${issue.identifier} - ${issue.url}`);

    return issue;
  } catch (error) {
    console.error('Error creating Plan Change Request:', error);
    throw error;
  }
}

/**
 * Build formatted PCR description
 */
function buildPCRDescription(flag, patient, recentSessions) {
  const lines = [];

  lines.push('## Plan Change Request - HIGH Severity Flag Detected\n');

  // Patient Info
  lines.push('### Patient Information');
  lines.push(`- **Name:** ${patient.first_name} ${patient.last_name}`);
  lines.push(`- **ID:** ${patient.id}`);
  lines.push(`- **Sport:** ${patient.sport || 'N/A'}`);
  lines.push(`- **Position:** ${patient.position || 'N/A'}`);
  lines.push('');

  // Flag Details
  lines.push('### Flag Details');
  lines.push(`- **Type:** ${formatFlagType(flag.flag_type)}`);
  lines.push(`- **Severity:** ${flag.severity}`);
  lines.push(`- **Triggered:** ${formatDateTime(flag.triggered_at)}`);
  lines.push(`- **Metric:** ${flag.metric_name} = ${flag.metric_value}`);
  lines.push('');

  lines.push('### Rationale');
  lines.push(flag.rationale);
  lines.push('');

  // Recent Sessions Context
  if (recentSessions && recentSessions.length > 0) {
    lines.push('### Recent Sessions (Last 3)');
    recentSessions.forEach((session, idx) => {
      lines.push(`${idx + 1}. **Session ${session.session_id}** - ${formatDateTime(session.performed_at)}`);
      lines.push(`   - Exercises: ${session.exercises.length}`);

      // Show pain scores if available
      const painScores = session.exercises
        .map(ex => ex.pain_score)
        .filter(p => p !== null && p !== undefined);

      if (painScores.length > 0) {
        const avgPain = (painScores.reduce((a, b) => a + b, 0) / painScores.length).toFixed(1);
        const maxPain = Math.max(...painScores);
        lines.push(`   - Pain: avg ${avgPain}/10, max ${maxPain}/10`);
      }
    });
    lines.push('');
  }

  // Context-specific data
  if (flag.context) {
    lines.push('### Additional Context');
    Object.entries(flag.context).forEach(([key, value]) => {
      lines.push(`- **${formatKey(key)}:** ${value}`);
    });
    lines.push('');
  }

  // Action Items
  lines.push('### Recommended Actions');

  if (flag.flag_type.includes('pain')) {
    lines.push('- [ ] Review recent pain logs and trends');
    lines.push('- [ ] Assess workload and exercise intensity');
    lines.push('- [ ] Consider reducing volume or intensity');
    lines.push('- [ ] Schedule PT assessment if needed');
  } else if (flag.flag_type.includes('velocity')) {
    lines.push('- [ ] Review throwing workload and recovery');
    lines.push('- [ ] Check for fatigue or mechanical issues');
    lines.push('- [ ] Consider reducing throwing volume');
    lines.push('- [ ] Assess strength and mobility status');
  } else if (flag.flag_type.includes('throwing_pain')) {
    lines.push('- [ ] Immediate throwing pause recommended');
    lines.push('- [ ] Review mechanics and pitch type breakdown');
    lines.push('- [ ] Assess for injury or strain');
    lines.push('- [ ] Consider medical evaluation');
  }

  lines.push('');
  lines.push('---');
  lines.push('*Auto-generated by PT Performance Platform Risk Engine*');

  return lines.join('\n');
}

/**
 * Create a Linear issue via GraphQL API
 */
async function createLinearIssue({ title, description, teamId, labelIds, stateId, priority }) {
  const mutation = `
    mutation CreateIssue($input: IssueCreateInput!) {
      issueCreate(input: $input) {
        success
        issue {
          id
          identifier
          title
          url
          state {
            name
          }
        }
      }
    }
  `;

  const input = {
    title,
    description,
    teamId,
    priority: priority || 0
  };

  if (labelIds && labelIds.length > 0) {
    input.labelIds = labelIds;
  }

  if (stateId) {
    input.stateId = stateId;
  }

  const response = await fetch(LINEAR_API_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': LINEAR_API_KEY
    },
    body: JSON.stringify({
      query: mutation,
      variables: { input }
    })
  });

  const result = await response.json();

  if (result.errors) {
    throw new Error(`Linear API errors: ${JSON.stringify(result.errors)}`);
  }

  if (!result.data?.issueCreate?.success) {
    throw new Error('Linear issue creation failed');
  }

  return result.data.issueCreate.issue;
}

/**
 * Get or create a label by name
 */
async function getOrCreateLabel(labelName) {
  try {
    // First, try to get existing labels
    const query = `
      query Team($teamId: String!) {
        team(id: $teamId) {
          labels {
            nodes {
              id
              name
            }
          }
        }
      }
    `;

    const response = await fetch(LINEAR_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': LINEAR_API_KEY
      },
      body: JSON.stringify({
        query,
        variables: { teamId: LINEAR_TEAM_ID }
      })
    });

    const result = await response.json();

    if (result.errors) {
      console.error('Error fetching labels:', result.errors);
      return null;
    }

    const labels = result.data?.team?.labels?.nodes || [];
    const existingLabel = labels.find(l => l.name === labelName);

    if (existingLabel) {
      return existingLabel.id;
    }

    // If label doesn't exist, create it
    const createMutation = `
      mutation CreateLabel($input: IssueLabelCreateInput!) {
        issueLabelCreate(input: $input) {
          success
          issueLabel {
            id
            name
          }
        }
      }
    `;

    const createResponse = await fetch(LINEAR_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': LINEAR_API_KEY
      },
      body: JSON.stringify({
        query: createMutation,
        variables: {
          input: {
            name: labelName,
            teamId: LINEAR_TEAM_ID,
            color: '#FF6B6B' // Red for zone-4b
          }
        }
      })
    });

    const createResult = await createResponse.json();

    if (createResult.errors) {
      console.error('Error creating label:', createResult.errors);
      return null;
    }

    return createResult.data?.issueLabelCreate?.issueLabel?.id;
  } catch (error) {
    console.error('Error with label:', error);
    return null;
  }
}

/**
 * Get workflow state ID by name
 */
async function getWorkflowState(stateName) {
  try {
    const query = `
      query Team($teamId: String!) {
        team(id: $teamId) {
          states {
            nodes {
              id
              name
              type
            }
          }
        }
      }
    `;

    const response = await fetch(LINEAR_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': LINEAR_API_KEY
      },
      body: JSON.stringify({
        query,
        variables: { teamId: LINEAR_TEAM_ID }
      })
    });

    const result = await response.json();

    if (result.errors) {
      console.error('Error fetching workflow states:', result.errors);
      return null;
    }

    const states = result.data?.team?.states?.nodes || [];
    const state = states.find(s => s.name === stateName);

    return state?.id || null;
  } catch (error) {
    console.error('Error fetching workflow state:', error);
    return null;
  }
}

// ==================== HELPER FUNCTIONS ====================

function formatFlagType(flagType) {
  return flagType
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

function formatKey(key) {
  return key
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

function formatDateTime(dateString) {
  if (!dateString) return 'N/A';
  const date = new Date(dateString);
  return date.toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
}
