-- Seed HIIT workout templates
-- Based on Tabata, EMOM, AMRAP, and other popular HIIT protocols

INSERT INTO system_workout_templates (id, name, description, category, difficulty, duration_minutes, exercises, tags, source_file) VALUES

-- TABATA WORKOUTS (20 sec on, 10 sec off, 8 rounds = 4 min per exercise)
('011b0001-0001-4000-8000-000000000001', 'Classic Tabata - Bodyweight', '4-minute Tabata protocol with bodyweight exercises. Maximum intensity, maximum results.', 'cardio', 'intermediate', 20,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "2 min"}, {"name": "High Knees", "duration": "1 min"}, {"name": "Arm Circles", "duration": "1 min"}]}, {"name": "Tabata Round 1", "sequence": 1, "exercises": [{"name": "Burpees", "sets": 8, "reps": "20 sec on / 10 sec off", "notes": "4 min total"}]}, {"name": "Rest", "sequence": 2, "exercises": [{"name": "Active Recovery", "duration": "1 min"}]}, {"name": "Tabata Round 2", "sequence": 3, "exercises": [{"name": "Mountain Climbers", "sets": 8, "reps": "20 sec on / 10 sec off", "notes": "4 min total"}]}, {"name": "Rest", "sequence": 4, "exercises": [{"name": "Active Recovery", "duration": "1 min"}]}, {"name": "Tabata Round 3", "sequence": 5, "exercises": [{"name": "Jump Squats", "sets": 8, "reps": "20 sec on / 10 sec off", "notes": "4 min total"}]}, {"name": "Cool Down", "sequence": 6, "exercises": [{"name": "Walking", "duration": "2 min"}, {"name": "Stretch", "duration": "2 min"}]}]}',
ARRAY['hiit', 'tabata', 'bodyweight', 'cardio', 'fat-burn'], 'tabata_bodyweight.md'),

('011b0001-0002-4000-8000-000000000002', 'Tabata Sprint Intervals', 'Running Tabata - the original protocol Dr. Izumi Tabata used with Olympic speed skaters.', 'cardio', 'advanced', 15,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Light Jog", "duration": "3 min"}, {"name": "Dynamic Stretches", "duration": "2 min"}]}, {"name": "Tabata Sprints", "sequence": 1, "exercises": [{"name": "Sprint", "sets": 8, "reps": "20 sec sprint / 10 sec rest", "notes": "All-out effort each sprint"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Walking", "duration": "3 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['hiit', 'tabata', 'running', 'sprint', 'olympic'], 'tabata_sprint.md'),

('011b0001-0003-4000-8000-000000000003', 'Tabata Core Crusher', 'Target your core with this 4-round Tabata workout. Abs on fire guaranteed.', 'cardio', 'intermediate', 25,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Cat Cow", "sets": 2, "reps": "10"}, {"name": "Plank Hold", "duration": "30 sec"}]}, {"name": "Tabata 1 - Plank", "sequence": 1, "exercises": [{"name": "Plank Jacks", "sets": 8, "reps": "20 sec on / 10 sec off"}]}, {"name": "Rest", "sequence": 2, "exercises": [{"name": "Rest", "duration": "1 min"}]}, {"name": "Tabata 2 - Crunch", "sequence": 3, "exercises": [{"name": "Bicycle Crunches", "sets": 8, "reps": "20 sec on / 10 sec off"}]}, {"name": "Rest", "sequence": 4, "exercises": [{"name": "Rest", "duration": "1 min"}]}, {"name": "Tabata 3 - Mountain Climber", "sequence": 5, "exercises": [{"name": "Mountain Climbers", "sets": 8, "reps": "20 sec on / 10 sec off"}]}, {"name": "Rest", "sequence": 6, "exercises": [{"name": "Rest", "duration": "1 min"}]}, {"name": "Tabata 4 - V-Up", "sequence": 7, "exercises": [{"name": "V-Ups", "sets": 8, "reps": "20 sec on / 10 sec off"}]}, {"name": "Cool Down", "sequence": 8, "exercises": [{"name": "Child Pose", "duration": "1 min"}, {"name": "Spinal Twist", "sets": 1, "reps": "30 sec each"}]}]}',
ARRAY['hiit', 'tabata', 'core', 'abs', 'bodyweight'], 'tabata_core.md'),

-- EMOM WORKOUTS (Every Minute on the Minute)
('011b0001-0004-4000-8000-000000000004', 'EMOM 20: Full Body Blast', 'Every minute on the minute for 20 minutes. Complete the reps, rest the remainder.', 'cardio', 'intermediate', 25,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "2 min"}, {"name": "Bodyweight Squats", "sets": 1, "reps": "10"}]}, {"name": "EMOM 20 Minutes", "sequence": 1, "exercises": [{"name": "Minute 1: Push-Ups", "reps": "12"}, {"name": "Minute 2: Air Squats", "reps": "15"}, {"name": "Minute 3: Burpees", "reps": "8"}, {"name": "Minute 4: Sit-Ups", "reps": "15"}, {"name": "Repeat 5 Rounds", "notes": "Complete all 4 exercises, 5 times through"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Walking", "duration": "2 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['hiit', 'emom', 'bodyweight', 'full-body', 'conditioning'], 'emom_full_body.md'),

('011b0001-0005-4000-8000-000000000005', 'EMOM 15: Kettlebell Power', 'Kettlebell EMOM for strength and conditioning. Quality reps, controlled power.', 'cardio', 'intermediate', 20,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Halo", "sets": 2, "reps": "8 each direction"}, {"name": "Goblet Squat", "sets": 2, "reps": "8"}]}, {"name": "EMOM 15 Minutes", "sequence": 1, "exercises": [{"name": "Minute 1: Kettlebell Swings", "reps": "15"}, {"name": "Minute 2: Goblet Squats", "reps": "10"}, {"name": "Minute 3: KB Clean & Press (alternating)", "reps": "10 total"}, {"name": "Repeat 5 Rounds", "notes": "Complete all 3 exercises, 5 times through"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Hip Stretch", "duration": "2 min"}, {"name": "Shoulder Stretch", "duration": "2 min"}]}]}',
ARRAY['hiit', 'emom', 'kettlebell', 'strength', 'conditioning'], 'emom_kettlebell.md'),

('011b0001-0006-4000-8000-000000000006', 'EMOM 12: Core Focus', 'Core-centric EMOM to build midline stability and endurance.', 'cardio', 'intermediate', 18,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Cat Cow", "sets": 2, "reps": "10"}, {"name": "Dead Bug", "sets": 2, "reps": "8 each"}]}, {"name": "EMOM 12 Minutes", "sequence": 1, "exercises": [{"name": "Minute 1: Plank Hold", "duration": "45 sec"}, {"name": "Minute 2: Russian Twists", "reps": "20 total"}, {"name": "Minute 3: Leg Raises", "reps": "12"}, {"name": "Minute 4: Mountain Climbers", "reps": "20 total"}, {"name": "Repeat 3 Rounds", "notes": "Complete all 4 exercises, 3 times through"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Child Pose", "duration": "1 min"}, {"name": "Spinal Twist", "sets": 1, "reps": "30 sec each"}]}]}',
ARRAY['hiit', 'emom', 'core', 'bodyweight', 'abs'], 'emom_core.md'),

-- AMRAP WORKOUTS (As Many Rounds As Possible)
('011b0001-0007-4000-8000-000000000007', 'AMRAP 20: CrossFit Style', 'Classic 20-minute AMRAP. Push your limits and count those rounds.', 'cardio', 'intermediate', 25,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Row or Bike", "duration": "3 min"}, {"name": "Dynamic Stretches", "duration": "2 min"}]}, {"name": "AMRAP 20 Minutes", "sequence": 1, "exercises": [{"name": "5 Pull-Ups (or Ring Rows)", "reps": "5"}, {"name": "10 Push-Ups", "reps": "10"}, {"name": "15 Air Squats", "reps": "15"}, {"name": "As Many Rounds As Possible", "notes": "Record total rounds + reps"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Light Row/Bike", "duration": "2 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['hiit', 'amrap', 'crossfit', 'bodyweight', 'conditioning'], 'amrap_crossfit_style.md'),

('011b0001-0008-4000-8000-000000000008', 'AMRAP 15: Dumbbell Complex', 'Dumbbell AMRAP for total body conditioning. One pair of dumbbells, max effort.', 'cardio', 'intermediate', 22,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Arm Circles", "duration": "1 min"}, {"name": "Bodyweight Squats", "sets": 1, "reps": "10"}, {"name": "Push-Ups", "sets": 1, "reps": "10"}]}, {"name": "AMRAP 15 Minutes", "sequence": 1, "exercises": [{"name": "8 Dumbbell Thrusters", "reps": "8"}, {"name": "8 Renegade Rows (4 each)", "reps": "8 total"}, {"name": "8 Dumbbell Lunges (4 each)", "reps": "8 total"}, {"name": "8 Dumbbell Deadlifts", "reps": "8"}, {"name": "As Many Rounds As Possible", "notes": "Record total rounds + reps"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Walking", "duration": "2 min"}, {"name": "Full Body Stretch", "duration": "3 min"}]}]}',
ARRAY['hiit', 'amrap', 'dumbbell', 'strength', 'conditioning'], 'amrap_dumbbell.md'),

('011b0001-0009-4000-8000-000000000009', 'AMRAP 10: Burpee Ladder', 'Ascending burpee ladder in 10 minutes. Simple but brutal.', 'cardio', 'advanced', 15,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "2 min"}, {"name": "Bodyweight Squats", "sets": 1, "reps": "10"}]}, {"name": "AMRAP 10 Minutes", "sequence": 1, "exercises": [{"name": "Round 1: 1 Burpee + 1 Air Squat", "reps": "1 each"}, {"name": "Round 2: 2 Burpees + 2 Air Squats", "reps": "2 each"}, {"name": "Round 3: 3 Burpees + 3 Air Squats", "reps": "3 each"}, {"name": "Continue Ladder", "notes": "Add 1 rep each round until time expires"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Walking", "duration": "2 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['hiit', 'amrap', 'burpee', 'ladder', 'bodyweight'], 'amrap_burpee_ladder.md'),

-- CIRCUIT TRAINING
('011b0001-0010-4000-8000-000000000010', 'Cardio Circuit Crusher', '4-station circuit repeated 4 times. Heart rate up, calories down.', 'cardio', 'intermediate', 30,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "March in Place", "duration": "2 min"}, {"name": "Arm Swings", "duration": "1 min"}, {"name": "Leg Swings", "duration": "1 min"}]}, {"name": "Circuit - 4 Rounds", "sequence": 1, "exercises": [{"name": "Jumping Jacks", "duration": "45 sec"}, {"name": "High Knees", "duration": "45 sec"}, {"name": "Burpees", "duration": "45 sec"}, {"name": "Mountain Climbers", "duration": "45 sec"}, {"name": "Rest", "duration": "60 sec between rounds"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Walking", "duration": "3 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['hiit', 'circuit', 'cardio', 'bodyweight', 'fat-burn'], 'cardio_circuit.md'),

('011b0001-0011-4000-8000-000000000011', 'Upper Body HIIT Circuit', 'Push and pull movements in high-intensity circuit format.', 'cardio', 'intermediate', 28,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Arm Circles", "duration": "1 min"}, {"name": "Push-Ups", "sets": 1, "reps": "10"}, {"name": "Band Pull-Aparts", "sets": 2, "reps": "15"}]}, {"name": "Circuit - 4 Rounds", "sequence": 1, "exercises": [{"name": "Push-Ups", "reps": "15"}, {"name": "Inverted Rows", "reps": "12"}, {"name": "Diamond Push-Ups", "reps": "10"}, {"name": "Plank Shoulder Taps", "reps": "20 total"}, {"name": "Dips (bench or rings)", "reps": "12"}, {"name": "Rest", "duration": "60 sec between rounds"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Chest Stretch", "duration": "1 min"}, {"name": "Lat Stretch", "duration": "1 min"}, {"name": "Tricep Stretch", "duration": "1 min"}]}]}',
ARRAY['hiit', 'circuit', 'upper-body', 'push', 'pull'], 'upper_body_hiit.md'),

('011b0001-0012-4000-8000-000000000012', 'Lower Body HIIT Circuit', 'Legs and glutes focused HIIT. Build strength while burning fat.', 'cardio', 'intermediate', 28,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Bodyweight Squats", "sets": 2, "reps": "10"}, {"name": "Leg Swings", "sets": 2, "reps": "10 each"}, {"name": "Glute Bridges", "sets": 2, "reps": "10"}]}, {"name": "Circuit - 4 Rounds", "sequence": 1, "exercises": [{"name": "Jump Squats", "reps": "15"}, {"name": "Alternating Lunges", "reps": "20 total"}, {"name": "Sumo Squat Pulses", "reps": "20"}, {"name": "Single Leg Glute Bridge", "reps": "10 each"}, {"name": "Broad Jumps", "reps": "10"}, {"name": "Rest", "duration": "60 sec between rounds"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Quad Stretch", "duration": "1 min each"}, {"name": "Hamstring Stretch", "duration": "1 min each"}, {"name": "Hip Flexor Stretch", "duration": "1 min each"}]}]}',
ARRAY['hiit', 'circuit', 'lower-body', 'legs', 'glutes'], 'lower_body_hiit.md'),

-- INTERVAL WORKOUTS
('011b0001-0013-4000-8000-000000000013', '30-20-10 Interval Training', 'Danish protocol: 30 sec easy, 20 sec moderate, 10 sec all-out. Proven effective.', 'cardio', 'intermediate', 25,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Light Jog or Row", "duration": "5 min"}]}, {"name": "30-20-10 Intervals - 5 Blocks", "sequence": 1, "exercises": [{"name": "Block Structure", "notes": "30 sec easy pace, 20 sec moderate, 10 sec sprint"}, {"name": "Repeat 5x per block", "notes": "5 min per block"}, {"name": "Rest 2 min between blocks", "duration": "2 min rest"}, {"name": "Total: 5 blocks", "notes": "Choose: Running, Rowing, Cycling, or Ski Erg"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Light Movement", "duration": "3 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['hiit', 'interval', 'danish', 'cardio', 'running'], '30_20_10_intervals.md'),

('011b0001-0014-4000-8000-000000000014', 'Fartlek Fun Run', 'Speed play running workout. Unstructured intervals based on feel.', 'cardio', 'intermediate', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Easy Jog", "duration": "5 min"}, {"name": "Dynamic Stretches", "duration": "3 min"}]}, {"name": "Fartlek Session", "sequence": 1, "exercises": [{"name": "Easy Jog", "duration": "2 min"}, {"name": "Moderate Pace", "duration": "1 min"}, {"name": "Easy Jog", "duration": "2 min"}, {"name": "Fast Run", "duration": "30 sec"}, {"name": "Easy Jog", "duration": "2 min"}, {"name": "Tempo Pace", "duration": "3 min"}, {"name": "Easy Jog", "duration": "2 min"}, {"name": "Sprint", "duration": "20 sec"}, {"name": "Repeat Pattern", "notes": "Mix intensities based on feel for 20 min"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Easy Jog", "duration": "3 min"}, {"name": "Walking", "duration": "2 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['hiit', 'fartlek', 'running', 'cardio', 'speed-play'], 'fartlek_run.md'),

('011b0001-0015-4000-8000-000000000015', 'Pyramid Intervals', 'Work up then back down: 1-2-3-4-3-2-1 minute intervals.', 'cardio', 'advanced', 30,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Light Cardio", "duration": "5 min"}]}, {"name": "Pyramid", "sequence": 1, "exercises": [{"name": "Hard Effort", "duration": "1 min"}, {"name": "Easy Recovery", "duration": "1 min"}, {"name": "Hard Effort", "duration": "2 min"}, {"name": "Easy Recovery", "duration": "1 min"}, {"name": "Hard Effort", "duration": "3 min"}, {"name": "Easy Recovery", "duration": "1.5 min"}, {"name": "Hard Effort", "duration": "4 min"}, {"name": "Easy Recovery", "duration": "2 min"}, {"name": "Hard Effort", "duration": "3 min"}, {"name": "Easy Recovery", "duration": "1.5 min"}, {"name": "Hard Effort", "duration": "2 min"}, {"name": "Easy Recovery", "duration": "1 min"}, {"name": "Hard Effort", "duration": "1 min"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Light Movement", "duration": "3 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['hiit', 'pyramid', 'interval', 'cardio', 'endurance'], 'pyramid_intervals.md'),

-- SPECIALTY HIIT
('011b0001-0016-4000-8000-000000000016', 'Boxing HIIT', 'Boxing-inspired HIIT with punching combinations and footwork.', 'cardio', 'intermediate', 30,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jump Rope", "duration": "3 min"}, {"name": "Shadow Boxing Light", "duration": "2 min"}]}, {"name": "Round 1-3: Combos", "sequence": 1, "exercises": [{"name": "Jab-Cross", "duration": "3 min"}, {"name": "Rest", "duration": "1 min"}, {"name": "Jab-Cross-Hook", "duration": "3 min"}, {"name": "Rest", "duration": "1 min"}, {"name": "Full Combo: 1-2-3-4", "duration": "3 min"}, {"name": "Rest", "duration": "1 min"}]}, {"name": "Round 4-5: Conditioning", "sequence": 2, "exercises": [{"name": "Burpees", "duration": "30 sec"}, {"name": "Shadow Box", "duration": "30 sec"}, {"name": "Repeat 6x", "notes": "2 rounds of this pattern"}]}, {"name": "Round 6: Finisher", "sequence": 3, "exercises": [{"name": "Speed Punches", "duration": "20 sec"}, {"name": "Rest", "duration": "10 sec"}, {"name": "Repeat 8x Tabata style", "notes": "4 min total"}]}, {"name": "Cool Down", "sequence": 4, "exercises": [{"name": "Light Shadow Box", "duration": "2 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['hiit', 'boxing', 'cardio', 'combat', 'conditioning'], 'boxing_hiit.md'),

('011b0001-0017-4000-8000-000000000017', 'Rowing HIIT Intervals', 'Rowing machine intervals for total body conditioning.', 'cardio', 'intermediate', 25,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Easy Row", "duration": "3 min"}, {"name": "Build Pace", "duration": "2 min"}]}, {"name": "Intervals", "sequence": 1, "exercises": [{"name": "500m Row - Fast", "notes": "Record time"}, {"name": "Rest", "duration": "90 sec"}, {"name": "500m Row - Fast", "notes": "Try to match or beat"}, {"name": "Rest", "duration": "90 sec"}, {"name": "500m Row - Fast", "notes": "Final effort"}, {"name": "Rest", "duration": "2 min"}, {"name": "250m Sprint x 4", "notes": "60 sec rest between"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Easy Row", "duration": "3 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['hiit', 'rowing', 'cardio', 'machine', 'conditioning'], 'rowing_hiit.md'),

('011b0001-0018-4000-8000-000000000018', 'Jump Rope HIIT', 'Skip your way to fitness with this jump rope interval workout.', 'cardio', 'intermediate', 22,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Light Jumping", "duration": "2 min"}, {"name": "Dynamic Stretches", "duration": "2 min"}]}, {"name": "Jump Rope Intervals", "sequence": 1, "exercises": [{"name": "Basic Jump", "duration": "1 min"}, {"name": "Rest", "duration": "30 sec"}, {"name": "High Knees Jump", "duration": "1 min"}, {"name": "Rest", "duration": "30 sec"}, {"name": "Single Leg Hops (alt)", "duration": "1 min"}, {"name": "Rest", "duration": "30 sec"}, {"name": "Double Unders or Fast Singles", "duration": "1 min"}, {"name": "Rest", "duration": "1 min"}, {"name": "Repeat 3 Rounds", "notes": "12 min total work"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Easy Jumping", "duration": "2 min"}, {"name": "Calf Stretch", "duration": "1 min each"}, {"name": "Full Body Stretch", "duration": "2 min"}]}]}',
ARRAY['hiit', 'jump-rope', 'cardio', 'conditioning', 'plyometric'], 'jump_rope_hiit.md'),

('011b0001-0019-4000-8000-000000000019', 'Staircase HIIT', 'Use stairs for this lower body and cardio blast.', 'cardio', 'intermediate', 25,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Walk Up/Down Stairs", "duration": "2 min"}, {"name": "Bodyweight Squats", "sets": 2, "reps": "10"}, {"name": "Calf Raises", "sets": 2, "reps": "15"}]}, {"name": "Stair Intervals", "sequence": 1, "exercises": [{"name": "Sprint Up, Walk Down", "reps": "5 flights"}, {"name": "Rest", "duration": "1 min"}, {"name": "Skip a Step Sprint", "reps": "5 flights"}, {"name": "Rest", "duration": "1 min"}, {"name": "Lateral Step-Ups", "reps": "3 flights each side"}, {"name": "Rest", "duration": "1 min"}, {"name": "Single Leg Hops Up", "reps": "3 flights each"}, {"name": "Rest", "duration": "1 min"}, {"name": "Sprint Up, Walk Down", "reps": "5 flights"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Walk Up/Down Slowly", "duration": "2 min"}, {"name": "Quad Stretch", "duration": "1 min each"}, {"name": "Calf Stretch", "duration": "1 min each"}]}]}',
ARRAY['hiit', 'stairs', 'cardio', 'lower-body', 'outdoor'], 'staircase_hiit.md'),

-- BEGINNER HIIT
('011b0001-0020-4000-8000-000000000020', 'Beginner HIIT - Low Impact', 'Introduction to HIIT without jumping. Joint-friendly cardio blast.', 'cardio', 'beginner', 22,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "March in Place", "duration": "2 min"}, {"name": "Arm Circles", "duration": "1 min"}, {"name": "Bodyweight Squats", "sets": 1, "reps": "10"}]}, {"name": "HIIT Circuit - 3 Rounds", "sequence": 1, "exercises": [{"name": "March with High Knees", "duration": "30 sec"}, {"name": "Rest", "duration": "15 sec"}, {"name": "Squat to Stand", "duration": "30 sec"}, {"name": "Rest", "duration": "15 sec"}, {"name": "Standing Mountain Climbers", "duration": "30 sec"}, {"name": "Rest", "duration": "15 sec"}, {"name": "Lateral Shuffles", "duration": "30 sec"}, {"name": "Rest", "duration": "15 sec"}, {"name": "1 min rest between rounds", "duration": "1 min"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Walking", "duration": "2 min"}, {"name": "Full Body Stretch", "duration": "4 min"}]}]}',
ARRAY['hiit', 'beginner', 'low-impact', 'cardio', 'joint-friendly'], 'beginner_hiit.md'),

('011b0001-0021-4000-8000-000000000021', 'HIIT for Seniors', 'Age-appropriate high-intensity intervals with safety modifications.', 'cardio', 'beginner', 20,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Seated March", "duration": "2 min"}, {"name": "Arm Raises", "sets": 2, "reps": "10"}, {"name": "Ankle Circles", "sets": 2, "reps": "10 each"}]}, {"name": "Intervals - 3 Rounds", "sequence": 1, "exercises": [{"name": "Fast March in Place", "duration": "30 sec"}, {"name": "Rest", "duration": "30 sec"}, {"name": "Chair Squats", "duration": "30 sec"}, {"name": "Rest", "duration": "30 sec"}, {"name": "Wall Push-Ups", "duration": "30 sec"}, {"name": "Rest", "duration": "30 sec"}, {"name": "Standing Side Leg Lifts", "duration": "30 sec"}, {"name": "Rest", "duration": "1 min between rounds"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Slow March", "duration": "2 min"}, {"name": "Seated Stretches", "duration": "4 min"}]}]}',
ARRAY['hiit', 'beginner', 'seniors', 'low-impact', 'safe'], 'hiit_seniors.md'),

-- ADVANCED HIIT
('011b0001-0022-4000-8000-000000000022', 'Death by Burpees', 'Ascending ladder of burpees. How far can you go before time runs out?', 'cardio', 'advanced', 20,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "2 min"}, {"name": "Push-Ups", "sets": 1, "reps": "10"}, {"name": "Squats", "sets": 1, "reps": "10"}]}, {"name": "Death by Burpees", "sequence": 1, "exercises": [{"name": "Minute 1", "reps": "1 burpee"}, {"name": "Minute 2", "reps": "2 burpees"}, {"name": "Minute 3", "reps": "3 burpees"}, {"name": "Continue adding 1 each minute", "notes": "Rest remainder of minute"}, {"name": "Until you cannot complete reps in 1 minute", "notes": "Record highest round completed"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Walking", "duration": "3 min"}, {"name": "Full Body Stretch", "duration": "3 min"}]}]}',
ARRAY['hiit', 'advanced', 'burpee', 'death-by', 'challenge'], 'death_by_burpees.md'),

('011b0001-0023-4000-8000-000000000023', 'The Filthy Fifty Lite', 'Scaled version of the CrossFit classic. 30 reps of 10 movements.', 'cardio', 'advanced', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Row or Bike", "duration": "3 min"}, {"name": "Dynamic Stretches", "duration": "2 min"}]}, {"name": "Filthy Thirty", "sequence": 1, "exercises": [{"name": "Box Jumps (or Step-Ups)", "reps": "30"}, {"name": "Jumping Pull-Ups (or Ring Rows)", "reps": "30"}, {"name": "Kettlebell Swings", "reps": "30"}, {"name": "Walking Lunges (steps)", "reps": "30"}, {"name": "Knees to Elbows (or Sit-Ups)", "reps": "30"}, {"name": "Push Press", "reps": "30"}, {"name": "Hip Extensions", "reps": "30"}, {"name": "Wall Balls", "reps": "30"}, {"name": "Burpees", "reps": "30"}, {"name": "Double Unders (or 60 Singles)", "reps": "30"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Light Movement", "duration": "3 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['hiit', 'advanced', 'crossfit', 'chipper', 'conditioning'], 'filthy_thirty.md'),

('011b0001-0024-4000-8000-000000000024', 'Sprint 8 Protocol', 'Research-backed 20-minute protocol. 8 all-out 30-second sprints.', 'cardio', 'advanced', 20,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Light Jog or Bike", "duration": "3 min"}, {"name": "Build to Moderate", "duration": "2 min"}]}, {"name": "Sprint 8", "sequence": 1, "exercises": [{"name": "Sprint 1", "duration": "30 sec all-out"}, {"name": "Recovery", "duration": "90 sec easy"}, {"name": "Sprint 2", "duration": "30 sec all-out"}, {"name": "Recovery", "duration": "90 sec easy"}, {"name": "Sprint 3", "duration": "30 sec all-out"}, {"name": "Recovery", "duration": "90 sec easy"}, {"name": "Sprint 4", "duration": "30 sec all-out"}, {"name": "Recovery", "duration": "90 sec easy"}, {"name": "Sprint 5", "duration": "30 sec all-out"}, {"name": "Recovery", "duration": "90 sec easy"}, {"name": "Sprint 6", "duration": "30 sec all-out"}, {"name": "Recovery", "duration": "90 sec easy"}, {"name": "Sprint 7", "duration": "30 sec all-out"}, {"name": "Recovery", "duration": "90 sec easy"}, {"name": "Sprint 8", "duration": "30 sec all-out"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Easy Movement", "duration": "3 min"}, {"name": "Stretch", "duration": "2 min"}]}]}',
ARRAY['hiit', 'sprint', 'advanced', 'research', 'protocol'], 'sprint_8.md'),

('011b0001-0025-4000-8000-000000000025', '1000 Rep Challenge', 'Epic endurance challenge: 100 reps of 10 exercises. Time yourself.', 'cardio', 'advanced', 45,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Light Cardio", "duration": "5 min"}, {"name": "Dynamic Stretches", "duration": "3 min"}]}, {"name": "1000 Reps - For Time", "sequence": 1, "exercises": [{"name": "Jumping Jacks", "reps": "100"}, {"name": "Bodyweight Squats", "reps": "100"}, {"name": "Push-Ups", "reps": "100"}, {"name": "Sit-Ups", "reps": "100"}, {"name": "Lunges (total steps)", "reps": "100"}, {"name": "Mountain Climbers (total)", "reps": "100"}, {"name": "Burpees", "reps": "100"}, {"name": "High Knees (total)", "reps": "100"}, {"name": "Tricep Dips", "reps": "100"}, {"name": "Plank Jacks", "reps": "100"}, {"name": "Record Total Time", "notes": "Break up sets as needed"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Walking", "duration": "5 min"}, {"name": "Full Body Stretch", "duration": "5 min"}]}]}',
ARRAY['hiit', 'advanced', 'endurance', 'challenge', '1000-rep'], '1000_rep_challenge.md');
