-- Seed Functional Fitness workout templates
-- Based on 7 movement patterns: Squat, Hinge, Lunge, Push, Pull, Carry, Rotate

INSERT INTO system_workout_templates (id, name, description, category, difficulty, duration_minutes, exercises, tags, source_file) VALUES

-- FOUNDATIONAL FUNCTIONAL
('f00c0001-0001-4000-8000-000000000001', 'Functional Foundations', 'Learn the 7 fundamental movement patterns. Build movement quality before intensity.', 'full_body', 'beginner', 35,
'{"blocks": [{"name": "Movement Prep", "sequence": 0, "exercises": [{"name": "Cat Cow", "sets": 2, "reps": "8"}, {"name": "World Greatest Stretch", "sets": 2, "reps": "3 each"}, {"name": "Glute Bridge", "sets": 2, "reps": "10"}]}, {"name": "Squat Pattern", "sequence": 1, "exercises": [{"name": "Bodyweight Squat", "sets": 3, "reps": "10"}, {"name": "Goblet Squat Hold", "sets": 2, "reps": "30 sec"}]}, {"name": "Hinge Pattern", "sequence": 2, "exercises": [{"name": "Hip Hinge with Dowel", "sets": 3, "reps": "10"}, {"name": "Romanian Deadlift - Bodyweight", "sets": 2, "reps": "10"}]}, {"name": "Lunge Pattern", "sequence": 3, "exercises": [{"name": "Split Squat", "sets": 2, "reps": "8 each"}, {"name": "Reverse Lunge", "sets": 2, "reps": "8 each"}]}, {"name": "Push Pattern", "sequence": 4, "exercises": [{"name": "Wall Push-Up", "sets": 2, "reps": "10"}, {"name": "Incline Push-Up", "sets": 2, "reps": "10"}]}, {"name": "Pull Pattern", "sequence": 5, "exercises": [{"name": "Band Pull-Apart", "sets": 3, "reps": "15"}, {"name": "Inverted Row", "sets": 2, "reps": "8"}]}, {"name": "Carry", "sequence": 6, "exercises": [{"name": "Farmers Walk", "duration": "30 sec"}, {"name": "Suitcase Carry", "sets": 1, "reps": "30 sec each"}]}, {"name": "Rotate", "sequence": 7, "exercises": [{"name": "Pallof Press", "sets": 2, "reps": "10 each"}, {"name": "Bird Dog", "sets": 2, "reps": "8 each"}]}]}',
ARRAY['functional', 'beginner', 'movement-patterns', 'foundation', 'full-body'], 'functional_foundations.md'),

('f00c0001-0002-4000-8000-000000000002', 'Everyday Functional Fitness', 'Train for real life. Movements that make daily activities easier and safer.', 'full_body', 'beginner', 30,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "March in Place", "duration": "2 min"}, {"name": "Arm Circles", "sets": 2, "reps": "10 each direction"}]}, {"name": "Getting Up & Down", "sequence": 1, "exercises": [{"name": "Sit to Stand (from chair)", "sets": 3, "reps": "10"}, {"name": "Turkish Get-Up (no weight)", "sets": 2, "reps": "3 each side"}]}, {"name": "Lifting & Carrying", "sequence": 2, "exercises": [{"name": "Deadlift Pattern", "sets": 3, "reps": "8"}, {"name": "Farmers Walk", "sets": 3, "reps": "40 yards"}]}, {"name": "Reaching & Pushing", "sequence": 3, "exercises": [{"name": "Overhead Press", "sets": 3, "reps": "8"}, {"name": "Push-Up", "sets": 2, "reps": "10"}]}, {"name": "Pulling", "sequence": 4, "exercises": [{"name": "Row", "sets": 3, "reps": "10"}, {"name": "Face Pull", "sets": 2, "reps": "12"}]}, {"name": "Balance", "sequence": 5, "exercises": [{"name": "Single Leg Stand", "sets": 2, "reps": "30 sec each"}, {"name": "Step Up", "sets": 2, "reps": "8 each"}]}]}',
ARRAY['functional', 'beginner', 'everyday', 'practical', 'daily-life'], 'everyday_functional.md'),

-- STRENGTH-FOCUSED FUNCTIONAL
('f00c0001-0003-4000-8000-000000000003', 'Functional Strength Builder', 'Build real-world strength with compound movements and loaded carries.', 'strength', 'intermediate', 45,
'{"blocks": [{"name": "Dynamic Warm Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "1 min"}, {"name": "Leg Swings", "sets": 2, "reps": "10 each"}, {"name": "Arm Swings", "sets": 2, "reps": "10"}]}, {"name": "Power", "sequence": 1, "exercises": [{"name": "Kettlebell Swing", "sets": 4, "reps": "12"}, {"name": "Medicine Ball Slam", "sets": 3, "reps": "10"}]}, {"name": "Lower Body Strength", "sequence": 2, "exercises": [{"name": "Goblet Squat", "sets": 4, "reps": "10"}, {"name": "Romanian Deadlift", "sets": 4, "reps": "8"}, {"name": "Walking Lunge", "sets": 3, "reps": "10 each"}]}, {"name": "Upper Body Strength", "sequence": 3, "exercises": [{"name": "Push-Up Variation", "sets": 4, "reps": "12"}, {"name": "Dumbbell Row", "sets": 4, "reps": "10 each"}, {"name": "Overhead Press", "sets": 3, "reps": "8"}]}, {"name": "Loaded Carry", "sequence": 4, "exercises": [{"name": "Farmers Walk", "sets": 3, "reps": "50 yards"}, {"name": "Suitcase Carry", "sets": 2, "reps": "40 yards each"}]}, {"name": "Core", "sequence": 5, "exercises": [{"name": "Pallof Press", "sets": 3, "reps": "10 each"}, {"name": "Dead Bug", "sets": 3, "reps": "10 each"}]}]}',
ARRAY['functional', 'intermediate', 'strength', 'compound', 'full-body'], 'functional_strength.md'),

('f00c0001-0004-4000-8000-000000000004', 'Kettlebell Functional Flow', 'Kettlebell-based functional training. Ballistic and grind movements combined.', 'strength', 'intermediate', 40,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Halo", "sets": 2, "reps": "8 each direction"}, {"name": "Goblet Squat", "sets": 2, "reps": "8"}, {"name": "Deadlift", "sets": 2, "reps": "8"}]}, {"name": "Ballistic", "sequence": 1, "exercises": [{"name": "Kettlebell Swing", "sets": 5, "reps": "15"}, {"name": "Single Arm Swing", "sets": 3, "reps": "10 each"}]}, {"name": "Grinds", "sequence": 2, "exercises": [{"name": "Goblet Squat", "sets": 4, "reps": "10"}, {"name": "Single Arm Row", "sets": 3, "reps": "10 each"}, {"name": "Single Arm Press", "sets": 3, "reps": "8 each"}]}, {"name": "Combination", "sequence": 3, "exercises": [{"name": "Clean & Press", "sets": 3, "reps": "5 each"}, {"name": "Snatch", "sets": 3, "reps": "5 each"}]}, {"name": "Carries", "sequence": 4, "exercises": [{"name": "Farmers Walk", "sets": 3, "reps": "40 yards"}, {"name": "Rack Walk", "sets": 2, "reps": "40 yards each"}]}, {"name": "Finish", "sequence": 5, "exercises": [{"name": "Turkish Get-Up", "sets": 2, "reps": "3 each"}]}]}',
ARRAY['functional', 'intermediate', 'kettlebell', 'ballistic', 'strength'], 'kettlebell_functional.md'),

-- METABOLIC FUNCTIONAL
('f00c0001-0005-4000-8000-000000000005', 'Functional Metabolic Blast', 'Combine functional movements with metabolic conditioning. Burn and build.', 'cardio', 'intermediate', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jump Rope", "duration": "2 min"}, {"name": "Bodyweight Squats", "sets": 1, "reps": "15"}, {"name": "Push-Ups", "sets": 1, "reps": "10"}]}, {"name": "Complex 1 - 3 Rounds", "sequence": 1, "exercises": [{"name": "Kettlebell Deadlift", "reps": "8"}, {"name": "Bent Over Row", "reps": "8"}, {"name": "Hang Clean", "reps": "8"}, {"name": "Front Squat", "reps": "8"}, {"name": "Push Press", "reps": "8"}, {"name": "Rest", "duration": "90 sec"}]}, {"name": "Conditioning", "sequence": 2, "exercises": [{"name": "Burpees", "sets": 3, "reps": "10"}, {"name": "Box Jumps", "sets": 3, "reps": "10"}, {"name": "Battle Rope Slams", "sets": 3, "reps": "30 sec"}]}, {"name": "Finisher", "sequence": 3, "exercises": [{"name": "Farmers Walk", "duration": "2 min continuous"}, {"name": "Plank Hold", "duration": "1 min"}]}]}',
ARRAY['functional', 'intermediate', 'metabolic', 'conditioning', 'complex'], 'functional_metabolic.md'),

('f00c0001-0006-4000-8000-000000000006', 'Dumbbell Functional Complex', 'One pair of dumbbells, maximum results. Flow through compound movements.', 'full_body', 'intermediate', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "1 min"}, {"name": "Arm Circles", "duration": "1 min"}, {"name": "Bodyweight Squats", "sets": 1, "reps": "10"}]}, {"name": "Complex - 4 Rounds", "sequence": 1, "exercises": [{"name": "Deadlift", "reps": "6"}, {"name": "Hang Clean", "reps": "6"}, {"name": "Front Squat", "reps": "6"}, {"name": "Push Press", "reps": "6"}, {"name": "Bent Over Row", "reps": "6"}, {"name": "Reverse Lunge", "reps": "6 each"}, {"name": "Rest 2 min between rounds", "duration": "2 min"}]}, {"name": "Accessory", "sequence": 2, "exercises": [{"name": "Renegade Row", "sets": 3, "reps": "8 each"}, {"name": "Thrusters", "sets": 3, "reps": "10"}]}, {"name": "Cool Down", "sequence": 3, "exercises": [{"name": "Stretch", "duration": "5 min"}]}]}',
ARRAY['functional', 'intermediate', 'dumbbell', 'complex', 'metabolic'], 'dumbbell_complex.md'),

-- MOVEMENT QUALITY
('f00c0001-0007-4000-8000-000000000007', 'Movement Quality Session', 'Focus on moving well. Corrective exercises and movement refinement.', 'mobility', 'beginner', 35,
'{"blocks": [{"name": "Self Massage", "sequence": 0, "exercises": [{"name": "Foam Roll - Thoracic Spine", "duration": "2 min"}, {"name": "Foam Roll - Lats", "duration": "1 min each"}, {"name": "Foam Roll - Glutes", "duration": "1 min each"}]}, {"name": "Mobility", "sequence": 1, "exercises": [{"name": "90/90 Hip Stretch", "sets": 2, "reps": "1 min each"}, {"name": "World Greatest Stretch", "sets": 2, "reps": "5 each"}, {"name": "Shoulder CARs", "sets": 2, "reps": "5 each direction"}]}, {"name": "Activation", "sequence": 2, "exercises": [{"name": "Glute Bridge", "sets": 3, "reps": "10"}, {"name": "Band Pull Apart", "sets": 3, "reps": "15"}, {"name": "Dead Bug", "sets": 3, "reps": "8 each"}]}, {"name": "Movement Practice", "sequence": 3, "exercises": [{"name": "Goblet Squat - Slow", "sets": 3, "reps": "8"}, {"name": "Push-Up - Perfect Form", "sets": 3, "reps": "5-8"}, {"name": "Hip Hinge Pattern", "sets": 3, "reps": "10"}]}, {"name": "Balance", "sequence": 4, "exercises": [{"name": "Single Leg Stand", "sets": 2, "reps": "30 sec each"}, {"name": "Single Leg Deadlift - Bodyweight", "sets": 2, "reps": "6 each"}]}]}',
ARRAY['functional', 'beginner', 'movement', 'corrective', 'quality'], 'movement_quality.md'),

('f00c0001-0008-4000-8000-000000000008', 'FMS Corrective Session', 'Based on Functional Movement Screen correctives. Address common dysfunctions.', 'mobility', 'beginner', 30,
'{"blocks": [{"name": "Breathing & Core", "sequence": 0, "exercises": [{"name": "Crocodile Breathing", "sets": 2, "reps": "10 breaths"}, {"name": "Dead Bug", "sets": 3, "reps": "8 each"}, {"name": "Bird Dog", "sets": 3, "reps": "8 each"}]}, {"name": "Hip Mobility", "sequence": 1, "exercises": [{"name": "Half Kneeling Hip Flexor Stretch", "sets": 2, "reps": "1 min each"}, {"name": "90/90 Switch", "sets": 2, "reps": "5 each"}, {"name": "Frog Stretch", "duration": "2 min"}]}, {"name": "Thoracic Mobility", "sequence": 2, "exercises": [{"name": "Open Book", "sets": 2, "reps": "8 each"}, {"name": "Quadruped Thoracic Rotation", "sets": 2, "reps": "8 each"}, {"name": "Cat Cow", "sets": 2, "reps": "10"}]}, {"name": "Shoulder Stability", "sequence": 3, "exercises": [{"name": "Wall Slide", "sets": 3, "reps": "10"}, {"name": "Prone Y-T-W", "sets": 2, "reps": "8 each"}, {"name": "Bear Crawl Hold", "sets": 3, "reps": "20 sec"}]}, {"name": "Integration", "sequence": 4, "exercises": [{"name": "Tall Kneeling Halo", "sets": 2, "reps": "5 each"}, {"name": "Turkish Get-Up", "sets": 1, "reps": "2 each"}]}]}',
ARRAY['functional', 'beginner', 'fms', 'corrective', 'mobility'], 'fms_correctives.md'),

-- ATHLETIC FUNCTIONAL
('f00c0001-0009-4000-8000-000000000009', 'Athletic Performance Training', 'Train like an athlete. Power, speed, agility, and strength combined.', 'strength', 'advanced', 50,
'{"blocks": [{"name": "Dynamic Warm Up", "sequence": 0, "exercises": [{"name": "A-Skip", "sets": 2, "reps": "20 yards"}, {"name": "High Knees", "sets": 2, "reps": "20 yards"}, {"name": "Butt Kicks", "sets": 2, "reps": "20 yards"}, {"name": "Carioca", "sets": 2, "reps": "20 yards each"}]}, {"name": "Power Development", "sequence": 1, "exercises": [{"name": "Box Jump", "sets": 4, "reps": "5"}, {"name": "Medicine Ball Slam", "sets": 4, "reps": "6"}, {"name": "Broad Jump", "sets": 4, "reps": "4"}]}, {"name": "Speed & Agility", "sequence": 2, "exercises": [{"name": "Pro Agility (5-10-5)", "sets": 4, "reps": "1"}, {"name": "Lateral Shuffle", "sets": 3, "reps": "20 yards each direction"}, {"name": "Sprint Starts", "sets": 4, "reps": "10 yards"}]}, {"name": "Strength", "sequence": 3, "exercises": [{"name": "Trap Bar Deadlift", "sets": 4, "reps": "5"}, {"name": "Single Leg Squat", "sets": 3, "reps": "6 each"}, {"name": "Push-Up with Clap", "sets": 3, "reps": "8"}]}, {"name": "Core", "sequence": 4, "exercises": [{"name": "Anti-Rotation Press", "sets": 3, "reps": "10 each"}, {"name": "Medicine Ball Rotational Throw", "sets": 3, "reps": "8 each"}]}]}',
ARRAY['functional', 'advanced', 'athletic', 'power', 'speed'], 'athletic_performance.md'),

('f00c0001-0010-4000-8000-000000000010', 'Rotational Power Training', 'Develop rotational strength and power for sports like golf, tennis, and baseball.', 'strength', 'intermediate', 40,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Thoracic Rotation", "sets": 2, "reps": "10 each"}, {"name": "Hip CARs", "sets": 2, "reps": "5 each"}, {"name": "Medicine Ball Hold Rotation", "sets": 2, "reps": "10 each"}]}, {"name": "Anti-Rotation", "sequence": 1, "exercises": [{"name": "Pallof Press", "sets": 3, "reps": "10 each"}, {"name": "Pallof Rotation", "sets": 3, "reps": "8 each"}, {"name": "Single Arm Farmers Walk", "sets": 3, "reps": "40 yards each"}]}, {"name": "Rotational Power", "sequence": 2, "exercises": [{"name": "Medicine Ball Rotational Throw", "sets": 4, "reps": "8 each"}, {"name": "Cable Woodchop", "sets": 3, "reps": "10 each"}, {"name": "Landmine Rotation", "sets": 3, "reps": "10 each"}]}, {"name": "Integration", "sequence": 3, "exercises": [{"name": "Single Leg Deadlift to Row", "sets": 3, "reps": "8 each"}, {"name": "Lunge with Rotation", "sets": 3, "reps": "8 each"}]}, {"name": "Core Stability", "sequence": 4, "exercises": [{"name": "Dead Bug with Rotation", "sets": 3, "reps": "8 each"}, {"name": "Side Plank with Rotation", "sets": 2, "reps": "8 each"}]}]}',
ARRAY['functional', 'intermediate', 'rotation', 'power', 'sports'], 'rotational_power.md'),

-- BODYWEIGHT FUNCTIONAL
('f00c0001-0011-4000-8000-000000000011', 'Bodyweight Functional Circuit', 'No equipment needed. Full body functional training with just your bodyweight.', 'full_body', 'intermediate', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "1 min"}, {"name": "Arm Circles", "duration": "1 min"}, {"name": "Leg Swings", "sets": 2, "reps": "10 each"}]}, {"name": "Circuit - 3 Rounds", "sequence": 1, "exercises": [{"name": "Bodyweight Squat", "reps": "15"}, {"name": "Push-Up", "reps": "12"}, {"name": "Reverse Lunge", "reps": "10 each"}, {"name": "Inverted Row or Superman", "reps": "12"}, {"name": "Glute Bridge", "reps": "15"}, {"name": "Plank Hold", "duration": "30 sec"}, {"name": "Rest 90 sec between rounds", "duration": "90 sec"}]}, {"name": "Finisher", "sequence": 2, "exercises": [{"name": "Burpees", "sets": 2, "reps": "10"}, {"name": "Mountain Climbers", "sets": 2, "reps": "20 total"}]}, {"name": "Cool Down", "sequence": 3, "exercises": [{"name": "Stretch", "duration": "5 min"}]}]}',
ARRAY['functional', 'intermediate', 'bodyweight', 'no-equipment', 'circuit'], 'bodyweight_functional.md'),

('f00c0001-0012-4000-8000-000000000012', 'Primal Movement Flow', 'Animal movement inspired training. Crawl, roll, and explore natural movement.', 'full_body', 'intermediate', 40,
'{"blocks": [{"name": "Awakening", "sequence": 0, "exercises": [{"name": "Rolling Pattern", "sets": 2, "reps": "5 each direction"}, {"name": "Breathing Crocodile", "duration": "2 min"}]}, {"name": "Crawling", "sequence": 1, "exercises": [{"name": "Baby Crawl", "duration": "30 sec"}, {"name": "Bear Crawl Forward", "sets": 2, "reps": "20 yards"}, {"name": "Bear Crawl Backward", "sets": 2, "reps": "20 yards"}, {"name": "Crab Walk", "sets": 2, "reps": "20 yards"}, {"name": "Leopard Crawl", "sets": 2, "reps": "15 yards"}]}, {"name": "Ground to Standing", "sequence": 2, "exercises": [{"name": "Turkish Get-Up (Bodyweight)", "sets": 3, "reps": "3 each"}, {"name": "Kneeling to Stand", "sets": 2, "reps": "5 each leg"}]}, {"name": "Animal Movements", "sequence": 3, "exercises": [{"name": "Frog Jump", "sets": 3, "reps": "10"}, {"name": "Inch Worm", "sets": 3, "reps": "5"}, {"name": "Duck Walk", "sets": 2, "reps": "20 yards"}, {"name": "Gorilla Walk", "sets": 2, "reps": "15 yards"}]}, {"name": "Flow", "sequence": 4, "exercises": [{"name": "Movement Flow - Combine All", "duration": "5 min", "notes": "Link movements together creatively"}]}]}',
ARRAY['functional', 'intermediate', 'primal', 'animal', 'movement'], 'primal_movement.md'),

-- SPORT-SPECIFIC FUNCTIONAL
('f00c0001-0013-4000-8000-000000000013', 'Functional Training for Runners', 'Strength and stability for better running performance and injury prevention.', 'strength', 'intermediate', 35,
'{"blocks": [{"name": "Activation", "sequence": 0, "exercises": [{"name": "Glute Bridge", "sets": 3, "reps": "12"}, {"name": "Clamshell", "sets": 2, "reps": "12 each"}, {"name": "Monster Walk", "sets": 2, "reps": "15 yards each direction"}]}, {"name": "Single Leg Strength", "sequence": 1, "exercises": [{"name": "Single Leg Squat to Box", "sets": 3, "reps": "8 each"}, {"name": "Single Leg Deadlift", "sets": 3, "reps": "8 each"}, {"name": "Single Leg Hip Thrust", "sets": 3, "reps": "10 each"}]}, {"name": "Core Stability", "sequence": 2, "exercises": [{"name": "Dead Bug", "sets": 3, "reps": "10 each"}, {"name": "Side Plank with Leg Lift", "sets": 2, "reps": "30 sec each"}, {"name": "Pallof Press", "sets": 3, "reps": "10 each"}]}, {"name": "Power", "sequence": 3, "exercises": [{"name": "Box Jump", "sets": 3, "reps": "6"}, {"name": "Single Leg Hop", "sets": 3, "reps": "6 each"}]}, {"name": "Mobility", "sequence": 4, "exercises": [{"name": "Hip Flexor Stretch", "sets": 2, "reps": "1 min each"}, {"name": "Ankle Mobility", "sets": 2, "reps": "10 each"}]}]}',
ARRAY['functional', 'intermediate', 'running', 'single-leg', 'injury-prevention'], 'functional_for_runners.md'),

('f00c0001-0014-4000-8000-000000000014', 'Functional Training for Cyclists', 'Address cyclist imbalances. Strengthen posterior chain and improve hip mobility.', 'strength', 'intermediate', 35,
'{"blocks": [{"name": "Release", "sequence": 0, "exercises": [{"name": "Foam Roll - IT Band", "duration": "1 min each"}, {"name": "Foam Roll - Quads", "duration": "1 min each"}, {"name": "Hip Flexor Stretch", "sets": 2, "reps": "1 min each"}]}, {"name": "Activation", "sequence": 1, "exercises": [{"name": "Glute Bridge", "sets": 3, "reps": "12"}, {"name": "Bird Dog", "sets": 3, "reps": "8 each"}, {"name": "Band Pull Apart", "sets": 3, "reps": "15"}]}, {"name": "Hip Hinge", "sequence": 2, "exercises": [{"name": "Romanian Deadlift", "sets": 4, "reps": "8"}, {"name": "Single Leg Deadlift", "sets": 3, "reps": "8 each"}]}, {"name": "Core", "sequence": 3, "exercises": [{"name": "Dead Bug", "sets": 3, "reps": "10 each"}, {"name": "Pallof Press", "sets": 3, "reps": "10 each"}, {"name": "Plank", "sets": 3, "reps": "30 sec"}]}, {"name": "Upper Back", "sequence": 4, "exercises": [{"name": "Face Pull", "sets": 3, "reps": "15"}, {"name": "Prone Y-T-W", "sets": 2, "reps": "10 each"}]}, {"name": "Stretch", "sequence": 5, "exercises": [{"name": "Pigeon Pose", "sets": 1, "reps": "1 min each"}, {"name": "Chest Stretch", "sets": 1, "reps": "1 min"}]}]}',
ARRAY['functional', 'intermediate', 'cycling', 'posterior-chain', 'hip'], 'functional_for_cyclists.md'),

-- LOADED CARRY FOCUS
('f00c0001-0015-4000-8000-000000000015', 'Loaded Carry Workout', 'Master the art of carrying. Farmers walks, suitcase carries, and more.', 'strength', 'intermediate', 40,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Bodyweight Squats", "sets": 2, "reps": "10"}, {"name": "Push-Ups", "sets": 2, "reps": "10"}, {"name": "Dead Bug", "sets": 2, "reps": "8 each"}]}, {"name": "Bilateral Carries", "sequence": 1, "exercises": [{"name": "Farmers Walk", "sets": 4, "reps": "50 yards"}, {"name": "Overhead Carry", "sets": 3, "reps": "40 yards"}]}, {"name": "Unilateral Carries", "sequence": 2, "exercises": [{"name": "Suitcase Carry", "sets": 3, "reps": "40 yards each"}, {"name": "Rack Walk", "sets": 3, "reps": "40 yards each"}, {"name": "Waiter Walk", "sets": 2, "reps": "30 yards each"}]}, {"name": "Mixed Carries", "sequence": 3, "exercises": [{"name": "Cross Body Carry", "sets": 2, "reps": "40 yards each config"}, {"name": "Offset Farmers Walk", "sets": 2, "reps": "40 yards each"}]}, {"name": "Finish", "sequence": 4, "exercises": [{"name": "Bear Hug Carry", "sets": 2, "reps": "40 yards"}, {"name": "Sandbag Carry", "sets": 2, "reps": "50 yards"}]}]}',
ARRAY['functional', 'intermediate', 'carry', 'grip', 'core'], 'loaded_carry.md'),

-- SENIOR/BEGINNER FUNCTIONAL
('f00c0001-0016-4000-8000-000000000016', 'Functional Fitness for Seniors', 'Safe, effective functional training for older adults. Maintain independence.', 'full_body', 'beginner', 30,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "March in Place", "duration": "2 min"}, {"name": "Arm Circles", "sets": 2, "reps": "10 each direction"}, {"name": "Ankle Circles", "sets": 2, "reps": "10 each"}]}, {"name": "Lower Body", "sequence": 1, "exercises": [{"name": "Sit to Stand from Chair", "sets": 3, "reps": "10"}, {"name": "Wall Sit", "sets": 2, "reps": "20 sec"}, {"name": "Step Up (low step)", "sets": 2, "reps": "8 each"}]}, {"name": "Upper Body", "sequence": 2, "exercises": [{"name": "Wall Push-Up", "sets": 3, "reps": "10"}, {"name": "Seated Row with Band", "sets": 3, "reps": "12"}, {"name": "Overhead Press - Light", "sets": 2, "reps": "10"}]}, {"name": "Balance", "sequence": 3, "exercises": [{"name": "Single Leg Stand - Wall Assist", "sets": 2, "reps": "20 sec each"}, {"name": "Heel to Toe Walk", "sets": 2, "reps": "20 yards"}, {"name": "Tandem Stance", "sets": 2, "reps": "20 sec each"}]}, {"name": "Stretch", "sequence": 4, "exercises": [{"name": "Calf Stretch", "sets": 1, "reps": "30 sec each"}, {"name": "Hamstring Stretch", "sets": 1, "reps": "30 sec each"}, {"name": "Chest Stretch", "sets": 1, "reps": "30 sec"}]}]}',
ARRAY['functional', 'beginner', 'seniors', 'balance', 'safe'], 'functional_seniors.md'),

('f00c0001-0017-4000-8000-000000000017', 'Functional Balance Training', 'Improve balance and stability through progressive functional exercises.', 'mobility', 'beginner', 30,
'{"blocks": [{"name": "Base Building", "sequence": 0, "exercises": [{"name": "Tandem Stance", "sets": 2, "reps": "30 sec each"}, {"name": "Single Leg Stand", "sets": 2, "reps": "30 sec each"}, {"name": "Weight Shift", "sets": 2, "reps": "10 each direction"}]}, {"name": "Dynamic Balance", "sequence": 1, "exercises": [{"name": "Heel to Toe Walk", "sets": 3, "reps": "20 yards"}, {"name": "Walking Lunge", "sets": 2, "reps": "10 each"}, {"name": "Lateral Step Over", "sets": 2, "reps": "10 each"}]}, {"name": "Reactive Balance", "sequence": 2, "exercises": [{"name": "Catch and Throw - Single Leg", "sets": 2, "reps": "10 each"}, {"name": "Step Touch Drill", "duration": "1 min"}]}, {"name": "Vestibular", "sequence": 3, "exercises": [{"name": "Head Turns with Walking", "sets": 2, "reps": "20 yards"}, {"name": "Gaze Stabilization", "sets": 2, "reps": "30 sec each"}]}, {"name": "Integration", "sequence": 4, "exercises": [{"name": "Single Leg Deadlift - Bodyweight", "sets": 2, "reps": "6 each"}, {"name": "Clock Reach", "sets": 2, "reps": "4 each leg"}]}]}',
ARRAY['functional', 'beginner', 'balance', 'stability', 'fall-prevention'], 'functional_balance.md'),

-- ADVANCED FUNCTIONAL
('f00c0001-0018-4000-8000-000000000018', 'Advanced Functional Training', 'High-level functional movements for experienced athletes.', 'strength', 'advanced', 55,
'{"blocks": [{"name": "Activation", "sequence": 0, "exercises": [{"name": "Band Pull Apart", "sets": 2, "reps": "15"}, {"name": "Glute Bridge March", "sets": 2, "reps": "10 each"}, {"name": "Dead Bug", "sets": 2, "reps": "8 each"}]}, {"name": "Power", "sequence": 1, "exercises": [{"name": "Power Clean", "sets": 5, "reps": "3"}, {"name": "Box Jump", "sets": 4, "reps": "5"}, {"name": "Medicine Ball Slam", "sets": 4, "reps": "8"}]}, {"name": "Strength Complex", "sequence": 2, "exercises": [{"name": "Front Squat", "sets": 4, "reps": "5"}, {"name": "Strict Press", "sets": 4, "reps": "5"}, {"name": "Weighted Pull-Up", "sets": 4, "reps": "5"}]}, {"name": "Unilateral", "sequence": 3, "exercises": [{"name": "Bulgarian Split Squat", "sets": 3, "reps": "8 each"}, {"name": "Single Arm Row", "sets": 3, "reps": "8 each"}, {"name": "Single Leg Romanian Deadlift", "sets": 3, "reps": "8 each"}]}, {"name": "Carries", "sequence": 4, "exercises": [{"name": "Heavy Farmers Walk", "sets": 3, "reps": "40 yards"}, {"name": "Yoke Walk", "sets": 2, "reps": "40 yards"}]}, {"name": "Core", "sequence": 5, "exercises": [{"name": "Ab Wheel Rollout", "sets": 3, "reps": "10"}, {"name": "L-Sit Hold", "sets": 3, "reps": "15 sec"}]}]}',
ARRAY['functional', 'advanced', 'strength', 'power', 'olympic'], 'advanced_functional.md'),

('f00c0001-0019-4000-8000-000000000019', 'Sandbag Functional Workout', 'Use an unconventional tool for real-world strength. Sandbag training.', 'strength', 'intermediate', 40,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Sandbag Deadlift - Light", "sets": 2, "reps": "8"}, {"name": "Sandbag Rotation", "sets": 2, "reps": "10 each"}]}, {"name": "Lift & Carry", "sequence": 1, "exercises": [{"name": "Sandbag Clean", "sets": 4, "reps": "6"}, {"name": "Sandbag Bear Hug Carry", "sets": 4, "reps": "40 yards"}, {"name": "Sandbag Ground to Shoulder", "sets": 3, "reps": "5 each"}]}, {"name": "Strength", "sequence": 2, "exercises": [{"name": "Sandbag Front Squat", "sets": 4, "reps": "8"}, {"name": "Sandbag Bent Over Row", "sets": 4, "reps": "10"}, {"name": "Sandbag Lunges", "sets": 3, "reps": "8 each"}]}, {"name": "Conditioning", "sequence": 3, "exercises": [{"name": "Sandbag Shouldering", "sets": 3, "reps": "10 total"}, {"name": "Sandbag Over Shoulder Throws", "sets": 3, "reps": "10"}]}, {"name": "Finisher", "sequence": 4, "exercises": [{"name": "Sandbag Get-Up", "sets": 2, "reps": "3 each"}]}]}',
ARRAY['functional', 'intermediate', 'sandbag', 'unconventional', 'strength'], 'sandbag_functional.md'),

-- SUSPENSION/RINGS
('f00c0001-0020-4000-8000-000000000020', 'Suspension Trainer Functional', 'Full body workout using TRX or suspension trainer. Leverage and instability.', 'full_body', 'intermediate', 40,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "TRX Squat", "sets": 2, "reps": "10"}, {"name": "TRX Row - Light", "sets": 2, "reps": "10"}]}, {"name": "Lower Body", "sequence": 1, "exercises": [{"name": "TRX Pistol Squat Assist", "sets": 3, "reps": "6 each"}, {"name": "TRX Lunge", "sets": 3, "reps": "8 each"}, {"name": "TRX Hamstring Curl", "sets": 3, "reps": "10"}]}, {"name": "Push", "sequence": 2, "exercises": [{"name": "TRX Push-Up", "sets": 3, "reps": "12"}, {"name": "TRX Chest Press", "sets": 3, "reps": "10"}, {"name": "TRX Tricep Press", "sets": 3, "reps": "12"}]}, {"name": "Pull", "sequence": 3, "exercises": [{"name": "TRX Row", "sets": 4, "reps": "12"}, {"name": "TRX Y-Fly", "sets": 3, "reps": "10"}, {"name": "TRX Bicep Curl", "sets": 3, "reps": "12"}]}, {"name": "Core", "sequence": 4, "exercises": [{"name": "TRX Plank", "sets": 3, "reps": "30 sec"}, {"name": "TRX Pike", "sets": 3, "reps": "10"}, {"name": "TRX Body Saw", "sets": 3, "reps": "10"}]}]}',
ARRAY['functional', 'intermediate', 'trx', 'suspension', 'full-body'], 'suspension_functional.md'),

-- MIXED MODALITY
('f00c0001-0021-4000-8000-000000000021', 'Hybrid Strength & Conditioning', 'Combine strength training with cardio conditioning. Best of both worlds.', 'full_body', 'intermediate', 50,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Row or Bike", "duration": "3 min"}, {"name": "Dynamic Stretches", "duration": "3 min"}]}, {"name": "Strength Block 1", "sequence": 1, "exercises": [{"name": "Back Squat", "sets": 4, "reps": "6"}, {"name": "Bench Press", "sets": 4, "reps": "6"}]}, {"name": "Conditioning 1", "sequence": 2, "exercises": [{"name": "Row 500m", "notes": "Fast pace"}, {"name": "Rest", "duration": "1 min"}]}, {"name": "Strength Block 2", "sequence": 3, "exercises": [{"name": "Romanian Deadlift", "sets": 4, "reps": "8"}, {"name": "Pull-Ups", "sets": 4, "reps": "8"}]}, {"name": "Conditioning 2", "sequence": 4, "exercises": [{"name": "Burpees", "sets": 3, "reps": "10"}, {"name": "Box Jumps", "sets": 3, "reps": "10"}]}, {"name": "Finisher", "sequence": 5, "exercises": [{"name": "Farmers Walk", "sets": 2, "reps": "50 yards"}, {"name": "Plank Hold", "duration": "1 min"}]}]}',
ARRAY['functional', 'intermediate', 'hybrid', 'strength', 'conditioning'], 'hybrid_training.md'),

('f00c0001-0022-4000-8000-000000000022', 'Work Capacity Builder', 'Increase your engine. Build the ability to do more work in less time.', 'cardio', 'advanced', 45,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Row or Bike", "duration": "3 min"}, {"name": "Kettlebell Swings", "sets": 2, "reps": "10"}]}, {"name": "EMOM 20", "sequence": 1, "exercises": [{"name": "Minute 1: Cal Row", "reps": "15 cals"}, {"name": "Minute 2: Kettlebell Swings", "reps": "15"}, {"name": "Minute 3: Burpees", "reps": "8"}, {"name": "Minute 4: Box Jumps", "reps": "10"}, {"name": "Repeat 5 Rounds", "notes": "20 min total"}]}, {"name": "Strength", "sequence": 2, "exercises": [{"name": "Deadlift", "sets": 3, "reps": "5"}, {"name": "Push Press", "sets": 3, "reps": "5"}]}, {"name": "Finisher", "sequence": 3, "exercises": [{"name": "400m Run", "notes": "Fast"}, {"name": "50 Air Squats", "notes": "Unbroken if possible"}, {"name": "Record Time", "notes": "For time"}]}]}',
ARRAY['functional', 'advanced', 'capacity', 'conditioning', 'engine'], 'work_capacity.md'),

-- SPECIALTY
('f00c0001-0023-4000-8000-000000000023', 'Grip Strength Functional', 'Develop crushing grip and forearm strength through functional movements.', 'strength', 'intermediate', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Wrist Circles", "sets": 2, "reps": "10 each"}, {"name": "Finger Extensions", "sets": 2, "reps": "10"}, {"name": "Dead Hang", "duration": "30 sec"}]}, {"name": "Crush Grip", "sequence": 1, "exercises": [{"name": "Farmers Walk - Heavy", "sets": 4, "reps": "40 yards"}, {"name": "Plate Pinch Hold", "sets": 3, "reps": "30 sec"}]}, {"name": "Support Grip", "sequence": 2, "exercises": [{"name": "Dead Hang", "sets": 3, "reps": "max time"}, {"name": "Towel Pull-Ups", "sets": 3, "reps": "5-8"}]}, {"name": "Wrist Strength", "sequence": 3, "exercises": [{"name": "Wrist Curl", "sets": 3, "reps": "12"}, {"name": "Reverse Wrist Curl", "sets": 3, "reps": "12"}, {"name": "Pronation/Supination", "sets": 2, "reps": "10 each"}]}, {"name": "Finger Strength", "sequence": 4, "exercises": [{"name": "Fat Grip Deadlift", "sets": 3, "reps": "6"}, {"name": "Finger Curls", "sets": 2, "reps": "15"}]}]}',
ARRAY['functional', 'intermediate', 'grip', 'forearm', 'strength'], 'grip_strength.md'),

('f00c0001-0024-4000-8000-000000000024', 'Hip-Focused Functional', 'Address hip mobility and strength. Essential for functional movement.', 'mobility', 'intermediate', 35,
'{"blocks": [{"name": "Release", "sequence": 0, "exercises": [{"name": "Foam Roll - Hip Flexors", "duration": "1 min each"}, {"name": "Foam Roll - Glutes", "duration": "1 min each"}, {"name": "Foam Roll - IT Band", "duration": "1 min each"}]}, {"name": "Mobility", "sequence": 1, "exercises": [{"name": "90/90 Stretch", "sets": 2, "reps": "1 min each"}, {"name": "Pigeon Pose", "sets": 2, "reps": "1 min each"}, {"name": "Hip CARs", "sets": 2, "reps": "5 each"}]}, {"name": "Activation", "sequence": 2, "exercises": [{"name": "Glute Bridge", "sets": 3, "reps": "15"}, {"name": "Clamshell", "sets": 3, "reps": "12 each"}, {"name": "Fire Hydrant", "sets": 3, "reps": "10 each"}]}, {"name": "Strength", "sequence": 3, "exercises": [{"name": "Hip Thrust", "sets": 4, "reps": "12"}, {"name": "Bulgarian Split Squat", "sets": 3, "reps": "8 each"}, {"name": "Single Leg Deadlift", "sets": 3, "reps": "8 each"}]}, {"name": "Integration", "sequence": 4, "exercises": [{"name": "Walking Lunge", "sets": 2, "reps": "10 each"}, {"name": "Lateral Lunge", "sets": 2, "reps": "8 each"}]}]}',
ARRAY['functional', 'intermediate', 'hip', 'mobility', 'glute'], 'hip_focused_functional.md'),

('f00c0001-0025-4000-8000-000000000025', 'Tactical Fitness Training', 'Training for first responders, military, and tactical athletes.', 'full_body', 'advanced', 50,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Run", "duration": "3 min"}, {"name": "Dynamic Stretches", "duration": "3 min"}]}, {"name": "Strength", "sequence": 1, "exercises": [{"name": "Deadlift", "sets": 4, "reps": "5"}, {"name": "Weighted Pull-Up", "sets": 4, "reps": "6"}, {"name": "Push Press", "sets": 4, "reps": "6"}]}, {"name": "Load Bearing", "sequence": 2, "exercises": [{"name": "Ruck Walk", "duration": "10 min", "notes": "30-50 lb pack"}, {"name": "Sandbag Carry", "sets": 3, "reps": "50 yards"}]}, {"name": "Combat Conditioning", "sequence": 3, "exercises": [{"name": "Burpees", "sets": 3, "reps": "10"}, {"name": "Box Jumps", "sets": 3, "reps": "10"}, {"name": "Medicine Ball Slam", "sets": 3, "reps": "10"}]}, {"name": "Endurance", "sequence": 4, "exercises": [{"name": "400m Run", "reps": "4", "notes": "90 sec rest between"}, {"name": "Core Holds", "duration": "2 min total"}]}, {"name": "Recovery", "sequence": 5, "exercises": [{"name": "Light Jog", "duration": "3 min"}, {"name": "Stretch", "duration": "5 min"}]}]}',
ARRAY['functional', 'advanced', 'tactical', 'military', 'first-responder'], 'tactical_fitness.md');
