-- Seed TRX (Suspension Training) workout templates
-- TRX-only workouts using suspension trainer

INSERT INTO system_workout_templates (id, name, description, category, difficulty, duration_minutes, exercises, tags, source_file) VALUES

-- FOUNDATIONAL TRX
('aaa00001-0001-4000-8000-000000000001', 'TRX Fundamentals', 'Learn the basics of suspension training. Master the foundational movements.', 'full_body', 'beginner', 35,
'{"blocks": [{"name": "Setup & Basics", "sequence": 0, "exercises": [{"name": "TRX Strap Length Adjustment", "notes": "Learn mid-length, long, and short positions"}, {"name": "Body Positioning Practice", "notes": "Angle = Intensity"}]}, {"name": "Lower Body Basics", "sequence": 1, "exercises": [{"name": "TRX Assisted Squat", "sets": 3, "reps": "12"}, {"name": "TRX Balance Lunge", "sets": 2, "reps": "10 each"}, {"name": "TRX Single Leg Squat Assist", "sets": 2, "reps": "8 each"}]}, {"name": "Upper Body Push", "sequence": 2, "exercises": [{"name": "TRX Chest Press", "sets": 3, "reps": "12"}, {"name": "TRX Push-Up", "sets": 3, "reps": "10"}]}, {"name": "Upper Body Pull", "sequence": 3, "exercises": [{"name": "TRX Row", "sets": 3, "reps": "12"}, {"name": "TRX Y-Fly", "sets": 2, "reps": "10"}]}, {"name": "Core", "sequence": 4, "exercises": [{"name": "TRX Plank", "sets": 3, "reps": "30 sec"}, {"name": "TRX Mountain Climber (slow)", "sets": 2, "reps": "10 each"}]}, {"name": "Stretch", "sequence": 5, "exercises": [{"name": "TRX Hip Flexor Stretch", "duration": "1 min each"}, {"name": "TRX Chest Stretch", "duration": "1 min"}]}]}',
ARRAY['trx', 'beginner', 'fundamentals', 'suspension', 'intro'], 'trx_fundamentals.md'),

('aaa00001-0002-4000-8000-000000000002', 'TRX Full Body Basics', 'Complete full body workout using only TRX. Perfect for beginners.', 'full_body', 'beginner', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "TRX Squat", "sets": 2, "reps": "10"}, {"name": "TRX Arm Circles", "sets": 2, "reps": "8 each direction"}]}, {"name": "Legs", "sequence": 1, "exercises": [{"name": "TRX Squat", "sets": 3, "reps": "15"}, {"name": "TRX Lunge", "sets": 3, "reps": "10 each"}, {"name": "TRX Hamstring Curl", "sets": 3, "reps": "12"}]}, {"name": "Push", "sequence": 2, "exercises": [{"name": "TRX Chest Press", "sets": 3, "reps": "12"}, {"name": "TRX Tricep Press", "sets": 3, "reps": "12"}]}, {"name": "Pull", "sequence": 3, "exercises": [{"name": "TRX Row", "sets": 3, "reps": "12"}, {"name": "TRX Bicep Curl", "sets": 3, "reps": "12"}]}, {"name": "Core", "sequence": 4, "exercises": [{"name": "TRX Plank", "sets": 3, "reps": "30 sec"}, {"name": "TRX Crunch", "sets": 2, "reps": "12"}]}, {"name": "Stretch", "sequence": 5, "exercises": [{"name": "TRX Stretching Series", "duration": "5 min"}]}]}',
ARRAY['trx', 'beginner', 'full-body', 'suspension', 'complete'], 'trx_full_body_basics.md'),

-- STRENGTH TRX
('aaa00001-0003-4000-8000-000000000003', 'TRX Strength Builder', 'Progressive overload using body angles. Build real strength on the straps.', 'strength', 'intermediate', 45,
'{"blocks": [{"name": "Activation", "sequence": 0, "exercises": [{"name": "TRX Row - Light", "sets": 2, "reps": "10"}, {"name": "TRX Squat", "sets": 2, "reps": "10"}]}, {"name": "Push Strength", "sequence": 1, "exercises": [{"name": "TRX Chest Press - Steep Angle", "sets": 4, "reps": "10"}, {"name": "TRX Atomic Push-Up", "sets": 3, "reps": "8"}, {"name": "TRX Tricep Press - Close", "sets": 3, "reps": "12"}, {"name": "TRX Push-Up - Feet in Straps", "sets": 3, "reps": "10"}]}, {"name": "Pull Strength", "sequence": 2, "exercises": [{"name": "TRX Row - Steep Angle", "sets": 4, "reps": "10"}, {"name": "TRX Power Pull", "sets": 3, "reps": "8 each"}, {"name": "TRX W-Pull", "sets": 3, "reps": "12"}, {"name": "TRX Bicep Curl - Single Arm", "sets": 3, "reps": "10 each"}]}, {"name": "Legs", "sequence": 3, "exercises": [{"name": "TRX Pistol Squat", "sets": 3, "reps": "6 each"}, {"name": "TRX Hamstring Curl", "sets": 3, "reps": "12"}, {"name": "TRX Lunge - Rear Foot Elevated", "sets": 3, "reps": "10 each"}]}, {"name": "Core", "sequence": 4, "exercises": [{"name": "TRX Pike", "sets": 3, "reps": "10"}, {"name": "TRX Side Plank", "sets": 3, "reps": "30 sec each"}]}]}',
ARRAY['trx', 'intermediate', 'strength', 'progressive', 'advanced-moves'], 'trx_strength_builder.md'),

('aaa00001-0004-4000-8000-000000000004', 'TRX Upper Body Focus', 'Dedicated upper body session using only TRX suspension trainer.', 'upper', 'intermediate', 40,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "TRX Row - Light", "sets": 2, "reps": "10"}, {"name": "TRX T-Fly", "sets": 2, "reps": "8"}]}, {"name": "Chest", "sequence": 1, "exercises": [{"name": "TRX Chest Press", "sets": 4, "reps": "12"}, {"name": "TRX Push-Up", "sets": 3, "reps": "12"}, {"name": "TRX Chest Fly", "sets": 3, "reps": "10"}]}, {"name": "Back", "sequence": 2, "exercises": [{"name": "TRX Row", "sets": 4, "reps": "12"}, {"name": "TRX Y-Fly", "sets": 3, "reps": "10"}, {"name": "TRX T-Fly", "sets": 3, "reps": "10"}, {"name": "TRX W-Pull", "sets": 3, "reps": "12"}]}, {"name": "Shoulders", "sequence": 3, "exercises": [{"name": "TRX Deltoid Raise", "sets": 3, "reps": "10"}, {"name": "TRX I-Fly", "sets": 3, "reps": "10"}, {"name": "TRX Overhead Press", "sets": 3, "reps": "10"}]}, {"name": "Arms", "sequence": 4, "exercises": [{"name": "TRX Bicep Curl", "sets": 3, "reps": "12"}, {"name": "TRX Tricep Press", "sets": 3, "reps": "12"}]}, {"name": "Cool Down", "sequence": 5, "exercises": [{"name": "TRX Chest Stretch", "duration": "1 min"}, {"name": "TRX Lat Stretch", "duration": "1 min each"}]}]}',
ARRAY['trx', 'intermediate', 'upper-body', 'chest', 'back'], 'trx_upper_body.md'),

('aaa00001-0005-4000-8000-000000000005', 'TRX Lower Body Focus', 'Leg day on the straps. Squats, lunges, and single-leg work.', 'lower', 'intermediate', 40,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "TRX Squat", "sets": 2, "reps": "10"}, {"name": "TRX Hip Hinge", "sets": 2, "reps": "10"}]}, {"name": "Bilateral Legs", "sequence": 1, "exercises": [{"name": "TRX Squat - Deep", "sets": 4, "reps": "15"}, {"name": "TRX Jump Squat", "sets": 3, "reps": "12"}, {"name": "TRX Hamstring Curl", "sets": 4, "reps": "12"}]}, {"name": "Unilateral Legs", "sequence": 2, "exercises": [{"name": "TRX Lunge", "sets": 3, "reps": "12 each"}, {"name": "TRX Pistol Squat Assist", "sets": 3, "reps": "8 each"}, {"name": "TRX Single Leg Squat", "sets": 3, "reps": "8 each"}, {"name": "TRX Crossing Balance Lunge", "sets": 3, "reps": "10 each"}]}, {"name": "Glutes", "sequence": 3, "exercises": [{"name": "TRX Hip Press", "sets": 3, "reps": "15"}, {"name": "TRX Single Leg Hip Press", "sets": 3, "reps": "10 each"}]}, {"name": "Stretch", "sequence": 4, "exercises": [{"name": "TRX Hip Flexor Stretch", "duration": "1 min each"}, {"name": "TRX Hamstring Stretch", "duration": "1 min each"}]}]}',
ARRAY['trx', 'intermediate', 'lower-body', 'legs', 'glutes'], 'trx_lower_body.md'),

-- CORE TRX
('aaa00001-0006-4000-8000-000000000006', 'TRX Core Destroyer', 'Intensive core training using TRX suspension. Unstable = Intense.', 'full_body', 'intermediate', 30,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "TRX Plank", "sets": 2, "reps": "20 sec"}, {"name": "TRX Mountain Climber - Slow", "sets": 2, "reps": "8 each"}]}, {"name": "Front Core", "sequence": 1, "exercises": [{"name": "TRX Plank", "sets": 3, "reps": "45 sec"}, {"name": "TRX Crunch", "sets": 3, "reps": "15"}, {"name": "TRX Pike", "sets": 3, "reps": "10"}, {"name": "TRX Body Saw", "sets": 3, "reps": "10"}]}, {"name": "Rotational Core", "sequence": 2, "exercises": [{"name": "TRX Oblique Crunch", "sets": 3, "reps": "12 each"}, {"name": "TRX Side Plank", "sets": 3, "reps": "30 sec each"}, {"name": "TRX Pendulum", "sets": 3, "reps": "10 each"}]}, {"name": "Dynamic Core", "sequence": 3, "exercises": [{"name": "TRX Mountain Climber", "sets": 3, "reps": "20 total"}, {"name": "TRX Atomic Push-Up", "sets": 3, "reps": "10"}, {"name": "TRX Knee Tuck", "sets": 3, "reps": "12"}]}, {"name": "Finish", "sequence": 4, "exercises": [{"name": "TRX Plank Hold", "duration": "1 min max effort"}]}]}',
ARRAY['trx', 'intermediate', 'core', 'abs', 'stability'], 'trx_core_destroyer.md'),

('aaa00001-0007-4000-8000-000000000007', 'TRX Plank Variations', 'Master the TRX plank in all its variations. Core stability focus.', 'full_body', 'intermediate', 25,
'{"blocks": [{"name": "Basic Planks", "sequence": 0, "exercises": [{"name": "TRX Plank - Standard", "sets": 3, "reps": "30 sec"}, {"name": "TRX Plank - Wide Feet", "sets": 2, "reps": "30 sec"}, {"name": "TRX Plank - Narrow Feet", "sets": 2, "reps": "30 sec"}]}, {"name": "Side Planks", "sequence": 1, "exercises": [{"name": "TRX Side Plank - Right", "sets": 3, "reps": "30 sec"}, {"name": "TRX Side Plank - Left", "sets": 3, "reps": "30 sec"}, {"name": "TRX Side Plank with Hip Dip", "sets": 2, "reps": "10 each"}]}, {"name": "Dynamic Planks", "sequence": 2, "exercises": [{"name": "TRX Plank to Pike", "sets": 3, "reps": "8"}, {"name": "TRX Plank Knee to Elbow", "sets": 2, "reps": "10 each"}, {"name": "TRX Body Saw", "sets": 3, "reps": "10"}, {"name": "TRX Pendulum", "sets": 3, "reps": "8 each"}]}, {"name": "Challenge", "sequence": 3, "exercises": [{"name": "TRX Plank - Single Arm", "sets": 2, "reps": "15 sec each"}, {"name": "TRX Reverse Plank", "sets": 2, "reps": "30 sec"}]}]}',
ARRAY['trx', 'intermediate', 'plank', 'core', 'stability'], 'trx_plank_variations.md'),

-- HIIT TRX
('aaa00001-0008-4000-8000-000000000008', 'TRX HIIT Blast', 'High-intensity intervals on the straps. Cardio meets strength.', 'cardio', 'intermediate', 30,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "TRX Squat", "sets": 2, "reps": "10"}, {"name": "TRX Row", "sets": 2, "reps": "10"}, {"name": "TRX Jump", "duration": "30 sec"}]}, {"name": "HIIT Circuit - 3 Rounds", "sequence": 1, "exercises": [{"name": "TRX Jump Squat", "duration": "40 sec"}, {"name": "Rest", "duration": "20 sec"}, {"name": "TRX Atomic Push-Up", "duration": "40 sec"}, {"name": "Rest", "duration": "20 sec"}, {"name": "TRX Sprinter Start", "duration": "40 sec"}, {"name": "Rest", "duration": "20 sec"}, {"name": "TRX Mountain Climber", "duration": "40 sec"}, {"name": "Rest", "duration": "20 sec"}, {"name": "TRX Burpee", "duration": "40 sec"}, {"name": "Rest", "duration": "60 sec between rounds"}]}, {"name": "Finisher", "sequence": 2, "exercises": [{"name": "TRX Squat Jump", "sets": 1, "reps": "20"}, {"name": "TRX Plank", "duration": "1 min"}]}, {"name": "Cool Down", "sequence": 3, "exercises": [{"name": "TRX Stretching", "duration": "3 min"}]}]}',
ARRAY['trx', 'intermediate', 'hiit', 'cardio', 'fat-burn'], 'trx_hiit_blast.md'),

('aaa00001-0009-4000-8000-000000000009', 'TRX Tabata', 'Tabata protocol meets TRX. 4-minute rounds of suspension torture.', 'cardio', 'advanced', 25,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "TRX Squat", "sets": 2, "reps": "10"}, {"name": "TRX Row", "sets": 2, "reps": "10"}]}, {"name": "Tabata 1 - Legs", "sequence": 1, "exercises": [{"name": "TRX Jump Squat", "sets": 8, "reps": "20 sec on / 10 sec off", "notes": "4 min total"}]}, {"name": "Rest", "sequence": 2, "exercises": [{"name": "Active Rest", "duration": "1 min"}]}, {"name": "Tabata 2 - Push", "sequence": 3, "exercises": [{"name": "TRX Atomic Push-Up", "sets": 8, "reps": "20 sec on / 10 sec off", "notes": "4 min total"}]}, {"name": "Rest", "sequence": 4, "exercises": [{"name": "Active Rest", "duration": "1 min"}]}, {"name": "Tabata 3 - Pull", "sequence": 5, "exercises": [{"name": "TRX Row - Fast", "sets": 8, "reps": "20 sec on / 10 sec off", "notes": "4 min total"}]}, {"name": "Rest", "sequence": 6, "exercises": [{"name": "Active Rest", "duration": "1 min"}]}, {"name": "Tabata 4 - Core", "sequence": 7, "exercises": [{"name": "TRX Mountain Climber", "sets": 8, "reps": "20 sec on / 10 sec off", "notes": "4 min total"}]}, {"name": "Cool Down", "sequence": 8, "exercises": [{"name": "TRX Stretch", "duration": "3 min"}]}]}',
ARRAY['trx', 'advanced', 'tabata', 'hiit', 'intense'], 'trx_tabata.md'),

-- CIRCUIT TRX
('aaa00001-0010-4000-8000-000000000010', 'TRX Circuit Training', 'Move through stations on the straps. Full body circuit format.', 'full_body', 'intermediate', 40,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "TRX Squat", "sets": 1, "reps": "10"}, {"name": "TRX Row", "sets": 1, "reps": "10"}, {"name": "TRX Plank", "duration": "20 sec"}]}, {"name": "Circuit - 4 Rounds", "sequence": 1, "exercises": [{"name": "TRX Chest Press", "reps": "12"}, {"name": "TRX Row", "reps": "12"}, {"name": "TRX Squat", "reps": "15"}, {"name": "TRX Lunge", "reps": "10 each"}, {"name": "TRX Pike", "reps": "10"}, {"name": "TRX Bicep Curl", "reps": "12"}, {"name": "TRX Tricep Press", "reps": "12"}, {"name": "Rest", "duration": "60 sec between rounds"}]}, {"name": "Finisher", "sequence": 2, "exercises": [{"name": "TRX Burpee", "sets": 2, "reps": "10"}, {"name": "TRX Plank Hold", "duration": "45 sec"}]}, {"name": "Cool Down", "sequence": 3, "exercises": [{"name": "TRX Stretching", "duration": "5 min"}]}]}',
ARRAY['trx', 'intermediate', 'circuit', 'full-body', 'conditioning'], 'trx_circuit.md'),

-- ADVANCED TRX
('aaa00001-0011-4000-8000-000000000011', 'TRX Advanced Moves', 'Master the challenging TRX exercises. For experienced users only.', 'strength', 'advanced', 45,
'{"blocks": [{"name": "Activation", "sequence": 0, "exercises": [{"name": "TRX Push-Up", "sets": 2, "reps": "10"}, {"name": "TRX Row", "sets": 2, "reps": "10"}]}, {"name": "Advanced Push", "sequence": 1, "exercises": [{"name": "TRX Atomic Push-Up", "sets": 4, "reps": "10"}, {"name": "TRX Push-Up - Feet in Straps, Hands Narrow", "sets": 3, "reps": "10"}, {"name": "TRX Suspended Push-Up (feet high)", "sets": 3, "reps": "8"}]}, {"name": "Advanced Pull", "sequence": 2, "exercises": [{"name": "TRX Single Arm Row", "sets": 3, "reps": "10 each"}, {"name": "TRX Power Pull", "sets": 4, "reps": "8 each"}, {"name": "TRX Face Pull to External Rotation", "sets": 3, "reps": "10"}]}, {"name": "Advanced Legs", "sequence": 3, "exercises": [{"name": "TRX Pistol Squat", "sets": 3, "reps": "8 each"}, {"name": "TRX Sprinter Lunge", "sets": 3, "reps": "10 each"}, {"name": "TRX Single Leg Burpee", "sets": 2, "reps": "6 each"}]}, {"name": "Advanced Core", "sequence": 4, "exercises": [{"name": "TRX Pike", "sets": 4, "reps": "12"}, {"name": "TRX Suspended Crunch to Pike", "sets": 3, "reps": "8"}, {"name": "TRX Pendulum", "sets": 3, "reps": "10 each"}, {"name": "TRX Body Saw to Pike", "sets": 3, "reps": "8"}]}, {"name": "Cool Down", "sequence": 5, "exercises": [{"name": "TRX Stretching", "duration": "5 min"}]}]}',
ARRAY['trx', 'advanced', 'challenging', 'progression', 'master'], 'trx_advanced_moves.md'),

('aaa00001-0012-4000-8000-000000000012', 'TRX Single Arm & Single Leg', 'Unilateral focus on the TRX. Address imbalances and build stability.', 'strength', 'advanced', 40,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "TRX Squat", "sets": 2, "reps": "10"}, {"name": "TRX Row", "sets": 2, "reps": "10"}]}, {"name": "Single Arm Upper", "sequence": 1, "exercises": [{"name": "TRX Single Arm Chest Press", "sets": 3, "reps": "10 each"}, {"name": "TRX Single Arm Row", "sets": 3, "reps": "10 each"}, {"name": "TRX Single Arm Tricep Press", "sets": 3, "reps": "10 each"}, {"name": "TRX Single Arm Bicep Curl", "sets": 3, "reps": "10 each"}]}, {"name": "Single Leg Lower", "sequence": 2, "exercises": [{"name": "TRX Pistol Squat", "sets": 3, "reps": "8 each"}, {"name": "TRX Single Leg Squat", "sets": 3, "reps": "10 each"}, {"name": "TRX Single Leg Hip Press", "sets": 3, "reps": "12 each"}, {"name": "TRX Crossing Balance Lunge", "sets": 3, "reps": "10 each"}]}, {"name": "Core", "sequence": 3, "exercises": [{"name": "TRX Single Leg Plank", "sets": 2, "reps": "20 sec each"}, {"name": "TRX Single Arm Plank", "sets": 2, "reps": "15 sec each"}]}, {"name": "Stretch", "sequence": 4, "exercises": [{"name": "TRX Stretching Series", "duration": "5 min"}]}]}',
ARRAY['trx', 'advanced', 'unilateral', 'single-arm', 'single-leg'], 'trx_unilateral.md'),

-- SPORT-SPECIFIC TRX
('aaa00001-0013-4000-8000-000000000013', 'TRX for Runners', 'Build running strength and stability using TRX suspension trainer.', 'strength', 'intermediate', 35,
'{"blocks": [{"name": "Activation", "sequence": 0, "exercises": [{"name": "TRX Hip Hinge", "sets": 2, "reps": "10"}, {"name": "TRX Squat", "sets": 2, "reps": "10"}]}, {"name": "Single Leg Strength", "sequence": 1, "exercises": [{"name": "TRX Pistol Squat Assist", "sets": 3, "reps": "8 each"}, {"name": "TRX Single Leg Squat", "sets": 3, "reps": "10 each"}, {"name": "TRX Sprinter Start", "sets": 3, "reps": "10 each"}]}, {"name": "Hip & Glute", "sequence": 2, "exercises": [{"name": "TRX Hip Press", "sets": 3, "reps": "15"}, {"name": "TRX Single Leg Hip Press", "sets": 3, "reps": "12 each"}, {"name": "TRX Hamstring Curl", "sets": 3, "reps": "12"}]}, {"name": "Core Stability", "sequence": 3, "exercises": [{"name": "TRX Plank", "sets": 3, "reps": "45 sec"}, {"name": "TRX Side Plank", "sets": 3, "reps": "30 sec each"}, {"name": "TRX Mountain Climber", "sets": 2, "reps": "20 total"}]}, {"name": "Mobility", "sequence": 4, "exercises": [{"name": "TRX Hip Flexor Stretch", "duration": "1 min each"}, {"name": "TRX Hamstring Stretch", "duration": "1 min each"}, {"name": "TRX Calf Stretch", "duration": "1 min each"}]}]}',
ARRAY['trx', 'intermediate', 'running', 'single-leg', 'hip'], 'trx_for_runners.md'),

('aaa00001-0014-4000-8000-000000000014', 'TRX for Golfers', 'Rotational strength and flexibility for better golf performance.', 'full_body', 'intermediate', 35,
'{"blocks": [{"name": "Mobility", "sequence": 0, "exercises": [{"name": "TRX Hip Hinge with Rotation", "sets": 2, "reps": "8 each"}, {"name": "TRX Torso Rotation", "sets": 2, "reps": "10 each"}]}, {"name": "Rotational Core", "sequence": 1, "exercises": [{"name": "TRX Oblique Crunch", "sets": 3, "reps": "12 each"}, {"name": "TRX Power Pull", "sets": 3, "reps": "10 each"}, {"name": "TRX Pendulum", "sets": 3, "reps": "10 each"}]}, {"name": "Hip Strength", "sequence": 2, "exercises": [{"name": "TRX Hip Hinge", "sets": 3, "reps": "12"}, {"name": "TRX Lunge with Rotation", "sets": 3, "reps": "10 each"}, {"name": "TRX Single Leg Squat", "sets": 2, "reps": "8 each"}]}, {"name": "Upper Body", "sequence": 3, "exercises": [{"name": "TRX Row", "sets": 3, "reps": "12"}, {"name": "TRX Y-Fly", "sets": 3, "reps": "10"}, {"name": "TRX T-Fly", "sets": 3, "reps": "10"}]}, {"name": "Stretch", "sequence": 4, "exercises": [{"name": "TRX Torso Rotation Stretch", "duration": "1 min each"}, {"name": "TRX Hip Flexor Stretch", "duration": "1 min each"}, {"name": "TRX Lat Stretch", "duration": "1 min each"}]}]}',
ARRAY['trx', 'intermediate', 'golf', 'rotation', 'flexibility'], 'trx_for_golfers.md'),

-- MOBILITY/FLEXIBILITY TRX
('aaa00001-0015-4000-8000-000000000015', 'TRX Mobility & Stretch', 'Use TRX for assisted stretching and mobility work.', 'mobility', 'beginner', 30,
'{"blocks": [{"name": "Lower Body Mobility", "sequence": 0, "exercises": [{"name": "TRX Hip Flexor Stretch", "duration": "1 min each"}, {"name": "TRX Deep Squat Hold", "duration": "1 min"}, {"name": "TRX Hamstring Stretch", "duration": "1 min each"}, {"name": "TRX Calf Stretch", "duration": "45 sec each"}, {"name": "TRX Adductor Stretch", "duration": "1 min"}]}, {"name": "Upper Body Mobility", "sequence": 1, "exercises": [{"name": "TRX Chest Stretch", "duration": "1 min"}, {"name": "TRX Lat Stretch", "duration": "1 min each"}, {"name": "TRX Shoulder Stretch", "duration": "45 sec each"}, {"name": "TRX Tricep Stretch", "duration": "45 sec each"}]}, {"name": "Spine Mobility", "sequence": 2, "exercises": [{"name": "TRX Rotation Stretch", "duration": "1 min each"}, {"name": "TRX Side Bend", "duration": "45 sec each"}, {"name": "TRX Back Stretch", "duration": "1 min"}]}, {"name": "Flow", "sequence": 3, "exercises": [{"name": "TRX World Greatest Stretch", "sets": 2, "reps": "5 each"}]}]}',
ARRAY['trx', 'beginner', 'mobility', 'stretch', 'flexibility'], 'trx_mobility.md'),

('aaa00001-0016-4000-8000-000000000016', 'TRX Yoga Fusion', 'Combine TRX with yoga-inspired movements for flexibility and strength.', 'mobility', 'intermediate', 40,
'{"blocks": [{"name": "Grounding", "sequence": 0, "exercises": [{"name": "TRX Assisted Mountain Pose", "duration": "1 min"}, {"name": "TRX Breathing", "duration": "2 min"}]}, {"name": "Sun Salutation Flow", "sequence": 1, "exercises": [{"name": "TRX Forward Fold", "sets": 3, "reps": "30 sec"}, {"name": "TRX Plank", "sets": 3, "reps": "20 sec"}, {"name": "TRX Downward Dog", "sets": 3, "reps": "30 sec"}, {"name": "TRX Warrior I (each side)", "sets": 2, "reps": "30 sec each"}]}, {"name": "Balance Series", "sequence": 2, "exercises": [{"name": "TRX Tree Pose", "sets": 2, "reps": "30 sec each"}, {"name": "TRX Warrior III", "sets": 2, "reps": "20 sec each"}, {"name": "TRX Half Moon", "sets": 2, "reps": "20 sec each"}]}, {"name": "Strength Flow", "sequence": 3, "exercises": [{"name": "TRX Crescent Lunge", "sets": 2, "reps": "30 sec each"}, {"name": "TRX Chair Pose", "sets": 2, "reps": "30 sec"}, {"name": "TRX Twisted Lunge", "sets": 2, "reps": "30 sec each"}]}, {"name": "Restoration", "sequence": 4, "exercises": [{"name": "TRX Pigeon Pose", "duration": "1 min each"}, {"name": "TRX Supine Twist", "duration": "1 min each"}, {"name": "TRX Savasana Stretch", "duration": "2 min"}]}]}',
ARRAY['trx', 'intermediate', 'yoga', 'fusion', 'flexibility'], 'trx_yoga_fusion.md'),

-- REHAB/PREHAB TRX
('aaa00001-0017-4000-8000-000000000017', 'TRX Shoulder Stability', 'Prehab and rehab for shoulders using TRX. Build bulletproof shoulders.', 'mobility', 'beginner', 30,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "TRX Arm Circles", "sets": 2, "reps": "10 each direction"}, {"name": "TRX Row - Light", "sets": 2, "reps": "10"}]}, {"name": "Scapular Control", "sequence": 1, "exercises": [{"name": "TRX Y-Fly", "sets": 3, "reps": "12"}, {"name": "TRX T-Fly", "sets": 3, "reps": "12"}, {"name": "TRX W-Pull", "sets": 3, "reps": "12"}, {"name": "TRX I-Fly", "sets": 3, "reps": "10"}]}, {"name": "Rotator Cuff", "sequence": 2, "exercises": [{"name": "TRX External Rotation", "sets": 3, "reps": "12 each"}, {"name": "TRX Face Pull", "sets": 3, "reps": "12"}, {"name": "TRX High Row", "sets": 3, "reps": "10"}]}, {"name": "Stability Challenge", "sequence": 3, "exercises": [{"name": "TRX Plank with Reach", "sets": 2, "reps": "8 each"}, {"name": "TRX Push-Up Plus", "sets": 2, "reps": "10"}, {"name": "TRX Clock Reach", "sets": 2, "reps": "5 each direction"}]}, {"name": "Stretch", "sequence": 4, "exercises": [{"name": "TRX Chest Stretch", "duration": "1 min"}, {"name": "TRX Lat Stretch", "duration": "1 min each"}, {"name": "TRX Posterior Shoulder Stretch", "duration": "45 sec each"}]}]}',
ARRAY['trx', 'beginner', 'shoulder', 'prehab', 'stability'], 'trx_shoulder_stability.md'),

('aaa00001-0018-4000-8000-000000000018', 'TRX Back Health', 'Strengthen your back and improve posture using TRX.', 'mobility', 'beginner', 30,
'{"blocks": [{"name": "Mobilization", "sequence": 0, "exercises": [{"name": "TRX Cat Cow", "sets": 2, "reps": "8"}, {"name": "TRX Rotation", "sets": 2, "reps": "8 each"}]}, {"name": "Core Activation", "sequence": 1, "exercises": [{"name": "TRX Plank", "sets": 3, "reps": "30 sec"}, {"name": "TRX Dead Bug", "sets": 2, "reps": "8 each"}, {"name": "TRX Bird Dog", "sets": 2, "reps": "8 each"}]}, {"name": "Back Strength", "sequence": 2, "exercises": [{"name": "TRX Row", "sets": 3, "reps": "12"}, {"name": "TRX Y-Fly", "sets": 3, "reps": "10"}, {"name": "TRX Reverse Fly", "sets": 3, "reps": "10"}, {"name": "TRX Hip Hinge", "sets": 3, "reps": "12"}]}, {"name": "Posture", "sequence": 3, "exercises": [{"name": "TRX Face Pull", "sets": 3, "reps": "12"}, {"name": "TRX W-Pull", "sets": 2, "reps": "12"}, {"name": "TRX Chest Stretch Hold", "duration": "1 min"}]}, {"name": "Release", "sequence": 4, "exercises": [{"name": "TRX Lat Stretch", "duration": "1 min each"}, {"name": "TRX Back Stretch", "duration": "1 min"}, {"name": "TRX Hip Flexor Stretch", "duration": "1 min each"}]}]}',
ARRAY['trx', 'beginner', 'back', 'posture', 'spine'], 'trx_back_health.md'),

-- TIME-BASED TRX
('aaa00001-0019-4000-8000-000000000019', '15-Minute TRX Express', 'Quick full body TRX workout. Get in, get out, get results.', 'full_body', 'intermediate', 15,
'{"blocks": [{"name": "Quick Warm Up", "sequence": 0, "exercises": [{"name": "TRX Squat", "sets": 1, "reps": "10"}, {"name": "TRX Row", "sets": 1, "reps": "10"}]}, {"name": "Circuit - 2 Rounds", "sequence": 1, "exercises": [{"name": "TRX Chest Press", "duration": "45 sec"}, {"name": "TRX Row", "duration": "45 sec"}, {"name": "TRX Squat", "duration": "45 sec"}, {"name": "TRX Lunge (alternating)", "duration": "45 sec"}, {"name": "TRX Plank", "duration": "45 sec"}, {"name": "Rest", "duration": "30 sec between rounds"}]}, {"name": "Quick Stretch", "sequence": 2, "exercises": [{"name": "TRX Hip Flexor Stretch", "duration": "30 sec each"}, {"name": "TRX Chest Stretch", "duration": "30 sec"}]}]}',
ARRAY['trx', 'intermediate', 'express', '15-minute', 'quick'], 'trx_15_minute.md'),

('aaa00001-0020-4000-8000-000000000020', '30-Minute TRX Complete', 'Comprehensive TRX workout in 30 minutes. Hit everything.', 'full_body', 'intermediate', 30,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "TRX Squat", "sets": 1, "reps": "10"}, {"name": "TRX Row", "sets": 1, "reps": "10"}, {"name": "TRX Plank", "duration": "20 sec"}]}, {"name": "Lower Body", "sequence": 1, "exercises": [{"name": "TRX Squat", "sets": 3, "reps": "12"}, {"name": "TRX Lunge", "sets": 2, "reps": "10 each"}, {"name": "TRX Hamstring Curl", "sets": 2, "reps": "12"}]}, {"name": "Upper Push", "sequence": 2, "exercises": [{"name": "TRX Chest Press", "sets": 3, "reps": "12"}, {"name": "TRX Tricep Press", "sets": 2, "reps": "12"}]}, {"name": "Upper Pull", "sequence": 3, "exercises": [{"name": "TRX Row", "sets": 3, "reps": "12"}, {"name": "TRX Bicep Curl", "sets": 2, "reps": "12"}]}, {"name": "Core", "sequence": 4, "exercises": [{"name": "TRX Plank", "sets": 2, "reps": "30 sec"}, {"name": "TRX Crunch", "sets": 2, "reps": "12"}, {"name": "TRX Pike", "sets": 2, "reps": "8"}]}, {"name": "Cool Down", "sequence": 5, "exercises": [{"name": "TRX Stretching", "duration": "3 min"}]}]}',
ARRAY['trx', 'intermediate', 'complete', '30-minute', 'full-body'], 'trx_30_minute.md'),

-- SPECIALIZED TRX
('aaa00001-0021-4000-8000-000000000021', 'TRX Metabolic Conditioning', 'High-rep TRX for metabolic burn. Strength meets cardio.', 'cardio', 'intermediate', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "TRX Jumping Squat", "sets": 2, "reps": "10"}, {"name": "TRX Row", "sets": 2, "reps": "10"}]}, {"name": "Metabolic Circuit - 3 Rounds", "sequence": 1, "exercises": [{"name": "TRX Jump Squat", "reps": "20"}, {"name": "TRX Push-Up", "reps": "15"}, {"name": "TRX Row - Fast", "reps": "20"}, {"name": "TRX Mountain Climber", "reps": "30 total"}, {"name": "TRX Lunge", "reps": "20 total"}, {"name": "TRX Plank Jack", "reps": "20"}, {"name": "Rest", "duration": "60 sec between rounds"}]}, {"name": "Finisher - AMRAP 3 Min", "sequence": 2, "exercises": [{"name": "TRX Burpee", "reps": "5"}, {"name": "TRX Squat", "reps": "10"}, {"name": "TRX Row", "reps": "10"}, {"name": "Repeat AMRAP", "notes": "3 min"}]}, {"name": "Cool Down", "sequence": 3, "exercises": [{"name": "TRX Stretching", "duration": "4 min"}]}]}',
ARRAY['trx', 'intermediate', 'metabolic', 'conditioning', 'fat-burn'], 'trx_metabolic.md'),

('aaa00001-0022-4000-8000-000000000022', 'TRX Power Training', 'Explosive movements on the straps. Build athletic power.', 'strength', 'advanced', 40,
'{"blocks": [{"name": "Activation", "sequence": 0, "exercises": [{"name": "TRX Squat", "sets": 2, "reps": "10"}, {"name": "TRX Row", "sets": 2, "reps": "10"}, {"name": "TRX Jump", "sets": 2, "reps": "5"}]}, {"name": "Lower Body Power", "sequence": 1, "exercises": [{"name": "TRX Jump Squat", "sets": 4, "reps": "10"}, {"name": "TRX Split Jump", "sets": 4, "reps": "8 each"}, {"name": "TRX Broad Jump Assist", "sets": 3, "reps": "6"}]}, {"name": "Upper Body Power", "sequence": 2, "exercises": [{"name": "TRX Explosive Push-Up", "sets": 4, "reps": "8"}, {"name": "TRX Power Pull", "sets": 4, "reps": "8 each"}, {"name": "TRX Chest Press - Explosive", "sets": 3, "reps": "10"}]}, {"name": "Full Body Power", "sequence": 3, "exercises": [{"name": "TRX Burpee", "sets": 4, "reps": "8"}, {"name": "TRX Sprinter Start", "sets": 3, "reps": "10 each"}]}, {"name": "Core Power", "sequence": 4, "exercises": [{"name": "TRX Atomic Push-Up - Explosive", "sets": 3, "reps": "8"}, {"name": "TRX Pendulum - Fast", "sets": 3, "reps": "10 each"}]}, {"name": "Cool Down", "sequence": 5, "exercises": [{"name": "TRX Stretching", "duration": "5 min"}]}]}',
ARRAY['trx', 'advanced', 'power', 'explosive', 'athletic'], 'trx_power.md'),

('aaa00001-0023-4000-8000-000000000023', 'TRX for Seniors', 'Safe TRX exercises for older adults. Build functional strength.', 'full_body', 'beginner', 30,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "TRX Assisted March", "duration": "2 min"}, {"name": "TRX Arm Circles", "sets": 2, "reps": "8 each direction"}]}, {"name": "Lower Body", "sequence": 1, "exercises": [{"name": "TRX Assisted Squat", "sets": 3, "reps": "10"}, {"name": "TRX Assisted Single Leg Stand", "sets": 2, "reps": "30 sec each"}, {"name": "TRX Step Back Lunge", "sets": 2, "reps": "8 each"}]}, {"name": "Upper Body", "sequence": 2, "exercises": [{"name": "TRX Row - Light Angle", "sets": 3, "reps": "10"}, {"name": "TRX Chest Press - Light Angle", "sets": 3, "reps": "10"}, {"name": "TRX Y-Fly", "sets": 2, "reps": "10"}]}, {"name": "Core & Balance", "sequence": 3, "exercises": [{"name": "TRX Plank - Hands on Floor", "sets": 2, "reps": "20 sec"}, {"name": "TRX Balance Stand", "sets": 2, "reps": "30 sec each leg"}]}, {"name": "Stretch", "sequence": 4, "exercises": [{"name": "TRX Hip Flexor Stretch", "duration": "1 min each"}, {"name": "TRX Chest Stretch", "duration": "1 min"}, {"name": "TRX Calf Stretch", "duration": "45 sec each"}]}]}',
ARRAY['trx', 'beginner', 'seniors', 'safe', 'functional'], 'trx_seniors.md'),

('aaa00001-0024-4000-8000-000000000024', 'TRX Pull Focus', 'Dedicated pulling session. Back, biceps, and rear delts.', 'upper', 'intermediate', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "TRX Row - Light", "sets": 2, "reps": "10"}, {"name": "TRX Arm Circles", "sets": 2, "reps": "8 each"}]}, {"name": "Horizontal Pull", "sequence": 1, "exercises": [{"name": "TRX Row", "sets": 4, "reps": "12"}, {"name": "TRX Wide Row", "sets": 3, "reps": "12"}, {"name": "TRX Single Arm Row", "sets": 3, "reps": "10 each"}]}, {"name": "Vertical Pull Pattern", "sequence": 2, "exercises": [{"name": "TRX High Row", "sets": 3, "reps": "12"}, {"name": "TRX Face Pull", "sets": 3, "reps": "12"}, {"name": "TRX Power Pull", "sets": 3, "reps": "8 each"}]}, {"name": "Rear Delts", "sequence": 3, "exercises": [{"name": "TRX Y-Fly", "sets": 3, "reps": "12"}, {"name": "TRX T-Fly", "sets": 3, "reps": "12"}, {"name": "TRX W-Pull", "sets": 3, "reps": "12"}]}, {"name": "Biceps", "sequence": 4, "exercises": [{"name": "TRX Bicep Curl", "sets": 3, "reps": "12"}, {"name": "TRX Single Arm Curl", "sets": 2, "reps": "10 each"}]}, {"name": "Stretch", "sequence": 5, "exercises": [{"name": "TRX Lat Stretch", "duration": "1 min each"}, {"name": "TRX Bicep Stretch", "duration": "45 sec each"}]}]}',
ARRAY['trx', 'intermediate', 'pull', 'back', 'biceps'], 'trx_pull_focus.md'),

('aaa00001-0025-4000-8000-000000000025', 'TRX Push Focus', 'Dedicated pushing session. Chest, shoulders, and triceps.', 'upper', 'intermediate', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "TRX Chest Press - Light", "sets": 2, "reps": "10"}, {"name": "TRX Arm Circles", "sets": 2, "reps": "8 each"}]}, {"name": "Chest", "sequence": 1, "exercises": [{"name": "TRX Chest Press", "sets": 4, "reps": "12"}, {"name": "TRX Push-Up", "sets": 3, "reps": "12"}, {"name": "TRX Chest Fly", "sets": 3, "reps": "10"}]}, {"name": "Shoulders", "sequence": 2, "exercises": [{"name": "TRX Deltoid Raise", "sets": 3, "reps": "12"}, {"name": "TRX I-Fly", "sets": 3, "reps": "10"}, {"name": "TRX Y-Fly (front delt focus)", "sets": 3, "reps": "10"}]}, {"name": "Triceps", "sequence": 3, "exercises": [{"name": "TRX Tricep Press", "sets": 3, "reps": "12"}, {"name": "TRX Skull Crusher", "sets": 3, "reps": "10"}, {"name": "TRX Diamond Push-Up", "sets": 2, "reps": "10"}]}, {"name": "Core Push", "sequence": 4, "exercises": [{"name": "TRX Atomic Push-Up", "sets": 3, "reps": "10"}, {"name": "TRX Plank", "sets": 2, "reps": "30 sec"}]}, {"name": "Stretch", "sequence": 5, "exercises": [{"name": "TRX Chest Stretch", "duration": "1 min"}, {"name": "TRX Tricep Stretch", "duration": "45 sec each"}, {"name": "TRX Shoulder Stretch", "duration": "45 sec each"}]}]}',
ARRAY['trx', 'intermediate', 'push', 'chest', 'triceps'], 'trx_push_focus.md');
