-- Create Program Reviews Table
-- ACP-395: PT Review and Approval Workflow
-- Adds an intermediate review/approval step between AI-generated programs
-- and patient deployment. Therapists review evidence citations, edit exercises,
-- and explicitly approve or reject before a program goes live.
--
-- Workflow: AI generates program -> PT reviews -> PT edits -> PT approves -> deploy

BEGIN;

-- ============================================================================
-- 1. PROGRAM REVIEWS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.program_reviews (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    program_id UUID NOT NULL REFERENCES public.programs(id) ON DELETE CASCADE,
    reviewer_id UUID NOT NULL REFERENCES public.therapists(id) ON DELETE CASCADE,

    -- Review status workflow
    status TEXT NOT NULL DEFAULT 'pending_review'
        CHECK (status IN ('pending_review', 'in_review', 'approved', 'rejected', 'revision_requested')),

    -- AI generation metadata
    ai_generated BOOLEAN DEFAULT TRUE,
    ai_model TEXT,
    ai_confidence_score DOUBLE PRECISION CHECK (ai_confidence_score IS NULL OR (ai_confidence_score >= 0 AND ai_confidence_score <= 100)),

    -- Review content
    review_notes TEXT,
    rejection_reason TEXT,

    -- Structured JSONB fields for audit trail and clinical data
    edits_made JSONB DEFAULT '[]'::jsonb,
    evidence_citations JSONB DEFAULT '[]'::jsonb,
    contraindications JSONB DEFAULT '[]'::jsonb,

    -- Approval timestamp (set when status becomes 'approved')
    approved_at TIMESTAMPTZ,

    -- Audit timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- 2. ALTER PROGRAMS TABLE — ADD REVIEW STATUS
-- ============================================================================

ALTER TABLE public.programs
    ADD COLUMN IF NOT EXISTS review_status TEXT
        DEFAULT 'draft'
        CHECK (review_status IN ('draft', 'pending_review', 'in_review', 'approved', 'rejected'));

-- ============================================================================
-- 3. INDEXES
-- ============================================================================

-- Fast lookup: all reviews for a program (audit trail)
CREATE INDEX IF NOT EXISTS idx_program_reviews_program_id
    ON public.program_reviews (program_id);

-- Fast lookup: reviews assigned to a therapist
CREATE INDEX IF NOT EXISTS idx_program_reviews_reviewer_id
    ON public.program_reviews (reviewer_id);

-- Review queue: pending and in-review items for a therapist, most recent first
CREATE INDEX IF NOT EXISTS idx_program_reviews_queue
    ON public.program_reviews (reviewer_id, status, created_at DESC)
    WHERE status IN ('pending_review', 'in_review');

-- Filter by status across all reviews
CREATE INDEX IF NOT EXISTS idx_program_reviews_status
    ON public.program_reviews (status);

-- Programs pending review (for dashboard counts)
CREATE INDEX IF NOT EXISTS idx_programs_review_status
    ON public.programs (review_status)
    WHERE review_status IS NOT NULL AND review_status != 'draft';

-- ============================================================================
-- 4. COMMENTS
-- ============================================================================

COMMENT ON TABLE public.program_reviews IS
    'Tracks the PT review and approval workflow for AI-generated (and manually created) programs';
COMMENT ON COLUMN public.program_reviews.status IS
    'Review workflow state: pending_review -> in_review -> approved | rejected | revision_requested';
COMMENT ON COLUMN public.program_reviews.ai_generated IS
    'Whether this program was generated by AI (TRUE) or manually created (FALSE)';
COMMENT ON COLUMN public.program_reviews.ai_model IS
    'AI model identifier that generated the program, e.g. "gpt-4", "claude"';
COMMENT ON COLUMN public.program_reviews.ai_confidence_score IS
    'AI confidence score (0-100) for the generated program';
COMMENT ON COLUMN public.program_reviews.edits_made IS
    'JSONB array of edits: [{"exercise_id": UUID, "field_changed": str, "old_value": str, "new_value": str}]';
COMMENT ON COLUMN public.program_reviews.evidence_citations IS
    'JSONB array of citations: [{"title": str, "authors": [str], "journal": str, "year": int, "doi": str, "relevance_note": str, "evidence_level": str}]';
COMMENT ON COLUMN public.program_reviews.contraindications IS
    'JSONB array of safety concerns: [{"type": str, "description": str, "severity": "critical"|"warning"|"info", "affected_exercises": [UUID]}]';
COMMENT ON COLUMN public.program_reviews.approved_at IS
    'Timestamp when the PT approved the program; NULL until approved';
COMMENT ON COLUMN public.programs.review_status IS
    'Review workflow status for the program: draft -> pending_review -> in_review -> approved | rejected';

-- ============================================================================
-- 5. ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE public.program_reviews ENABLE ROW LEVEL SECURITY;

-- Therapists can view reviews they are assigned to
CREATE POLICY "Therapists can view own reviews"
    ON public.program_reviews
    FOR SELECT
    TO authenticated
    USING (
        reviewer_id IN (
            SELECT id FROM public.therapists WHERE user_id = auth.uid()
        )
    );

-- Therapists can create reviews (assign to themselves)
CREATE POLICY "Therapists can create reviews"
    ON public.program_reviews
    FOR INSERT
    TO authenticated
    WITH CHECK (
        reviewer_id IN (
            SELECT id FROM public.therapists WHERE user_id = auth.uid()
        )
    );

-- Therapists can update their own reviews
CREATE POLICY "Therapists can update own reviews"
    ON public.program_reviews
    FOR UPDATE
    TO authenticated
    USING (
        reviewer_id IN (
            SELECT id FROM public.therapists WHERE user_id = auth.uid()
        )
    )
    WITH CHECK (
        reviewer_id IN (
            SELECT id FROM public.therapists WHERE user_id = auth.uid()
        )
    );

-- Therapists can delete their own reviews
CREATE POLICY "Therapists can delete own reviews"
    ON public.program_reviews
    FOR DELETE
    TO authenticated
    USING (
        reviewer_id IN (
            SELECT id FROM public.therapists WHERE user_id = auth.uid()
        )
    );

-- Patients can view reviews for programs assigned to them (read-only)
CREATE POLICY "Patients can view reviews for their programs"
    ON public.program_reviews
    FOR SELECT
    TO authenticated
    USING (
        program_id IN (
            SELECT id FROM public.programs
            WHERE patient_id IN (
                SELECT id FROM public.patients WHERE user_id = auth.uid()
            )
        )
    );

-- ============================================================================
-- 6. UPDATED_AT TRIGGER
-- ============================================================================

-- Depends on: update_updated_at_column() from 20260104220000_build138_complete_schema.sql
CREATE TRIGGER update_program_reviews_updated_at
    BEFORE UPDATE ON public.program_reviews
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================================
-- 7. GRANT PERMISSIONS
-- ============================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON public.program_reviews TO authenticated;

COMMIT;
