-- Seed Pilates workout templates
-- Based on Classical Pilates (Joseph Pilates' original 34 exercises), Mat, and Reformer sequences

INSERT INTO system_workout_templates (id, name, description, category, difficulty, duration_minutes, exercises, tags, source_file) VALUES

-- BEGINNER MAT PILATES
('011a0001-0001-4000-8000-000000000001', 'Pilates Fundamentals', 'Learn the 6 Pilates principles: breath, concentration, control, flow, centering, precision. Foundation exercises for beginners.', 'mobility', 'beginner', 30,
'{"blocks": [{"name": "Breathing & Centering", "sequence": 0, "exercises": [{"name": "Diaphragmatic Breathing", "duration": "3 min"}, {"name": "Pelvic Floor Activation", "sets": 3, "reps": "10 breaths"}, {"name": "Neutral Spine Finding", "duration": "2 min"}]}, {"name": "Core Activation", "sequence": 1, "exercises": [{"name": "Imprint & Release", "sets": 2, "reps": "10"}, {"name": "Toe Taps", "sets": 2, "reps": "10 each"}, {"name": "Leg Slides", "sets": 2, "reps": "10 each"}]}, {"name": "Basic Movements", "sequence": 2, "exercises": [{"name": "Pelvic Curl", "sets": 3, "reps": "8"}, {"name": "Chest Lift", "sets": 3, "reps": "8"}, {"name": "Arm Circles", "sets": 2, "reps": "8 each direction"}]}, {"name": "Stretching", "sequence": 3, "exercises": [{"name": "Knee Folds", "duration": "2 min"}, {"name": "Spinal Twist", "sets": 2, "reps": "30 sec each side"}]}]}',
ARRAY['pilates', 'beginner', 'mat', 'fundamentals', 'core'], 'pilates_fundamentals.md'),

('011a0001-0002-4000-8000-000000000002', 'Classical Mat Beginner', 'The essential beginner exercises from Joseph Pilates'' Return to Life sequence.', 'mobility', 'beginner', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Hundred Prep", "sets": 3, "reps": "50 pumps"}, {"name": "Roll Up Prep", "sets": 3, "reps": "5"}]}, {"name": "Core Series", "sequence": 1, "exercises": [{"name": "Single Leg Circle", "sets": 2, "reps": "5 each direction"}, {"name": "Rolling Like a Ball", "sets": 1, "reps": "6"}, {"name": "Single Leg Stretch", "sets": 1, "reps": "10 each"}]}, {"name": "Spine", "sequence": 2, "exercises": [{"name": "Spine Stretch Forward", "sets": 3, "reps": "5"}, {"name": "Saw", "sets": 2, "reps": "5 each side"}]}, {"name": "Back Extension", "sequence": 3, "exercises": [{"name": "Swan Prep", "sets": 3, "reps": "5"}, {"name": "Single Leg Kick", "sets": 2, "reps": "8 each"}]}, {"name": "Cool Down", "sequence": 4, "exercises": [{"name": "Seal", "sets": 1, "reps": "6"}, {"name": "Mermaid Stretch", "sets": 2, "reps": "3 each side"}]}]}',
ARRAY['pilates', 'beginner', 'mat', 'classical', 'return-to-life'], 'classical_mat_beginner.md'),

('011a0001-0003-4000-8000-000000000003', 'Pilates Core Basics', 'Focus on the powerhouse - Pilates term for deep core muscles. Build foundational core strength.', 'mobility', 'beginner', 25,
'{"blocks": [{"name": "Activation", "sequence": 0, "exercises": [{"name": "Transverse Abdominis Activation", "duration": "2 min"}, {"name": "Pelvic Floor Engagement", "sets": 3, "reps": "10 breaths"}]}, {"name": "Core Work", "sequence": 1, "exercises": [{"name": "Hundred Prep", "sets": 2, "reps": "50 pumps"}, {"name": "Dead Bug", "sets": 3, "reps": "10 each"}, {"name": "Chest Lift with Rotation", "sets": 2, "reps": "8 each side"}, {"name": "Single Leg Stretch", "sets": 2, "reps": "10 each"}]}, {"name": "Stabilization", "sequence": 2, "exercises": [{"name": "Bird Dog", "sets": 2, "reps": "8 each"}, {"name": "Plank Hold", "sets": 3, "reps": "20 sec"}]}, {"name": "Release", "sequence": 3, "exercises": [{"name": "Child Pose", "duration": "1 min"}, {"name": "Spinal Twist", "sets": 1, "reps": "30 sec each"}]}]}',
ARRAY['pilates', 'beginner', 'core', 'powerhouse', 'mat'], 'pilates_core_basics.md'),

-- INTERMEDIATE MAT PILATES
('011a0001-0004-4000-8000-000000000004', 'Classical Mat Intermediate', 'Progress through the intermediate sequence from Joseph Pilates'' original mat work.', 'mobility', 'intermediate', 45,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "The Hundred", "sets": 1, "reps": "100 pumps"}, {"name": "Roll Up", "sets": 1, "reps": "5"}]}, {"name": "Ab Series", "sequence": 1, "exercises": [{"name": "Single Leg Stretch", "sets": 1, "reps": "10 each"}, {"name": "Double Leg Stretch", "sets": 1, "reps": "10"}, {"name": "Single Straight Leg Stretch", "sets": 1, "reps": "10 each"}, {"name": "Double Straight Leg Lower", "sets": 1, "reps": "10"}, {"name": "Criss Cross", "sets": 1, "reps": "10 each"}]}, {"name": "Spine Work", "sequence": 2, "exercises": [{"name": "Spine Stretch Forward", "sets": 1, "reps": "5"}, {"name": "Open Leg Rocker", "sets": 1, "reps": "6"}, {"name": "Corkscrew", "sets": 1, "reps": "3 each direction"}, {"name": "Saw", "sets": 1, "reps": "4 each side"}]}, {"name": "Back Extension", "sequence": 3, "exercises": [{"name": "Swan Dive", "sets": 1, "reps": "5"}, {"name": "Single Leg Kick", "sets": 1, "reps": "8 each"}, {"name": "Double Leg Kick", "sets": 1, "reps": "3 each side"}]}, {"name": "Side Series", "sequence": 4, "exercises": [{"name": "Side Kick Front/Back", "sets": 1, "reps": "10 each"}, {"name": "Side Kick Up/Down", "sets": 1, "reps": "10 each"}, {"name": "Side Kick Circles", "sets": 1, "reps": "8 each direction"}]}, {"name": "Finish", "sequence": 5, "exercises": [{"name": "Teaser Prep", "sets": 1, "reps": "5"}, {"name": "Swimming", "sets": 1, "reps": "20 counts"}, {"name": "Seal", "sets": 1, "reps": "6"}]}]}',
ARRAY['pilates', 'intermediate', 'mat', 'classical', 'full-body'], 'classical_mat_intermediate.md'),

('011a0001-0005-4000-8000-000000000005', 'Pilates Ab Series of Five', 'The famous five-exercise abdominal sequence. Intense core work in a focused session.', 'mobility', 'intermediate', 20,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Pelvic Curl", "sets": 3, "reps": "5"}, {"name": "Chest Lift", "sets": 2, "reps": "8"}]}, {"name": "Series of Five", "sequence": 1, "exercises": [{"name": "Single Leg Stretch", "sets": 2, "reps": "20 total"}, {"name": "Double Leg Stretch", "sets": 2, "reps": "10"}, {"name": "Single Straight Leg Stretch", "sets": 2, "reps": "20 total"}, {"name": "Double Straight Leg Lower", "sets": 2, "reps": "10"}, {"name": "Criss Cross", "sets": 2, "reps": "20 total"}]}, {"name": "Recovery", "sequence": 2, "exercises": [{"name": "Rolling Like a Ball", "sets": 1, "reps": "6"}, {"name": "Knee Fold Stretch", "duration": "1 min"}]}]}',
ARRAY['pilates', 'intermediate', 'abs', 'core', 'series-of-five'], 'pilates_ab_series.md'),

('011a0001-0006-4000-8000-000000000006', 'Pilates Spine Corrector Flow', 'Use the spine corrector (or towel roll) for enhanced back extension and flexibility work.', 'mobility', 'intermediate', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Breathing on Barrel", "duration": "2 min"}, {"name": "Pelvic Curl on Barrel", "sets": 3, "reps": "5"}]}, {"name": "Ab Work", "sequence": 1, "exercises": [{"name": "Chest Lift on Barrel", "sets": 3, "reps": "8"}, {"name": "Oblique Curl on Barrel", "sets": 2, "reps": "8 each"}]}, {"name": "Back Extension", "sequence": 2, "exercises": [{"name": "Swan on Barrel", "sets": 3, "reps": "5"}, {"name": "Grasshopper", "sets": 2, "reps": "8"}, {"name": "Rocking", "sets": 2, "reps": "6"}]}, {"name": "Hip Work", "sequence": 3, "exercises": [{"name": "Side Leg Lifts on Barrel", "sets": 2, "reps": "10 each"}, {"name": "Clam on Barrel", "sets": 2, "reps": "10 each"}]}, {"name": "Stretch", "sequence": 4, "exercises": [{"name": "Back Stretch over Barrel", "duration": "2 min"}, {"name": "Side Stretch on Barrel", "sets": 1, "reps": "1 min each"}]}]}',
ARRAY['pilates', 'intermediate', 'spine-corrector', 'back', 'flexibility'], 'pilates_spine_corrector.md'),

('011a0001-0007-4000-8000-000000000007', 'Pilates for Back Health', 'Gentle strengthening and mobility work for a healthy spine. Great for desk workers.', 'mobility', 'beginner', 30,
'{"blocks": [{"name": "Release", "sequence": 0, "exercises": [{"name": "Knee Folds", "sets": 2, "reps": "10 each"}, {"name": "Pelvic Rocks", "sets": 2, "reps": "10"}, {"name": "Cat Cow", "sets": 2, "reps": "8"}]}, {"name": "Core Support", "sequence": 1, "exercises": [{"name": "Dead Bug", "sets": 3, "reps": "10 each"}, {"name": "Bird Dog", "sets": 3, "reps": "8 each"}, {"name": "Pelvic Curl", "sets": 3, "reps": "8"}]}, {"name": "Extension", "sequence": 2, "exercises": [{"name": "Baby Swan", "sets": 3, "reps": "8"}, {"name": "Swimming Prep", "sets": 2, "reps": "10 each"}]}, {"name": "Mobility", "sequence": 3, "exercises": [{"name": "Spine Twist", "sets": 2, "reps": "5 each"}, {"name": "Thread the Needle", "sets": 2, "reps": "5 each"}, {"name": "Child Pose", "duration": "2 min"}]}]}',
ARRAY['pilates', 'beginner', 'back', 'spine', 'desk-worker', 'therapeutic'], 'pilates_back_health.md'),

-- ADVANCED MAT PILATES
('011a0001-0008-4000-8000-000000000008', 'Classical Mat Advanced', 'The full classical mat sequence as taught by Joseph Pilates. For experienced practitioners.', 'mobility', 'advanced', 55,
'{"blocks": [{"name": "Opening", "sequence": 0, "exercises": [{"name": "The Hundred", "sets": 1, "reps": "100 pumps"}, {"name": "Roll Up", "sets": 1, "reps": "5"}, {"name": "Roll Over", "sets": 1, "reps": "5"}]}, {"name": "Single Leg Work", "sequence": 1, "exercises": [{"name": "Single Leg Circle", "sets": 1, "reps": "5 each direction"}, {"name": "Rolling Like a Ball", "sets": 1, "reps": "6"}]}, {"name": "Ab Series", "sequence": 2, "exercises": [{"name": "Single Leg Stretch", "sets": 1, "reps": "10 each"}, {"name": "Double Leg Stretch", "sets": 1, "reps": "10"}, {"name": "Single Straight Leg", "sets": 1, "reps": "10 each"}, {"name": "Double Straight Leg", "sets": 1, "reps": "10"}, {"name": "Criss Cross", "sets": 1, "reps": "10 each"}]}, {"name": "Spine Series", "sequence": 3, "exercises": [{"name": "Spine Stretch Forward", "sets": 1, "reps": "5"}, {"name": "Open Leg Rocker", "sets": 1, "reps": "6"}, {"name": "Corkscrew", "sets": 1, "reps": "3 each"}, {"name": "Saw", "sets": 1, "reps": "4 each"}]}, {"name": "Back Extension", "sequence": 4, "exercises": [{"name": "Swan Dive", "sets": 1, "reps": "5"}, {"name": "Single Leg Kick", "sets": 1, "reps": "8 each"}, {"name": "Double Leg Kick", "sets": 1, "reps": "3 each"}, {"name": "Neck Pull", "sets": 1, "reps": "5"}]}, {"name": "Advanced Core", "sequence": 5, "exercises": [{"name": "Scissors", "sets": 1, "reps": "5 each"}, {"name": "Bicycle", "sets": 1, "reps": "5 each"}, {"name": "Shoulder Bridge", "sets": 1, "reps": "5 each leg"}, {"name": "Spine Twist", "sets": 1, "reps": "3 each"}]}, {"name": "Side Series", "sequence": 6, "exercises": [{"name": "Side Kick Series", "sets": 1, "reps": "complete sequence each side"}]}, {"name": "Closing", "sequence": 7, "exercises": [{"name": "Teaser 1, 2, 3", "sets": 1, "reps": "3 each variation"}, {"name": "Hip Circles", "sets": 1, "reps": "3 each direction"}, {"name": "Swimming", "sets": 1, "reps": "20 counts"}, {"name": "Leg Pull Front", "sets": 1, "reps": "5 each"}, {"name": "Leg Pull Back", "sets": 1, "reps": "5 each"}, {"name": "Kneeling Side Kick", "sets": 1, "reps": "5 each"}, {"name": "Side Bend", "sets": 1, "reps": "3 each"}, {"name": "Boomerang", "sets": 1, "reps": "4"}, {"name": "Seal", "sets": 1, "reps": "6"}, {"name": "Rocking", "sets": 1, "reps": "5"}, {"name": "Control Balance", "sets": 1, "reps": "3 each"}, {"name": "Push Up", "sets": 1, "reps": "3-5"}]}]}',
ARRAY['pilates', 'advanced', 'mat', 'classical', 'full-sequence'], 'classical_mat_advanced.md'),

('011a0001-0009-4000-8000-000000000009', 'Pilates Power Flow', 'Dynamic, challenging mat flow for advanced practitioners. Continuous movement.', 'mobility', 'advanced', 40,
'{"blocks": [{"name": "Dynamic Start", "sequence": 0, "exercises": [{"name": "Standing Roll Down", "sets": 3, "reps": "3"}, {"name": "Push Up to Pike", "sets": 2, "reps": "5"}]}, {"name": "Power Core", "sequence": 1, "exercises": [{"name": "The Hundred", "sets": 1, "reps": "100 pumps"}, {"name": "Roll Up", "sets": 1, "reps": "8"}, {"name": "Jackknife", "sets": 1, "reps": "5"}, {"name": "Teaser", "sets": 1, "reps": "5"}]}, {"name": "Flow Sequence", "sequence": 2, "exercises": [{"name": "Boomerang", "sets": 1, "reps": "6"}, {"name": "Seal to Stand", "sets": 1, "reps": "5"}, {"name": "Star", "sets": 1, "reps": "3 each side"}, {"name": "Twist", "sets": 1, "reps": "5 each"}]}, {"name": "Challenge", "sequence": 3, "exercises": [{"name": "Control Balance", "sets": 1, "reps": "5 each"}, {"name": "Scissors", "sets": 1, "reps": "8 each"}, {"name": "Bicycle", "sets": 1, "reps": "8 each"}]}, {"name": "Finish", "sequence": 4, "exercises": [{"name": "Swimming", "sets": 1, "reps": "30 counts"}, {"name": "Rocking", "sets": 1, "reps": "8"}, {"name": "Push Up Series", "sets": 1, "reps": "5"}]}]}',
ARRAY['pilates', 'advanced', 'power', 'flow', 'dynamic'], 'pilates_power_flow.md'),

('011a0001-0010-4000-8000-000000000010', 'Pilates Teaser Progression', 'Master the iconic Teaser exercise through progressive variations.', 'mobility', 'advanced', 30,
'{"blocks": [{"name": "Prep Work", "sequence": 0, "exercises": [{"name": "Roll Up", "sets": 3, "reps": "5"}, {"name": "Single Leg Stretch", "sets": 2, "reps": "10 each"}, {"name": "Double Straight Leg Lower", "sets": 2, "reps": "8"}]}, {"name": "Teaser Prep", "sequence": 1, "exercises": [{"name": "Teaser Prep - One Leg", "sets": 3, "reps": "5 each leg"}, {"name": "Teaser Prep - Both Legs Down", "sets": 3, "reps": "5"}]}, {"name": "Full Teaser", "sequence": 2, "exercises": [{"name": "Teaser 1", "sets": 3, "reps": "3"}, {"name": "Teaser 2 - Legs Only", "sets": 2, "reps": "5"}, {"name": "Teaser 3 - Full", "sets": 2, "reps": "3"}]}, {"name": "Variations", "sequence": 3, "exercises": [{"name": "Teaser with Twist", "sets": 2, "reps": "3 each"}, {"name": "Teaser with Arm Circles", "sets": 2, "reps": "3"}]}, {"name": "Recovery", "sequence": 4, "exercises": [{"name": "Rolling Like a Ball", "sets": 1, "reps": "6"}, {"name": "Spine Stretch Forward", "sets": 2, "reps": "3"}]}]}',
ARRAY['pilates', 'advanced', 'teaser', 'core', 'challenge'], 'pilates_teaser_progression.md'),

-- REFORMER PILATES
('011a0001-0011-4000-8000-000000000011', 'Reformer Beginner Flow', 'Introduction to the Pilates Reformer. Learn footwork, straps, and basic exercises.', 'mobility', 'beginner', 45,
'{"blocks": [{"name": "Footwork", "sequence": 0, "exercises": [{"name": "Parallel Heels", "sets": 2, "reps": "10"}, {"name": "Parallel Toes", "sets": 2, "reps": "10"}, {"name": "V Position", "sets": 2, "reps": "10"}, {"name": "Wide Second", "sets": 2, "reps": "10"}, {"name": "Single Leg", "sets": 2, "reps": "5 each"}]}, {"name": "Straps - Legs", "sequence": 1, "exercises": [{"name": "Leg Circles", "sets": 2, "reps": "5 each direction"}, {"name": "Frog", "sets": 2, "reps": "8"}, {"name": "Short Spine Prep", "sets": 2, "reps": "5"}]}, {"name": "Straps - Arms", "sequence": 2, "exercises": [{"name": "Arms Pulling", "sets": 2, "reps": "8"}, {"name": "Arm Circles", "sets": 2, "reps": "5 each"}, {"name": "Hug a Tree", "sets": 2, "reps": "8"}]}, {"name": "Hundred", "sequence": 3, "exercises": [{"name": "Hundred on Reformer", "sets": 1, "reps": "100 pumps"}]}, {"name": "Long Box", "sequence": 4, "exercises": [{"name": "Pulling Straps", "sets": 2, "reps": "5"}, {"name": "T-Pull", "sets": 2, "reps": "5"}, {"name": "Backstroke Prep", "sets": 2, "reps": "5"}]}, {"name": "Stretch", "sequence": 5, "exercises": [{"name": "Mermaid on Reformer", "sets": 2, "reps": "3 each"}, {"name": "Eve Lunge", "sets": 1, "reps": "30 sec each"}]}]}',
ARRAY['pilates', 'beginner', 'reformer', 'apparatus', 'studio'], 'reformer_beginner.md'),

('011a0001-0012-4000-8000-000000000012', 'Classical Reformer Intermediate', 'The intermediate classical Reformer sequence following Josephs order.', 'mobility', 'intermediate', 50,
'{"blocks": [{"name": "Footwork", "sequence": 0, "exercises": [{"name": "Footwork Series", "sets": 1, "reps": "10 each position"}]}, {"name": "Hundred & Coordination", "sequence": 1, "exercises": [{"name": "Hundred", "sets": 1, "reps": "100 pumps"}, {"name": "Coordination", "sets": 1, "reps": "5"}]}, {"name": "Rowing Series", "sequence": 2, "exercises": [{"name": "Rowing 1 - Into the Sternum", "sets": 1, "reps": "3"}, {"name": "Rowing 2 - 90 Degrees", "sets": 1, "reps": "3"}, {"name": "Rowing 3 - From Chest", "sets": 1, "reps": "3"}, {"name": "Rowing 4 - From Hips", "sets": 1, "reps": "3"}]}, {"name": "Long Box", "sequence": 3, "exercises": [{"name": "Swan", "sets": 1, "reps": "5"}, {"name": "Pulling Straps", "sets": 1, "reps": "5"}, {"name": "T-Pull", "sets": 1, "reps": "5"}, {"name": "Backstroke", "sets": 1, "reps": "5"}]}, {"name": "Short Box", "sequence": 4, "exercises": [{"name": "Round Back", "sets": 1, "reps": "3"}, {"name": "Flat Back", "sets": 1, "reps": "3"}, {"name": "Side to Side", "sets": 1, "reps": "3 each"}, {"name": "Twist & Reach", "sets": 1, "reps": "3 each"}, {"name": "Tree", "sets": 1, "reps": "3 each leg"}]}, {"name": "Long Stretch Series", "sequence": 5, "exercises": [{"name": "Long Stretch", "sets": 1, "reps": "5"}, {"name": "Down Stretch", "sets": 1, "reps": "5"}, {"name": "Up Stretch", "sets": 1, "reps": "5"}, {"name": "Elephant", "sets": 1, "reps": "5"}]}, {"name": "Stomach Massage", "sequence": 6, "exercises": [{"name": "Round", "sets": 1, "reps": "10"}, {"name": "Flat", "sets": 1, "reps": "10"}, {"name": "Reach", "sets": 1, "reps": "10"}, {"name": "Twist", "sets": 1, "reps": "5 each"}]}, {"name": "Knee Stretches", "sequence": 7, "exercises": [{"name": "Round Back", "sets": 1, "reps": "10"}, {"name": "Arched Back", "sets": 1, "reps": "10"}, {"name": "Knees Off", "sets": 1, "reps": "10"}]}, {"name": "Finish", "sequence": 8, "exercises": [{"name": "Running", "sets": 1, "reps": "20"}, {"name": "Pelvic Lift", "sets": 1, "reps": "5"}]}]}',
ARRAY['pilates', 'intermediate', 'reformer', 'classical', 'apparatus'], 'classical_reformer_intermediate.md'),

('011a0001-0013-4000-8000-000000000013', 'Reformer Jump Board Cardio', 'Cardio Pilates using the jump board attachment. Low-impact plyometrics.', 'cardio', 'intermediate', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Footwork - Parallel", "sets": 1, "reps": "10"}, {"name": "Footwork - V", "sets": 1, "reps": "10"}]}, {"name": "Basic Jumps", "sequence": 1, "exercises": [{"name": "Parallel Jumps", "sets": 3, "reps": "20"}, {"name": "First Position Jumps", "sets": 3, "reps": "20"}, {"name": "Second Position Jumps", "sets": 3, "reps": "20"}]}, {"name": "Cardio Intervals", "sequence": 2, "exercises": [{"name": "Alternating Single Leg", "sets": 3, "reps": "20 each"}, {"name": "Scissor Jumps", "sets": 3, "reps": "20"}, {"name": "Skater Jumps", "sets": 3, "reps": "16"}]}, {"name": "Core Challenge", "sequence": 3, "exercises": [{"name": "Hundred with Jumps", "sets": 1, "reps": "100 pumps"}, {"name": "Coordination with Jump", "sets": 2, "reps": "8"}]}, {"name": "Cool Down", "sequence": 4, "exercises": [{"name": "Footwork Slow", "sets": 1, "reps": "10 each position"}, {"name": "Supine Stretch", "duration": "3 min"}]}]}',
ARRAY['pilates', 'intermediate', 'reformer', 'jump-board', 'cardio'], 'reformer_jump_board.md'),

-- SPECIALIZED PILATES
('011a0001-0014-4000-8000-000000000014', 'Pilates for Runners', 'Address common runner imbalances: hip flexors, IT band, and core stability.', 'mobility', 'intermediate', 35,
'{"blocks": [{"name": "Hip Release", "sequence": 0, "exercises": [{"name": "Hip Flexor Stretch", "sets": 2, "reps": "30 sec each"}, {"name": "Figure 4 Stretch", "sets": 2, "reps": "30 sec each"}, {"name": "Leg Circles", "sets": 2, "reps": "5 each direction"}]}, {"name": "Core Stability", "sequence": 1, "exercises": [{"name": "Dead Bug", "sets": 3, "reps": "10 each"}, {"name": "Single Leg Stretch", "sets": 2, "reps": "10 each"}, {"name": "Criss Cross", "sets": 2, "reps": "10 each"}]}, {"name": "Hip Strength", "sequence": 2, "exercises": [{"name": "Side Leg Lifts", "sets": 2, "reps": "10 each"}, {"name": "Clam", "sets": 2, "reps": "10 each"}, {"name": "Single Leg Bridge", "sets": 2, "reps": "8 each"}]}, {"name": "Glute Work", "sequence": 3, "exercises": [{"name": "Shoulder Bridge", "sets": 3, "reps": "5 each leg"}, {"name": "Swimming", "sets": 2, "reps": "20 counts"}]}, {"name": "IT Band Release", "sequence": 4, "exercises": [{"name": "Side Lying Leg Series", "sets": 1, "reps": "complete series each side"}, {"name": "Mermaid Stretch", "sets": 2, "reps": "3 each side"}]}]}',
ARRAY['pilates', 'intermediate', 'runners', 'athletic', 'hip'], 'pilates_for_runners.md'),

('011a0001-0015-4000-8000-000000000015', 'Pilates for Golfers', 'Improve rotation, hip mobility, and core power for better golf performance.', 'mobility', 'intermediate', 35,
'{"blocks": [{"name": "Spine Mobility", "sequence": 0, "exercises": [{"name": "Spine Twist", "sets": 3, "reps": "5 each"}, {"name": "Saw", "sets": 3, "reps": "5 each"}, {"name": "Mermaid", "sets": 2, "reps": "3 each"}]}, {"name": "Hip Rotation", "sequence": 1, "exercises": [{"name": "Leg Circles", "sets": 2, "reps": "5 each direction"}, {"name": "Hip Stretch Series", "sets": 2, "reps": "30 sec each"}]}, {"name": "Rotational Core", "sequence": 2, "exercises": [{"name": "Criss Cross", "sets": 3, "reps": "10 each"}, {"name": "Oblique Roll Back", "sets": 2, "reps": "8 each"}, {"name": "Corkscrew", "sets": 2, "reps": "3 each"}]}, {"name": "Back Extension", "sequence": 3, "exercises": [{"name": "Swan", "sets": 3, "reps": "5"}, {"name": "Swimming", "sets": 2, "reps": "20 counts"}]}, {"name": "Balance", "sequence": 4, "exercises": [{"name": "Single Leg Balance", "sets": 2, "reps": "30 sec each"}, {"name": "Standing Roll Down", "sets": 3, "reps": "3"}]}]}',
ARRAY['pilates', 'intermediate', 'golf', 'rotation', 'athletic'], 'pilates_for_golfers.md'),

('011a0001-0016-4000-8000-000000000016', 'Prenatal Pilates', 'Safe, effective Pilates for pregnancy. Focus on pelvic floor and posture.', 'mobility', 'beginner', 30,
'{"blocks": [{"name": "Breathing", "sequence": 0, "exercises": [{"name": "Diaphragmatic Breathing", "duration": "3 min"}, {"name": "Pelvic Floor Connection", "sets": 3, "reps": "10 breaths"}]}, {"name": "Gentle Warm Up", "sequence": 1, "exercises": [{"name": "Cat Cow", "sets": 2, "reps": "8"}, {"name": "Arm Circles", "sets": 2, "reps": "8 each"}]}, {"name": "Side Lying", "sequence": 2, "exercises": [{"name": "Side Leg Lifts", "sets": 2, "reps": "10 each"}, {"name": "Clam", "sets": 2, "reps": "10 each"}, {"name": "Inner Thigh Lifts", "sets": 2, "reps": "10 each"}]}, {"name": "All Fours", "sequence": 3, "exercises": [{"name": "Bird Dog", "sets": 2, "reps": "8 each"}, {"name": "Thread the Needle", "sets": 2, "reps": "5 each"}]}, {"name": "Seated", "sequence": 4, "exercises": [{"name": "Spine Stretch Forward", "sets": 2, "reps": "5"}, {"name": "Saw Modification", "sets": 2, "reps": "3 each"}, {"name": "Mermaid", "sets": 2, "reps": "3 each"}]}, {"name": "Stretch", "sequence": 5, "exercises": [{"name": "Figure 4 Stretch", "sets": 1, "reps": "30 sec each"}, {"name": "Child Pose (Wide Knee)", "duration": "2 min"}]}]}',
ARRAY['pilates', 'beginner', 'prenatal', 'pregnancy', 'pelvic-floor'], 'prenatal_pilates.md'),

('011a0001-0017-4000-8000-000000000017', 'Postnatal Pilates Recovery', 'Gentle return to Pilates after pregnancy. Core reconnection and diastasis safe.', 'mobility', 'beginner', 25,
'{"blocks": [{"name": "Reconnection", "sequence": 0, "exercises": [{"name": "Diaphragmatic Breathing", "duration": "3 min"}, {"name": "Pelvic Floor Activation", "sets": 3, "reps": "10 breaths"}, {"name": "Transverse Connection", "sets": 3, "reps": "10"}]}, {"name": "Gentle Core", "sequence": 1, "exercises": [{"name": "Heel Slides", "sets": 2, "reps": "10 each"}, {"name": "Toe Taps", "sets": 2, "reps": "10 each"}, {"name": "Dead Bug Modified", "sets": 2, "reps": "8 each"}]}, {"name": "Hip Work", "sequence": 2, "exercises": [{"name": "Pelvic Curl", "sets": 3, "reps": "8"}, {"name": "Clam", "sets": 2, "reps": "10 each"}, {"name": "Bridge", "sets": 2, "reps": "10"}]}, {"name": "Upper Back", "sequence": 3, "exercises": [{"name": "Chest Opener", "sets": 2, "reps": "5"}, {"name": "Arm Circles", "sets": 2, "reps": "8 each"}]}, {"name": "Stretch", "sequence": 4, "exercises": [{"name": "Figure 4 Stretch", "sets": 1, "reps": "30 sec each"}, {"name": "Child Pose", "duration": "2 min"}]}]}',
ARRAY['pilates', 'beginner', 'postnatal', 'postpartum', 'core-recovery'], 'postnatal_pilates.md'),

('011a0001-0018-4000-8000-000000000018', 'Pilates Ring Toning', 'Use the magic circle (Pilates ring) for added resistance and muscle engagement.', 'mobility', 'intermediate', 35,
'{"blocks": [{"name": "Arms", "sequence": 0, "exercises": [{"name": "Ring Squeeze - Front", "sets": 3, "reps": "10"}, {"name": "Ring Squeeze - Overhead", "sets": 3, "reps": "10"}, {"name": "Ring Squeeze - Behind", "sets": 2, "reps": "10"}]}, {"name": "Core", "sequence": 1, "exercises": [{"name": "Hundred with Ring", "sets": 1, "reps": "100 pumps"}, {"name": "Roll Up with Ring", "sets": 2, "reps": "5"}, {"name": "Single Leg Stretch with Ring", "sets": 2, "reps": "10 each"}]}, {"name": "Inner Thigh", "sequence": 2, "exercises": [{"name": "Ring Between Ankles - Bridge", "sets": 3, "reps": "10"}, {"name": "Ring Between Knees - Squeeze", "sets": 3, "reps": "15"}, {"name": "Side Lying Inner Thigh", "sets": 2, "reps": "10 each"}]}, {"name": "Outer Thigh", "sequence": 3, "exercises": [{"name": "Ring Around Thighs - Clam", "sets": 2, "reps": "10 each"}, {"name": "Ring Press Out - Side Lying", "sets": 2, "reps": "10 each"}]}, {"name": "Stretch", "sequence": 4, "exercises": [{"name": "Figure 4 Stretch", "sets": 1, "reps": "30 sec each"}, {"name": "Mermaid", "sets": 2, "reps": "3 each"}]}]}',
ARRAY['pilates', 'intermediate', 'magic-circle', 'toning', 'equipment'], 'pilates_ring_toning.md'),

-- MORE SPECIALIZED
('011a0001-0019-4000-8000-000000000019', 'Pilates for Desk Workers', 'Counter the effects of sitting: open chest, strengthen back, release hips.', 'mobility', 'beginner', 25,
'{"blocks": [{"name": "Posture Reset", "sequence": 0, "exercises": [{"name": "Chest Opener", "sets": 3, "reps": "5 breaths"}, {"name": "Shoulder Rolls", "sets": 2, "reps": "8 each direction"}, {"name": "Neck Stretches", "sets": 2, "reps": "30 sec each"}]}, {"name": "Spine Mobility", "sequence": 1, "exercises": [{"name": "Cat Cow", "sets": 2, "reps": "8"}, {"name": "Spine Twist Seated", "sets": 2, "reps": "5 each"}, {"name": "Mermaid Stretch", "sets": 2, "reps": "3 each"}]}, {"name": "Hip Release", "sequence": 2, "exercises": [{"name": "Hip Flexor Stretch", "sets": 2, "reps": "30 sec each"}, {"name": "Figure 4 Stretch", "sets": 2, "reps": "30 sec each"}, {"name": "Pelvic Circles", "sets": 2, "reps": "5 each direction"}]}, {"name": "Back Strengthen", "sequence": 3, "exercises": [{"name": "Baby Swan", "sets": 3, "reps": "8"}, {"name": "Swimming Prep", "sets": 2, "reps": "10 each"}, {"name": "Bird Dog", "sets": 2, "reps": "8 each"}]}, {"name": "Core", "sequence": 4, "exercises": [{"name": "Dead Bug", "sets": 2, "reps": "10 each"}, {"name": "Pelvic Curl", "sets": 2, "reps": "8"}]}]}',
ARRAY['pilates', 'beginner', 'desk-worker', 'posture', 'office'], 'pilates_desk_workers.md'),

('011a0001-0020-4000-8000-000000000020', 'Pilates Stretch & Restore', 'Gentle stretching session using Pilates principles. Perfect for recovery days.', 'mobility', 'beginner', 30,
'{"blocks": [{"name": "Breathing", "sequence": 0, "exercises": [{"name": "Diaphragmatic Breathing", "duration": "3 min"}, {"name": "Rib Cage Breathing", "sets": 2, "reps": "10 breaths"}]}, {"name": "Spine", "sequence": 1, "exercises": [{"name": "Knee Folds", "sets": 2, "reps": "8 each"}, {"name": "Spinal Twist", "sets": 2, "reps": "1 min each"}, {"name": "Cat Cow", "sets": 2, "reps": "8"}]}, {"name": "Hips", "sequence": 2, "exercises": [{"name": "Figure 4 Stretch", "sets": 2, "reps": "1 min each"}, {"name": "Happy Baby", "duration": "2 min"}, {"name": "Frog Stretch", "duration": "2 min"}]}, {"name": "Back", "sequence": 3, "exercises": [{"name": "Child Pose", "duration": "2 min"}, {"name": "Thread the Needle", "sets": 2, "reps": "30 sec each"}, {"name": "Seal Stretch", "duration": "1 min"}]}, {"name": "Full Body", "sequence": 4, "exercises": [{"name": "Mermaid", "sets": 2, "reps": "30 sec each"}, {"name": "Saw Stretch", "sets": 2, "reps": "30 sec each"}, {"name": "Roll Down", "sets": 3, "reps": "slow"}]}]}',
ARRAY['pilates', 'beginner', 'stretch', 'restore', 'recovery'], 'pilates_stretch_restore.md'),

('011a0001-0021-4000-8000-000000000021', '10-Minute Pilates Express', 'Quick but effective Pilates session. Hit all the essentials in minimal time.', 'mobility', 'intermediate', 10,
'{"blocks": [{"name": "Core Blast", "sequence": 0, "exercises": [{"name": "The Hundred", "sets": 1, "reps": "100 pumps"}, {"name": "Roll Up", "sets": 1, "reps": "5"}]}, {"name": "Ab Series", "sequence": 1, "exercises": [{"name": "Single Leg Stretch", "sets": 1, "reps": "10 each"}, {"name": "Double Leg Stretch", "sets": 1, "reps": "8"}, {"name": "Criss Cross", "sets": 1, "reps": "10 each"}]}, {"name": "Back & Finish", "sequence": 2, "exercises": [{"name": "Swimming", "sets": 1, "reps": "20 counts"}, {"name": "Push Up", "sets": 1, "reps": "5"}, {"name": "Roll Down", "sets": 1, "reps": "3"}]}]}',
ARRAY['pilates', 'intermediate', 'quick', 'express', '10-minute'], 'pilates_10_minute_express.md'),

('011a0001-0022-4000-8000-000000000022', 'Pilates Wunda Chair Intro', 'Introduction to the Wunda Chair apparatus. Challenging stability and strength work.', 'mobility', 'intermediate', 40,
'{"blocks": [{"name": "Seated", "sequence": 0, "exercises": [{"name": "Pumping One Leg", "sets": 2, "reps": "10 each"}, {"name": "Pumping Both Legs", "sets": 2, "reps": "10"}, {"name": "Spine Stretch", "sets": 2, "reps": "5"}]}, {"name": "Standing", "sequence": 1, "exercises": [{"name": "Mountain Climber", "sets": 2, "reps": "8 each"}, {"name": "Going Up Front", "sets": 2, "reps": "5 each"}, {"name": "Going Up Side", "sets": 2, "reps": "5 each"}]}, {"name": "Prone", "sequence": 2, "exercises": [{"name": "Swan on Chair", "sets": 2, "reps": "5"}, {"name": "Horseback", "sets": 2, "reps": "5"}]}, {"name": "Supine", "sequence": 3, "exercises": [{"name": "Leg Pumps Supine", "sets": 2, "reps": "10"}, {"name": "Frog on Chair", "sets": 2, "reps": "8"}]}, {"name": "Challenge", "sequence": 4, "exercises": [{"name": "Tendon Stretch", "sets": 2, "reps": "5"}, {"name": "Pike", "sets": 2, "reps": "5"}]}]}',
ARRAY['pilates', 'intermediate', 'wunda-chair', 'apparatus', 'studio'], 'pilates_wunda_chair.md'),

('011a0001-0023-4000-8000-000000000023', 'Pilates Tower/Cadillac Basics', 'Learn the fundamentals of the Cadillac/Tower apparatus.', 'mobility', 'intermediate', 45,
'{"blocks": [{"name": "Leg Springs", "sequence": 0, "exercises": [{"name": "Leg Springs - Frog", "sets": 2, "reps": "10"}, {"name": "Leg Springs - Circles", "sets": 2, "reps": "5 each"}, {"name": "Leg Springs - Walking", "sets": 2, "reps": "20"}]}, {"name": "Arm Springs", "sequence": 1, "exercises": [{"name": "Arm Springs - Supine", "sets": 2, "reps": "10"}, {"name": "Arm Springs - Sitting", "sets": 2, "reps": "10"}, {"name": "Chest Expansion", "sets": 2, "reps": "5"}]}, {"name": "Push Through Bar", "sequence": 2, "exercises": [{"name": "Push Through - Supine", "sets": 2, "reps": "5"}, {"name": "Push Through - Tower", "sets": 2, "reps": "5"}, {"name": "Teaser with Bar", "sets": 2, "reps": "3"}]}, {"name": "Roll Back Bar", "sequence": 3, "exercises": [{"name": "Roll Back", "sets": 2, "reps": "5"}, {"name": "Roll Back with Twist", "sets": 2, "reps": "3 each"}]}, {"name": "Stretch", "sequence": 4, "exercises": [{"name": "Hanging", "duration": "1 min"}, {"name": "Monkey", "sets": 2, "reps": "5"}]}]}',
ARRAY['pilates', 'intermediate', 'cadillac', 'tower', 'apparatus'], 'pilates_tower_basics.md'),

('011a0001-0024-4000-8000-000000000024', 'Pilates Barre Fusion', 'Combine Pilates core work with barre-inspired leg exercises.', 'mobility', 'intermediate', 40,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Plie Pulses", "sets": 3, "reps": "20"}, {"name": "Releve Balance", "sets": 2, "reps": "30 sec"}]}, {"name": "Barre Legs", "sequence": 1, "exercises": [{"name": "Arabesque Lifts", "sets": 2, "reps": "15 each"}, {"name": "Attitude Lifts", "sets": 2, "reps": "15 each"}, {"name": "Inner Thigh Lifts at Barre", "sets": 2, "reps": "15 each"}, {"name": "Standing Leg Circles", "sets": 2, "reps": "10 each direction"}]}, {"name": "Pilates Core", "sequence": 2, "exercises": [{"name": "The Hundred", "sets": 1, "reps": "100 pumps"}, {"name": "Roll Up", "sets": 1, "reps": "5"}, {"name": "Ab Series of Five", "sets": 1, "reps": "10 each exercise"}]}, {"name": "Mat Leg Work", "sequence": 3, "exercises": [{"name": "Side Leg Series", "sets": 1, "reps": "complete each side"}, {"name": "Inner Thigh Lifts", "sets": 2, "reps": "15 each"}, {"name": "Clam", "sets": 2, "reps": "15 each"}]}, {"name": "Cool Down", "sequence": 4, "exercises": [{"name": "Mermaid", "sets": 2, "reps": "3 each"}, {"name": "Straddle Stretch", "duration": "2 min"}]}]}',
ARRAY['pilates', 'intermediate', 'barre', 'fusion', 'legs'], 'pilates_barre_fusion.md'),

('011a0001-0025-4000-8000-000000000025', 'Pilates for Swimmers', 'Build core stability, shoulder mobility, and streamlined body positioning for swimming.', 'mobility', 'intermediate', 35,
'{"blocks": [{"name": "Shoulder Prep", "sequence": 0, "exercises": [{"name": "Arm Circles", "sets": 2, "reps": "10 each direction"}, {"name": "Chest Expansion", "sets": 2, "reps": "8"}, {"name": "Shoulder Stretch", "sets": 2, "reps": "30 sec each"}]}, {"name": "Core Stability", "sequence": 1, "exercises": [{"name": "Dead Bug", "sets": 3, "reps": "10 each"}, {"name": "Swimming", "sets": 3, "reps": "30 counts"}, {"name": "Plank Hold", "sets": 3, "reps": "30 sec"}]}, {"name": "Back Extension", "sequence": 2, "exercises": [{"name": "Swan", "sets": 3, "reps": "5"}, {"name": "Single Leg Kick", "sets": 2, "reps": "8 each"}, {"name": "Double Leg Kick", "sets": 2, "reps": "5 each side"}]}, {"name": "Hip Work", "sequence": 3, "exercises": [{"name": "Leg Circles", "sets": 2, "reps": "5 each direction"}, {"name": "Side Kick Series", "sets": 1, "reps": "complete each side"}, {"name": "Shoulder Bridge", "sets": 2, "reps": "5 each leg"}]}, {"name": "Streamline", "sequence": 4, "exercises": [{"name": "Roll Up", "sets": 2, "reps": "5"}, {"name": "Spine Stretch Forward", "sets": 2, "reps": "5"}, {"name": "Mermaid", "sets": 2, "reps": "3 each"}]}]}',
ARRAY['pilates', 'intermediate', 'swimming', 'athletic', 'shoulder'], 'pilates_for_swimmers.md');
