-- Seed Bootcamp workout templates
-- Bodyweight only, mat-based, no equipment required

INSERT INTO system_workout_templates (id, name, description, category, difficulty, duration_minutes, exercises, tags, source_file) VALUES

-- CLASSIC BOOTCAMP
('b00a0001-0001-4000-8000-000000000001', 'Classic Military Bootcamp', 'Old school military-style PT. Push-ups, sit-ups, squats, and running. No excuses.', 'full_body', 'intermediate', 40,
'{"blocks": [{"name": "Formation", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "2 min"}, {"name": "High Knees", "duration": "1 min"}, {"name": "Butt Kicks", "duration": "1 min"}]}, {"name": "Push-Up Drill", "sequence": 1, "exercises": [{"name": "Standard Push-Ups", "sets": 3, "reps": "20"}, {"name": "Wide Push-Ups", "sets": 2, "reps": "15"}, {"name": "Diamond Push-Ups", "sets": 2, "reps": "12"}, {"name": "Incline Push-Ups", "sets": 2, "reps": "15"}]}, {"name": "Core Drill", "sequence": 2, "exercises": [{"name": "Sit-Ups", "sets": 3, "reps": "25"}, {"name": "Flutter Kicks", "sets": 3, "reps": "30"}, {"name": "Leg Raises", "sets": 3, "reps": "15"}, {"name": "Plank Hold", "sets": 2, "reps": "45 sec"}]}, {"name": "Lower Body Drill", "sequence": 3, "exercises": [{"name": "Bodyweight Squats", "sets": 3, "reps": "25"}, {"name": "Lunges", "sets": 3, "reps": "20 each"}, {"name": "Jump Squats", "sets": 2, "reps": "15"}]}, {"name": "Cardio Finish", "sequence": 4, "exercises": [{"name": "Burpees", "sets": 3, "reps": "10"}, {"name": "Mountain Climbers", "sets": 3, "reps": "30"}, {"name": "High Knees Sprint", "duration": "1 min"}]}, {"name": "Cool Down", "sequence": 5, "exercises": [{"name": "March in Place", "duration": "2 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['bootcamp', 'intermediate', 'military', 'bodyweight', 'no-equipment'], 'classic_bootcamp.md'),

('b00a0001-0002-4000-8000-000000000002', 'Total Body Bootcamp Blast', '30-minute full body bootcamp. Hit every muscle group with bodyweight only.', 'full_body', 'intermediate', 30,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "March in Place", "duration": "1 min"}, {"name": "Arm Circles", "duration": "1 min"}, {"name": "Leg Swings", "sets": 2, "reps": "10 each"}]}, {"name": "Circuit 1 - 2 Rounds", "sequence": 1, "exercises": [{"name": "Squats", "reps": "15"}, {"name": "Push-Ups", "reps": "12"}, {"name": "Reverse Lunges", "reps": "12 each"}, {"name": "Plank", "duration": "30 sec"}, {"name": "Rest", "duration": "30 sec"}]}, {"name": "Circuit 2 - 2 Rounds", "sequence": 2, "exercises": [{"name": "Jump Squats", "reps": "12"}, {"name": "Pike Push-Ups", "reps": "10"}, {"name": "Glute Bridges", "reps": "15"}, {"name": "Bicycle Crunches", "reps": "20 each"}, {"name": "Rest", "duration": "30 sec"}]}, {"name": "Finisher", "sequence": 3, "exercises": [{"name": "Burpees", "reps": "10"}, {"name": "High Knees", "duration": "30 sec"}, {"name": "Burpees", "reps": "10"}]}, {"name": "Cool Down", "sequence": 4, "exercises": [{"name": "Full Body Stretch", "duration": "3 min"}]}]}',
ARRAY['bootcamp', 'intermediate', 'full-body', 'bodyweight', '30-minute'], 'total_body_bootcamp.md'),

('b00a0001-0003-4000-8000-000000000003', 'Sunrise Bootcamp', 'Energizing morning bootcamp to start your day strong. Mat only.', 'full_body', 'beginner', 25,
'{"blocks": [{"name": "Wake Up", "sequence": 0, "exercises": [{"name": "Cat Cow", "sets": 2, "reps": "8"}, {"name": "World Greatest Stretch", "sets": 2, "reps": "3 each"}, {"name": "Glute Bridges", "sets": 2, "reps": "10"}]}, {"name": "Activation", "sequence": 1, "exercises": [{"name": "Jumping Jacks", "duration": "1 min"}, {"name": "High Knees", "duration": "30 sec"}, {"name": "Butt Kicks", "duration": "30 sec"}]}, {"name": "Strength Circuit", "sequence": 2, "exercises": [{"name": "Bodyweight Squats", "sets": 3, "reps": "15"}, {"name": "Push-Ups (any variation)", "sets": 3, "reps": "10"}, {"name": "Reverse Lunges", "sets": 2, "reps": "10 each"}, {"name": "Superman Hold", "sets": 3, "reps": "10"}]}, {"name": "Core", "sequence": 3, "exercises": [{"name": "Dead Bug", "sets": 2, "reps": "10 each"}, {"name": "Plank", "sets": 2, "reps": "30 sec"}]}, {"name": "Energize", "sequence": 4, "exercises": [{"name": "Jumping Jacks", "duration": "1 min"}, {"name": "Deep Breathing", "duration": "1 min"}]}]}',
ARRAY['bootcamp', 'beginner', 'morning', 'bodyweight', 'energizing'], 'sunrise_bootcamp.md'),

-- CARDIO-FOCUSED BOOTCAMP
('b00a0001-0004-4000-8000-000000000004', 'Cardio Killer Bootcamp', 'Maximum heart rate, minimum equipment. Pure cardio bootcamp torture.', 'cardio', 'advanced', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jog in Place", "duration": "2 min"}, {"name": "High Knees", "duration": "1 min"}, {"name": "Butt Kicks", "duration": "1 min"}]}, {"name": "Cardio Blast 1", "sequence": 1, "exercises": [{"name": "Burpees", "duration": "1 min"}, {"name": "Rest", "duration": "20 sec"}, {"name": "Mountain Climbers", "duration": "1 min"}, {"name": "Rest", "duration": "20 sec"}, {"name": "Jump Squats", "duration": "1 min"}, {"name": "Rest", "duration": "20 sec"}]}, {"name": "Active Recovery", "sequence": 2, "exercises": [{"name": "March in Place", "duration": "1 min"}]}, {"name": "Cardio Blast 2", "sequence": 3, "exercises": [{"name": "High Knees Sprint", "duration": "1 min"}, {"name": "Rest", "duration": "20 sec"}, {"name": "Plank Jacks", "duration": "1 min"}, {"name": "Rest", "duration": "20 sec"}, {"name": "Skater Hops", "duration": "1 min"}, {"name": "Rest", "duration": "20 sec"}]}, {"name": "Active Recovery", "sequence": 4, "exercises": [{"name": "Walk in Place", "duration": "1 min"}]}, {"name": "Cardio Blast 3", "sequence": 5, "exercises": [{"name": "Tuck Jumps", "duration": "45 sec"}, {"name": "Rest", "duration": "15 sec"}, {"name": "Burpees", "duration": "45 sec"}, {"name": "Rest", "duration": "15 sec"}, {"name": "Speed Skaters", "duration": "45 sec"}]}, {"name": "Cool Down", "sequence": 6, "exercises": [{"name": "Walk", "duration": "2 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['bootcamp', 'advanced', 'cardio', 'bodyweight', 'intense'], 'cardio_killer_bootcamp.md'),

('b00a0001-0005-4000-8000-000000000005', 'Jump Training Bootcamp', 'Plyometric-focused bootcamp. Explosive power using just your bodyweight.', 'cardio', 'advanced', 30,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "2 min"}, {"name": "Bodyweight Squats", "sets": 2, "reps": "10"}, {"name": "Leg Swings", "sets": 2, "reps": "10 each"}]}, {"name": "Jump Prep", "sequence": 1, "exercises": [{"name": "Pogo Hops", "sets": 2, "reps": "20"}, {"name": "Squat Pulses", "sets": 2, "reps": "15"}]}, {"name": "Plyometric Circuit - 3 Rounds", "sequence": 2, "exercises": [{"name": "Jump Squats", "reps": "10"}, {"name": "Split Squat Jumps", "reps": "8 each"}, {"name": "Broad Jumps", "reps": "6"}, {"name": "Tuck Jumps", "reps": "8"}, {"name": "Rest", "duration": "60 sec"}]}, {"name": "Lateral Power", "sequence": 3, "exercises": [{"name": "Lateral Bounds", "sets": 2, "reps": "8 each"}, {"name": "Skater Hops", "sets": 2, "reps": "10 each"}]}, {"name": "Cool Down", "sequence": 4, "exercises": [{"name": "Walk", "duration": "2 min"}, {"name": "Quad Stretch", "duration": "1 min each"}, {"name": "Calf Stretch", "duration": "1 min each"}]}]}',
ARRAY['bootcamp', 'advanced', 'plyometric', 'jump', 'explosive'], 'jump_bootcamp.md'),

-- STRENGTH-FOCUSED BOOTCAMP
('b00a0001-0006-4000-8000-000000000006', 'Bodyweight Strength Bootcamp', 'Build real strength without weights. Progressive bodyweight training.', 'strength', 'intermediate', 40,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Arm Circles", "sets": 2, "reps": "10 each direction"}, {"name": "Leg Swings", "sets": 2, "reps": "10 each"}, {"name": "Cat Cow", "sets": 2, "reps": "8"}]}, {"name": "Push Strength", "sequence": 1, "exercises": [{"name": "Standard Push-Ups", "sets": 4, "reps": "12-15"}, {"name": "Pike Push-Ups", "sets": 3, "reps": "10"}, {"name": "Decline Push-Ups", "sets": 3, "reps": "10"}, {"name": "Diamond Push-Ups", "sets": 2, "reps": "8"}]}, {"name": "Pull/Back Strength", "sequence": 2, "exercises": [{"name": "Superman Raises", "sets": 4, "reps": "12"}, {"name": "Prone Y-T-W", "sets": 3, "reps": "8 each"}, {"name": "Reverse Snow Angels", "sets": 3, "reps": "10"}]}, {"name": "Lower Body Strength", "sequence": 3, "exercises": [{"name": "Bulgarian Split Squat", "sets": 3, "reps": "10 each"}, {"name": "Single Leg Glute Bridge", "sets": 3, "reps": "10 each"}, {"name": "Pistol Squat Negatives", "sets": 3, "reps": "5 each"}, {"name": "Wall Sit", "sets": 2, "reps": "45 sec"}]}, {"name": "Core Strength", "sequence": 4, "exercises": [{"name": "Hollow Body Hold", "sets": 3, "reps": "30 sec"}, {"name": "Side Plank", "sets": 2, "reps": "30 sec each"}, {"name": "V-Ups", "sets": 3, "reps": "12"}]}, {"name": "Cool Down", "sequence": 5, "exercises": [{"name": "Stretch", "duration": "5 min"}]}]}',
ARRAY['bootcamp', 'intermediate', 'strength', 'bodyweight', 'progressive'], 'strength_bootcamp.md'),

('b00a0001-0007-4000-8000-000000000007', 'Upper Body Bootcamp', 'Destroy your upper body with zero equipment. Push, pull, and hold.', 'upper', 'intermediate', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Arm Circles", "duration": "1 min"}, {"name": "Shoulder Rolls", "sets": 2, "reps": "10 each"}, {"name": "Push-Up to Downward Dog", "sets": 2, "reps": "5"}]}, {"name": "Push Circuit - 3 Rounds", "sequence": 1, "exercises": [{"name": "Push-Ups", "reps": "15"}, {"name": "Pike Push-Ups", "reps": "10"}, {"name": "Tricep Dips (on floor)", "reps": "12"}, {"name": "Rest", "duration": "45 sec"}]}, {"name": "Pull/Back Circuit - 3 Rounds", "sequence": 2, "exercises": [{"name": "Superman Hold", "reps": "12"}, {"name": "Prone Y Raises", "reps": "10"}, {"name": "Prone T Raises", "reps": "10"}, {"name": "Prone W Raises", "reps": "10"}, {"name": "Rest", "duration": "45 sec"}]}, {"name": "Isometric Holds", "sequence": 3, "exercises": [{"name": "Push-Up Hold (bottom)", "sets": 2, "reps": "20 sec"}, {"name": "Plank", "sets": 2, "reps": "45 sec"}, {"name": "Side Plank", "sets": 2, "reps": "30 sec each"}]}, {"name": "Cool Down", "sequence": 4, "exercises": [{"name": "Chest Stretch", "duration": "1 min"}, {"name": "Tricep Stretch", "duration": "1 min each"}, {"name": "Shoulder Stretch", "duration": "1 min each"}]}]}',
ARRAY['bootcamp', 'intermediate', 'upper-body', 'push', 'pull'], 'upper_body_bootcamp.md'),

('b00a0001-0008-4000-8000-000000000008', 'Lower Body Bootcamp Burn', 'Legs and glutes bootcamp. No equipment, all burn.', 'lower', 'intermediate', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "March in Place", "duration": "1 min"}, {"name": "Leg Swings", "sets": 2, "reps": "10 each"}, {"name": "Bodyweight Squats", "sets": 2, "reps": "10"}]}, {"name": "Quad Focus - 3 Rounds", "sequence": 1, "exercises": [{"name": "Squats", "reps": "20"}, {"name": "Squat Pulses", "reps": "20"}, {"name": "Wall Sit", "duration": "30 sec"}, {"name": "Rest", "duration": "30 sec"}]}, {"name": "Glute Focus - 3 Rounds", "sequence": 2, "exercises": [{"name": "Glute Bridges", "reps": "20"}, {"name": "Single Leg Glute Bridge", "reps": "10 each"}, {"name": "Donkey Kicks", "reps": "15 each"}, {"name": "Fire Hydrants", "reps": "15 each"}, {"name": "Rest", "duration": "30 sec"}]}, {"name": "Hamstring Focus - 2 Rounds", "sequence": 3, "exercises": [{"name": "Good Mornings (bodyweight)", "reps": "15"}, {"name": "Single Leg Romanian Deadlift", "reps": "10 each"}, {"name": "Lying Hamstring Curl (heels dig)", "reps": "15"}]}, {"name": "Finisher", "sequence": 4, "exercises": [{"name": "Jump Squats", "reps": "15"}, {"name": "Alternating Lunges", "reps": "20 total"}, {"name": "Squat Hold", "duration": "30 sec"}]}, {"name": "Cool Down", "sequence": 5, "exercises": [{"name": "Quad Stretch", "duration": "1 min each"}, {"name": "Hamstring Stretch", "duration": "1 min each"}, {"name": "Hip Flexor Stretch", "duration": "1 min each"}]}]}',
ARRAY['bootcamp', 'intermediate', 'lower-body', 'legs', 'glutes'], 'lower_body_bootcamp.md'),

-- CORE BOOTCAMP
('b00a0001-0009-4000-8000-000000000009', 'Core Crusher Bootcamp', 'All core, all the time. Mat-based ab destruction.', 'full_body', 'intermediate', 25,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Cat Cow", "sets": 2, "reps": "8"}, {"name": "Dead Bug", "sets": 2, "reps": "8 each"}, {"name": "Plank", "duration": "30 sec"}]}, {"name": "Front Core - 3 Rounds", "sequence": 1, "exercises": [{"name": "Crunches", "reps": "20"}, {"name": "Reverse Crunches", "reps": "15"}, {"name": "V-Ups", "reps": "10"}, {"name": "Plank", "duration": "45 sec"}, {"name": "Rest", "duration": "30 sec"}]}, {"name": "Obliques - 2 Rounds", "sequence": 2, "exercises": [{"name": "Bicycle Crunches", "reps": "20 each"}, {"name": "Side Plank", "duration": "30 sec each"}, {"name": "Russian Twists", "reps": "20 each"}, {"name": "Rest", "duration": "30 sec"}]}, {"name": "Lower Abs", "sequence": 3, "exercises": [{"name": "Leg Raises", "sets": 3, "reps": "15"}, {"name": "Flutter Kicks", "sets": 2, "reps": "30"}, {"name": "Scissor Kicks", "sets": 2, "reps": "20 each"}]}, {"name": "Finisher", "sequence": 4, "exercises": [{"name": "Hollow Body Hold", "duration": "30 sec"}, {"name": "Plank to Push-Up", "reps": "10"}, {"name": "Mountain Climbers", "reps": "30"}]}, {"name": "Cool Down", "sequence": 5, "exercises": [{"name": "Child Pose", "duration": "1 min"}, {"name": "Spinal Twist", "sets": 1, "reps": "30 sec each"}]}]}',
ARRAY['bootcamp', 'intermediate', 'core', 'abs', 'mat'], 'core_crusher_bootcamp.md'),

('b00a0001-0010-4000-8000-000000000010', 'Plank Challenge Bootcamp', 'Plank variations for 20 minutes. Core stability bootcamp.', 'full_body', 'intermediate', 20,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Cat Cow", "sets": 2, "reps": "8"}, {"name": "Dead Bug", "sets": 2, "reps": "6 each"}]}, {"name": "Plank Series 1", "sequence": 1, "exercises": [{"name": "Standard Plank", "duration": "45 sec"}, {"name": "Rest", "duration": "15 sec"}, {"name": "Right Side Plank", "duration": "30 sec"}, {"name": "Rest", "duration": "15 sec"}, {"name": "Left Side Plank", "duration": "30 sec"}, {"name": "Rest", "duration": "15 sec"}]}, {"name": "Plank Series 2", "sequence": 2, "exercises": [{"name": "Plank Shoulder Taps", "reps": "20 total"}, {"name": "Rest", "duration": "15 sec"}, {"name": "Plank Jacks", "reps": "15"}, {"name": "Rest", "duration": "15 sec"}, {"name": "Plank Up-Downs", "reps": "10"}, {"name": "Rest", "duration": "15 sec"}]}, {"name": "Plank Series 3", "sequence": 3, "exercises": [{"name": "Reverse Plank", "duration": "30 sec"}, {"name": "Rest", "duration": "15 sec"}, {"name": "Plank with Leg Lift", "reps": "10 each"}, {"name": "Rest", "duration": "15 sec"}, {"name": "Bear Plank Hold", "duration": "30 sec"}]}, {"name": "Finisher", "sequence": 4, "exercises": [{"name": "Plank Hold", "duration": "1 min max effort"}]}, {"name": "Cool Down", "sequence": 5, "exercises": [{"name": "Child Pose", "duration": "1 min"}, {"name": "Cobra Stretch", "duration": "30 sec"}]}]}',
ARRAY['bootcamp', 'intermediate', 'plank', 'core', 'isometric'], 'plank_challenge.md'),

-- CIRCUIT BOOTCAMP
('b00a0001-0011-4000-8000-000000000011', '5-Station Bodyweight Circuit', 'Move through 5 stations, 3 rounds. Classic bootcamp format.', 'full_body', 'intermediate', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "1 min"}, {"name": "High Knees", "duration": "1 min"}, {"name": "Arm Circles", "duration": "1 min"}]}, {"name": "Circuit - 3 Rounds", "sequence": 1, "exercises": [{"name": "Station 1: Squats", "duration": "45 sec"}, {"name": "Station 2: Push-Ups", "duration": "45 sec"}, {"name": "Station 3: Mountain Climbers", "duration": "45 sec"}, {"name": "Station 4: Lunges", "duration": "45 sec"}, {"name": "Station 5: Plank Hold", "duration": "45 sec"}, {"name": "Rest", "duration": "60 sec between rounds"}]}, {"name": "Bonus Round", "sequence": 2, "exercises": [{"name": "Burpees", "duration": "1 min"}, {"name": "Rest", "duration": "30 sec"}, {"name": "High Knees", "duration": "1 min"}]}, {"name": "Cool Down", "sequence": 3, "exercises": [{"name": "March in Place", "duration": "2 min"}, {"name": "Full Body Stretch", "duration": "3 min"}]}]}',
ARRAY['bootcamp', 'intermediate', 'circuit', 'stations', 'full-body'], 'five_station_circuit.md'),

('b00a0001-0012-4000-8000-000000000012', 'Pyramid Bootcamp', 'Ascending and descending rep scheme. Up the ladder, then back down.', 'full_body', 'intermediate', 30,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "2 min"}, {"name": "Bodyweight Squats", "sets": 1, "reps": "10"}]}, {"name": "Ascending Pyramid", "sequence": 1, "exercises": [{"name": "Round 1: 2 Push-Ups, 4 Squats, 6 Sit-Ups", "notes": "2-4-6"}, {"name": "Round 2: 4 Push-Ups, 8 Squats, 12 Sit-Ups", "notes": "4-8-12"}, {"name": "Round 3: 6 Push-Ups, 12 Squats, 18 Sit-Ups", "notes": "6-12-18"}, {"name": "Round 4: 8 Push-Ups, 16 Squats, 24 Sit-Ups", "notes": "8-16-24"}, {"name": "Round 5: 10 Push-Ups, 20 Squats, 30 Sit-Ups", "notes": "10-20-30"}]}, {"name": "Descending Pyramid", "sequence": 2, "exercises": [{"name": "Round 6: 8 Push-Ups, 16 Squats, 24 Sit-Ups", "notes": "8-16-24"}, {"name": "Round 7: 6 Push-Ups, 12 Squats, 18 Sit-Ups", "notes": "6-12-18"}, {"name": "Round 8: 4 Push-Ups, 8 Squats, 12 Sit-Ups", "notes": "4-8-12"}, {"name": "Round 9: 2 Push-Ups, 4 Squats, 6 Sit-Ups", "notes": "2-4-6"}]}, {"name": "Cool Down", "sequence": 3, "exercises": [{"name": "Walk", "duration": "2 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['bootcamp', 'intermediate', 'pyramid', 'progressive', 'bodyweight'], 'pyramid_bootcamp.md'),

-- TIMED BOOTCAMP
('b00a0001-0013-4000-8000-000000000013', '20-Minute Express Bootcamp', 'Short on time, not on intensity. Full workout in 20 minutes.', 'full_body', 'intermediate', 20,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "1 min"}, {"name": "High Knees", "duration": "30 sec"}, {"name": "Butt Kicks", "duration": "30 sec"}]}, {"name": "Block 1", "sequence": 1, "exercises": [{"name": "Squats", "duration": "45 sec"}, {"name": "Push-Ups", "duration": "45 sec"}, {"name": "Mountain Climbers", "duration": "45 sec"}, {"name": "Rest", "duration": "30 sec"}]}, {"name": "Block 2", "sequence": 2, "exercises": [{"name": "Lunges", "duration": "45 sec"}, {"name": "Plank", "duration": "45 sec"}, {"name": "Burpees", "duration": "45 sec"}, {"name": "Rest", "duration": "30 sec"}]}, {"name": "Block 3", "sequence": 3, "exercises": [{"name": "Jump Squats", "duration": "45 sec"}, {"name": "Sit-Ups", "duration": "45 sec"}, {"name": "High Knees", "duration": "45 sec"}]}, {"name": "Cool Down", "sequence": 4, "exercises": [{"name": "March in Place", "duration": "1 min"}, {"name": "Quick Stretch", "duration": "2 min"}]}]}',
ARRAY['bootcamp', 'intermediate', 'express', '20-minute', 'quick'], 'express_bootcamp.md'),

('b00a0001-0014-4000-8000-000000000014', '45-Minute Complete Bootcamp', 'Comprehensive bootcamp covering all fitness components. The full experience.', 'full_body', 'intermediate', 45,
'{"blocks": [{"name": "Dynamic Warm Up", "sequence": 0, "exercises": [{"name": "March in Place", "duration": "1 min"}, {"name": "Jumping Jacks", "duration": "1 min"}, {"name": "Leg Swings", "sets": 2, "reps": "10 each"}, {"name": "Arm Circles", "duration": "1 min"}, {"name": "Bodyweight Squats", "sets": 1, "reps": "10"}]}, {"name": "Strength Block", "sequence": 1, "exercises": [{"name": "Push-Ups", "sets": 3, "reps": "15"}, {"name": "Squats", "sets": 3, "reps": "20"}, {"name": "Lunges", "sets": 3, "reps": "12 each"}, {"name": "Glute Bridges", "sets": 3, "reps": "15"}, {"name": "Pike Push-Ups", "sets": 2, "reps": "10"}]}, {"name": "Core Block", "sequence": 2, "exercises": [{"name": "Plank", "sets": 3, "reps": "45 sec"}, {"name": "Bicycle Crunches", "sets": 3, "reps": "20 each"}, {"name": "Leg Raises", "sets": 3, "reps": "12"}, {"name": "Side Plank", "sets": 2, "reps": "30 sec each"}]}, {"name": "Cardio Block", "sequence": 3, "exercises": [{"name": "Burpees", "duration": "1 min"}, {"name": "Rest", "duration": "30 sec"}, {"name": "Mountain Climbers", "duration": "1 min"}, {"name": "Rest", "duration": "30 sec"}, {"name": "High Knees", "duration": "1 min"}, {"name": "Rest", "duration": "30 sec"}, {"name": "Jump Squats", "duration": "1 min"}]}, {"name": "Finisher", "sequence": 4, "exercises": [{"name": "Wall Sit", "duration": "45 sec"}, {"name": "Push-Up Hold", "duration": "30 sec"}, {"name": "Hollow Body Hold", "duration": "30 sec"}]}, {"name": "Cool Down", "sequence": 5, "exercises": [{"name": "Walk in Place", "duration": "2 min"}, {"name": "Full Body Stretch", "duration": "5 min"}]}]}',
ARRAY['bootcamp', 'intermediate', 'complete', '45-minute', 'comprehensive'], 'complete_bootcamp.md'),

-- BEGINNER BOOTCAMP
('b00a0001-0015-4000-8000-000000000015', 'Beginner Bootcamp Basics', 'Introduction to bootcamp training. Modified exercises, longer rest.', 'full_body', 'beginner', 30,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "March in Place", "duration": "2 min"}, {"name": "Arm Circles", "duration": "1 min"}, {"name": "Leg Swings", "sets": 2, "reps": "8 each"}]}, {"name": "Circuit - 2 Rounds", "sequence": 1, "exercises": [{"name": "Wall or Incline Push-Ups", "reps": "10"}, {"name": "Bodyweight Squats", "reps": "12"}, {"name": "Reverse Lunges", "reps": "8 each"}, {"name": "Glute Bridges", "reps": "12"}, {"name": "Bird Dog", "reps": "8 each"}, {"name": "Rest", "duration": "60 sec"}]}, {"name": "Core", "sequence": 2, "exercises": [{"name": "Dead Bug", "sets": 2, "reps": "8 each"}, {"name": "Modified Plank (knees)", "sets": 2, "reps": "20 sec"}]}, {"name": "Cardio Light", "sequence": 3, "exercises": [{"name": "Marching High Knees", "duration": "1 min"}, {"name": "Step Jacks (no jump)", "duration": "1 min"}]}, {"name": "Cool Down", "sequence": 4, "exercises": [{"name": "Walk in Place", "duration": "2 min"}, {"name": "Gentle Stretch", "duration": "5 min"}]}]}',
ARRAY['bootcamp', 'beginner', 'intro', 'modified', 'gentle'], 'beginner_bootcamp.md'),

('b00a0001-0016-4000-8000-000000000016', 'Low Impact Bootcamp', 'Bootcamp intensity without the jumping. Joint-friendly bodyweight training.', 'full_body', 'beginner', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "March in Place", "duration": "2 min"}, {"name": "Arm Swings", "duration": "1 min"}, {"name": "Hip Circles", "sets": 2, "reps": "10 each direction"}]}, {"name": "Strength Circuit - 3 Rounds", "sequence": 1, "exercises": [{"name": "Slow Squats", "reps": "15"}, {"name": "Push-Ups (any level)", "reps": "10"}, {"name": "Stationary Lunges", "reps": "10 each"}, {"name": "Superman", "reps": "12"}, {"name": "Rest", "duration": "45 sec"}]}, {"name": "Core", "sequence": 2, "exercises": [{"name": "Dead Bug", "sets": 3, "reps": "10 each"}, {"name": "Bird Dog", "sets": 3, "reps": "8 each"}, {"name": "Plank", "sets": 2, "reps": "30 sec"}]}, {"name": "Low Impact Cardio", "sequence": 3, "exercises": [{"name": "Fast March", "duration": "1 min"}, {"name": "Lateral Steps", "duration": "1 min"}, {"name": "Step Touch", "duration": "1 min"}, {"name": "Knee Drives (no hop)", "duration": "1 min"}]}, {"name": "Cool Down", "sequence": 4, "exercises": [{"name": "Walk", "duration": "2 min"}, {"name": "Stretch", "duration": "4 min"}]}]}',
ARRAY['bootcamp', 'beginner', 'low-impact', 'joint-friendly', 'no-jumping'], 'low_impact_bootcamp.md'),

-- CHALLENGE BOOTCAMP
('b00a0001-0017-4000-8000-000000000017', '100 Rep Challenge', '100 reps each of 5 exercises. For time. How fast can you go?', 'full_body', 'advanced', 35,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "2 min"}, {"name": "Bodyweight Squats", "sets": 1, "reps": "10"}, {"name": "Push-Ups", "sets": 1, "reps": "10"}]}, {"name": "100 Rep Challenge - For Time", "sequence": 1, "exercises": [{"name": "Squats", "reps": "100"}, {"name": "Push-Ups", "reps": "100"}, {"name": "Sit-Ups", "reps": "100"}, {"name": "Lunges (total steps)", "reps": "100"}, {"name": "Burpees", "reps": "100"}, {"name": "Record Your Time", "notes": "Break up sets as needed"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Walk", "duration": "3 min"}, {"name": "Full Body Stretch", "duration": "5 min"}]}]}',
ARRAY['bootcamp', 'advanced', 'challenge', '100-rep', 'for-time'], '100_rep_challenge.md'),

('b00a0001-0018-4000-8000-000000000018', 'Burpee Bootcamp', 'The exercise everyone loves to hate. Burpee variations and torture.', 'cardio', 'advanced', 25,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "2 min"}, {"name": "High Knees", "duration": "1 min"}, {"name": "Squats", "sets": 1, "reps": "10"}]}, {"name": "Burpee Ladder", "sequence": 1, "exercises": [{"name": "1 Burpee, Rest", "notes": "10 sec rest"}, {"name": "2 Burpees, Rest", "notes": "10 sec rest"}, {"name": "3 Burpees, Rest", "notes": "10 sec rest"}, {"name": "Continue to 10", "notes": "Then back down to 1"}]}, {"name": "Burpee Variations - 2 Rounds", "sequence": 2, "exercises": [{"name": "Standard Burpee", "reps": "5"}, {"name": "Burpee with Tuck Jump", "reps": "5"}, {"name": "Burpee with Push-Up", "reps": "5"}, {"name": "Lateral Burpee", "reps": "5 each side"}, {"name": "Rest", "duration": "60 sec"}]}, {"name": "Finisher", "sequence": 3, "exercises": [{"name": "Max Burpees in 2 Minutes", "duration": "2 min"}]}, {"name": "Cool Down", "sequence": 4, "exercises": [{"name": "Walk", "duration": "2 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['bootcamp', 'advanced', 'burpee', 'cardio', 'torture'], 'burpee_bootcamp.md'),

-- PARTNER BOOTCAMP (can be done solo too)
('b00a0001-0019-4000-8000-000000000019', 'Partner Bootcamp', 'Designed for two, but works solo too. Work-rest intervals with a partner.', 'full_body', 'intermediate', 35,
'{"blocks": [{"name": "Warm Up Together", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "2 min"}, {"name": "High Fives (or Solo High Knees)", "duration": "1 min"}]}, {"name": "Partner Work-Rest - 3 Rounds", "sequence": 1, "exercises": [{"name": "Partner A: Max Squats while Partner B: Plank Hold", "duration": "1 min"}, {"name": "Switch Roles", "duration": "1 min"}, {"name": "Partner A: Max Push-Ups while Partner B: Wall Sit", "duration": "1 min"}, {"name": "Switch Roles", "duration": "1 min"}, {"name": "Partner A: Max Lunges while Partner B: Superman Hold", "duration": "1 min"}, {"name": "Switch Roles", "duration": "1 min"}, {"name": "Rest Together", "duration": "1 min"}]}, {"name": "Sync Work - 2 Rounds", "sequence": 2, "exercises": [{"name": "Burpees (together)", "reps": "10"}, {"name": "Sit-Ups (together)", "reps": "20"}, {"name": "Jump Squats (together)", "reps": "15"}]}, {"name": "Cool Down", "sequence": 3, "exercises": [{"name": "Partner Stretch or Solo Stretch", "duration": "5 min"}]}]}',
ARRAY['bootcamp', 'intermediate', 'partner', 'work-rest', 'social'], 'partner_bootcamp.md'),

-- OUTDOOR BOOTCAMP
('b00a0001-0020-4000-8000-000000000020', 'Park Bootcamp', 'Take it outside. Bodyweight exercises perfect for the park or backyard.', 'full_body', 'intermediate', 40,
'{"blocks": [{"name": "Warm Up Run", "sequence": 0, "exercises": [{"name": "Light Jog", "duration": "3 min"}, {"name": "Dynamic Stretches", "duration": "2 min"}]}, {"name": "Upper Body Station", "sequence": 1, "exercises": [{"name": "Push-Ups", "sets": 3, "reps": "15"}, {"name": "Tricep Dips (on bench)", "sets": 3, "reps": "12"}, {"name": "Incline Push-Ups (on bench)", "sets": 3, "reps": "12"}]}, {"name": "Lower Body Station", "sequence": 2, "exercises": [{"name": "Step-Ups (on bench)", "sets": 3, "reps": "12 each"}, {"name": "Bulgarian Split Squat", "sets": 3, "reps": "10 each"}, {"name": "Box Jumps (or Step-Ups)", "sets": 3, "reps": "10"}]}, {"name": "Cardio Station", "sequence": 3, "exercises": [{"name": "Sprint 50 yards", "sets": 4, "notes": "Walk back recovery"}, {"name": "Lateral Shuffles", "sets": 2, "reps": "30 yards each direction"}]}, {"name": "Core Station", "sequence": 4, "exercises": [{"name": "Plank", "sets": 3, "reps": "45 sec"}, {"name": "Leg Raises (on bench)", "sets": 3, "reps": "12"}, {"name": "Russian Twists", "sets": 2, "reps": "20 each"}]}, {"name": "Cool Down Jog", "sequence": 5, "exercises": [{"name": "Light Jog", "duration": "2 min"}, {"name": "Stretch", "duration": "5 min"}]}]}',
ARRAY['bootcamp', 'intermediate', 'outdoor', 'park', 'bench'], 'park_bootcamp.md'),

-- SPORT-SPECIFIC BOOTCAMP
('b00a0001-0021-4000-8000-000000000021', 'Athletic Bootcamp', 'Sports performance bootcamp. Speed, agility, and power without equipment.', 'full_body', 'advanced', 40,
'{"blocks": [{"name": "Dynamic Warm Up", "sequence": 0, "exercises": [{"name": "Jog in Place", "duration": "1 min"}, {"name": "High Knees", "duration": "30 sec"}, {"name": "Butt Kicks", "duration": "30 sec"}, {"name": "Leg Swings", "sets": 2, "reps": "10 each"}, {"name": "Arm Swings", "sets": 2, "reps": "10"}]}, {"name": "Speed & Agility", "sequence": 1, "exercises": [{"name": "Quick Feet", "sets": 3, "reps": "20 sec"}, {"name": "Lateral Shuffles", "sets": 3, "reps": "30 sec"}, {"name": "Carioca", "sets": 2, "reps": "30 sec each direction"}, {"name": "Sprint in Place", "sets": 4, "reps": "15 sec"}]}, {"name": "Power", "sequence": 2, "exercises": [{"name": "Tuck Jumps", "sets": 4, "reps": "8"}, {"name": "Broad Jumps", "sets": 4, "reps": "5"}, {"name": "Split Squat Jumps", "sets": 3, "reps": "8 each"}, {"name": "Lateral Bounds", "sets": 3, "reps": "8 each"}]}, {"name": "Strength Endurance", "sequence": 3, "exercises": [{"name": "Squat Jumps", "sets": 3, "reps": "15"}, {"name": "Clap Push-Ups (or Explosive Push-Ups)", "sets": 3, "reps": "10"}, {"name": "Single Leg Squats (assisted)", "sets": 2, "reps": "6 each"}]}, {"name": "Core for Athletes", "sequence": 4, "exercises": [{"name": "V-Ups", "sets": 3, "reps": "12"}, {"name": "Side Plank with Rotation", "sets": 2, "reps": "8 each"}, {"name": "Superman", "sets": 2, "reps": "12"}]}, {"name": "Cool Down", "sequence": 5, "exercises": [{"name": "Light Jog", "duration": "2 min"}, {"name": "Full Body Stretch", "duration": "5 min"}]}]}',
ARRAY['bootcamp', 'advanced', 'athletic', 'sports', 'performance'], 'athletic_bootcamp.md'),

-- THEMED BOOTCAMP
('b00a0001-0022-4000-8000-000000000022', 'Animal Flow Bootcamp', 'Move like animals. Primal movements meets bootcamp intensity.', 'full_body', 'intermediate', 35,
'{"blocks": [{"name": "Awakening", "sequence": 0, "exercises": [{"name": "Cat Cow", "sets": 2, "reps": "8"}, {"name": "Downward Dog to Cobra", "sets": 2, "reps": "5"}]}, {"name": "Crawling Patterns", "sequence": 1, "exercises": [{"name": "Bear Crawl Forward", "duration": "30 sec"}, {"name": "Bear Crawl Backward", "duration": "30 sec"}, {"name": "Crab Walk", "duration": "30 sec"}, {"name": "Leopard Crawl", "duration": "30 sec"}, {"name": "Rest", "duration": "30 sec"}, {"name": "Repeat 2 Rounds", "notes": ""}]}, {"name": "Animal Movements", "sequence": 2, "exercises": [{"name": "Frog Jumps", "sets": 3, "reps": "10"}, {"name": "Duck Walk", "duration": "30 sec"}, {"name": "Gorilla Shuffle", "sets": 2, "reps": "20 yards"}, {"name": "Inchworm", "sets": 2, "reps": "8"}]}, {"name": "Flow Combinations", "sequence": 3, "exercises": [{"name": "Beast to Crab Reach", "sets": 2, "reps": "8 each"}, {"name": "Scorpion Reach", "sets": 2, "reps": "8 each"}, {"name": "Ape to Frog", "sets": 2, "reps": "8"}]}, {"name": "Cool Down", "sequence": 4, "exercises": [{"name": "Child Pose", "duration": "1 min"}, {"name": "Full Body Stretch", "duration": "4 min"}]}]}',
ARRAY['bootcamp', 'intermediate', 'animal', 'primal', 'flow'], 'animal_flow_bootcamp.md'),

('b00a0001-0023-4000-8000-000000000023', 'Tabata Bootcamp', 'Bootcamp meets Tabata. 20 seconds work, 10 seconds rest, maximum effort.', 'cardio', 'advanced', 25,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "2 min"}, {"name": "High Knees", "duration": "1 min"}]}, {"name": "Tabata 1 - Squats", "sequence": 1, "exercises": [{"name": "Jump Squats or Squats", "sets": 8, "reps": "20 sec on / 10 sec off", "notes": "4 min total"}]}, {"name": "Rest", "sequence": 2, "exercises": [{"name": "Walk", "duration": "1 min"}]}, {"name": "Tabata 2 - Push-Ups", "sequence": 3, "exercises": [{"name": "Push-Ups", "sets": 8, "reps": "20 sec on / 10 sec off", "notes": "4 min total"}]}, {"name": "Rest", "sequence": 4, "exercises": [{"name": "Walk", "duration": "1 min"}]}, {"name": "Tabata 3 - Burpees", "sequence": 5, "exercises": [{"name": "Burpees", "sets": 8, "reps": "20 sec on / 10 sec off", "notes": "4 min total"}]}, {"name": "Rest", "sequence": 6, "exercises": [{"name": "Walk", "duration": "1 min"}]}, {"name": "Tabata 4 - Mountain Climbers", "sequence": 7, "exercises": [{"name": "Mountain Climbers", "sets": 8, "reps": "20 sec on / 10 sec off", "notes": "4 min total"}]}, {"name": "Cool Down", "sequence": 8, "exercises": [{"name": "Walk", "duration": "2 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['bootcamp', 'advanced', 'tabata', 'hiit', 'intense'], 'tabata_bootcamp.md'),

('b00a0001-0024-4000-8000-000000000024', 'Prison Workout Bootcamp', 'No excuses training. Just your bodyweight and a small space.', 'full_body', 'intermediate', 30,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "2 min"}, {"name": "Burpees", "sets": 1, "reps": "10"}]}, {"name": "Deck of Cards Style", "sequence": 1, "exercises": [{"name": "Push-Ups", "sets": 10, "reps": "10", "notes": "100 total, broken up"}, {"name": "Squats", "sets": 10, "reps": "20", "notes": "200 total, broken up"}, {"name": "Sit-Ups", "sets": 5, "reps": "20", "notes": "100 total, broken up"}, {"name": "Burpees", "sets": 5, "reps": "10", "notes": "50 total, broken up"}]}, {"name": "Notes", "sequence": 2, "exercises": [{"name": "Alternate between exercises", "notes": "Minimal rest"}, {"name": "Go at your own pace", "notes": "Complete all reps"}]}, {"name": "Cool Down", "sequence": 3, "exercises": [{"name": "Walk in Place", "duration": "2 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['bootcamp', 'intermediate', 'prison', 'minimal-space', 'no-excuses'], 'prison_bootcamp.md'),

('b00a0001-0025-4000-8000-000000000025', 'Countdown Bootcamp', 'Start at 10, work down to 1. Descending ladder for all exercises.', 'full_body', 'intermediate', 25,
'{"blocks": [{"name": "Warm Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "duration": "2 min"}, {"name": "Bodyweight Squats", "sets": 1, "reps": "10"}]}, {"name": "Countdown Ladder", "sequence": 1, "exercises": [{"name": "Round 10", "notes": "10 Burpees, 10 Push-Ups, 10 Squats, 10 Sit-Ups"}, {"name": "Round 9", "notes": "9 of each exercise"}, {"name": "Round 8", "notes": "8 of each exercise"}, {"name": "Round 7", "notes": "7 of each exercise"}, {"name": "Round 6", "notes": "6 of each exercise"}, {"name": "Round 5", "notes": "5 of each exercise"}, {"name": "Round 4", "notes": "4 of each exercise"}, {"name": "Round 3", "notes": "3 of each exercise"}, {"name": "Round 2", "notes": "2 of each exercise"}, {"name": "Round 1", "notes": "1 of each exercise"}, {"name": "Total Reps", "notes": "55 of each = 220 total reps"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Walk", "duration": "2 min"}, {"name": "Stretch", "duration": "3 min"}]}]}',
ARRAY['bootcamp', 'intermediate', 'countdown', 'ladder', 'descending'], 'countdown_bootcamp.md');
