-- Seed Senior/Low Impact workout templates (25 templates)
-- Focus: Gentle, accessible, balance-focused, chair-based options

INSERT INTO system_workout_templates (id, name, description, category, difficulty, duration_minutes, exercises, tags, source_file) VALUES

-- CHAIR-BASED WORKOUTS (7)
('00c00001-0001-4000-8000-000000000001', 'Seated Full Body', 'Complete workout while seated - great for limited mobility', 'full_body', 'beginner', 30,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Seated March", "sets": 1, "reps": "2 min"}, {"name": "Shoulder Rolls", "sets": 1, "reps": "10 each way"}, {"name": "Neck Turns", "sets": 1, "reps": "5 each side"}]}, {"name": "Upper Body", "sequence": 1, "exercises": [{"name": "Seated Arm Circles", "sets": 2, "reps": "10 each way"}, {"name": "Seated Bicep Curl", "sets": 2, "reps": "10", "notes": "Light dumbbells or water bottles"}, {"name": "Seated Overhead Press", "sets": 2, "reps": "10"}]}, {"name": "Lower Body", "sequence": 2, "exercises": [{"name": "Seated Leg Extension", "sets": 2, "reps": "10 each leg"}, {"name": "Seated Heel Raises", "sets": 2, "reps": "15"}, {"name": "Seated Toe Taps", "sets": 2, "reps": "15"}]}, {"name": "Cool Down", "sequence": 3, "exercises": [{"name": "Deep Breathing", "sets": 1, "reps": "10 breaths"}]}]}'::jsonb,
ARRAY['senior', 'chair', 'low-impact', 'beginner', 'accessible'], 'senior_seated_full_body.md'),

('00c00001-0002-4000-8000-000000000002', 'Chair Yoga', 'Gentle yoga poses modified for chair', 'mobility', 'beginner', 25,
'{"blocks": [{"name": "Centering", "sequence": 0, "exercises": [{"name": "Seated Mountain Pose", "sets": 1, "reps": "5 breaths"}, {"name": "Seated Cat-Cow", "sets": 1, "reps": "8 rounds"}]}, {"name": "Upper Body", "sequence": 1, "exercises": [{"name": "Seated Twist", "sets": 1, "reps": "5 breaths each side"}, {"name": "Seated Side Bend", "sets": 1, "reps": "5 breaths each side"}, {"name": "Eagle Arms", "sets": 1, "reps": "5 breaths each side"}]}, {"name": "Lower Body", "sequence": 2, "exercises": [{"name": "Seated Figure Four", "sets": 1, "reps": "5 breaths each side"}, {"name": "Seated Forward Fold", "sets": 1, "reps": "5 breaths"}, {"name": "Ankle Circles", "sets": 1, "reps": "10 each way"}]}, {"name": "Closing", "sequence": 3, "exercises": [{"name": "Seated Meditation", "sets": 1, "reps": "3-5 min"}]}]}'::jsonb,
ARRAY['senior', 'chair', 'yoga', 'gentle', 'flexibility'], 'senior_chair_yoga.md'),

('00c00001-0003-4000-8000-000000000003', 'Chair Cardio', 'Seated cardiovascular workout', 'cardio', 'beginner', 20,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Seated March", "sets": 1, "reps": "1 min"}]}, {"name": "Cardio Circuit", "sequence": 1, "exercises": [{"name": "Seated Jumping Jacks", "sets": 2, "reps": "30 sec", "notes": "Arms only with toe taps"}, {"name": "Seated Punches", "sets": 2, "reps": "30 sec"}, {"name": "Seated Knee Lifts", "sets": 2, "reps": "30 sec"}, {"name": "Seated Side Steps", "sets": 2, "reps": "30 sec"}, {"name": "Seated Bicycle", "sets": 2, "reps": "30 sec"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Gentle Stretching", "sets": 1, "reps": "3 min"}]}]}'::jsonb,
ARRAY['senior', 'chair', 'cardio', 'low-impact'], 'senior_chair_cardio.md'),

('00c00001-0004-4000-8000-000000000004', 'Seated Strength', 'Build strength while seated', 'strength', 'beginner', 25,
'{"blocks": [{"name": "Upper Body", "sequence": 0, "exercises": [{"name": "Seated Chest Press", "sets": 2, "reps": "12", "notes": "Resistance band or light weights"}, {"name": "Seated Row", "sets": 2, "reps": "12", "notes": "Band around feet"}, {"name": "Seated Lateral Raise", "sets": 2, "reps": "10"}]}, {"name": "Core", "sequence": 1, "exercises": [{"name": "Seated Knee Lift Hold", "sets": 2, "reps": "10 sec each leg"}, {"name": "Seated Twist", "sets": 2, "reps": "10 each side"}]}, {"name": "Lower Body", "sequence": 2, "exercises": [{"name": "Seated Leg Press", "sets": 2, "reps": "12", "notes": "Press feet against floor"}, {"name": "Seated Calf Raise", "sets": 2, "reps": "15"}]}]}'::jsonb,
ARRAY['senior', 'chair', 'strength', 'resistance-band'], 'senior_seated_strength.md'),

('00c00001-0005-4000-8000-000000000005', 'Chair Core', 'Core strengthening while seated', 'strength', 'beginner', 20,
'{"blocks": [{"name": "Activation", "sequence": 0, "exercises": [{"name": "Seated Pelvic Tilt", "sets": 2, "reps": "10"}, {"name": "Belly Breathing", "sets": 1, "reps": "10 breaths"}]}, {"name": "Core Work", "sequence": 1, "exercises": [{"name": "Seated Crunch", "sets": 2, "reps": "12"}, {"name": "Seated Oblique Twist", "sets": 2, "reps": "10 each side"}, {"name": "Seated Knee to Chest", "sets": 2, "reps": "10 each leg"}, {"name": "Seated Leg Lift Hold", "sets": 2, "reps": "10 sec each leg"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Seated Cat-Cow", "sets": 1, "reps": "8"}]}]}'::jsonb,
ARRAY['senior', 'chair', 'core', 'gentle'], 'senior_chair_core.md'),

('00c00001-0006-4000-8000-000000000006', 'Chair Upper Body', 'Upper body focus while seated', 'upper', 'beginner', 25,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Arm Circles", "sets": 1, "reps": "10 each way"}, {"name": "Shoulder Shrugs", "sets": 1, "reps": "10"}]}, {"name": "Pushing", "sequence": 1, "exercises": [{"name": "Seated Wall Push-Up", "sets": 2, "reps": "10", "notes": "Push against armrests"}, {"name": "Seated Overhead Press", "sets": 2, "reps": "12"}]}, {"name": "Pulling", "sequence": 2, "exercises": [{"name": "Seated Row", "sets": 2, "reps": "12", "notes": "Resistance band"}, {"name": "Seated Bicep Curl", "sets": 2, "reps": "12"}]}, {"name": "Cool Down", "sequence": 3, "exercises": [{"name": "Tricep Stretch", "sets": 1, "reps": "30 sec each"}, {"name": "Chest Stretch", "sets": 1, "reps": "30 sec"}]}]}'::jsonb,
ARRAY['senior', 'chair', 'upper-body', 'strength'], 'senior_chair_upper.md'),

('00c00001-0007-4000-8000-000000000007', 'Chair Lower Body', 'Lower body focus while seated', 'lower', 'beginner', 25,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Ankle Circles", "sets": 1, "reps": "10 each way"}, {"name": "Knee Extensions", "sets": 1, "reps": "10 each leg"}]}, {"name": "Quad Focus", "sequence": 1, "exercises": [{"name": "Seated Leg Extension", "sets": 3, "reps": "12 each leg"}, {"name": "Seated March", "sets": 2, "reps": "1 min"}]}, {"name": "Hamstring & Glute", "sequence": 2, "exercises": [{"name": "Seated Heel Dig", "sets": 2, "reps": "12 each leg"}, {"name": "Seated Glute Squeeze", "sets": 2, "reps": "15"}]}, {"name": "Calves", "sequence": 3, "exercises": [{"name": "Seated Calf Raise", "sets": 3, "reps": "15"}, {"name": "Toe Taps", "sets": 2, "reps": "20"}]}]}'::jsonb,
ARRAY['senior', 'chair', 'lower-body', 'strength'], 'senior_chair_lower.md'),

-- STANDING BALANCE WORKOUTS (6)
('00c00001-0008-4000-8000-000000000008', 'Balance Basics', 'Fundamental balance exercises with chair support', 'mobility', 'beginner', 20,
'{"blocks": [{"name": "Static Balance", "sequence": 0, "exercises": [{"name": "Single Leg Stand", "sets": 3, "reps": "15 sec each leg", "notes": "Hold chair for support"}, {"name": "Tandem Stance", "sets": 2, "reps": "20 sec each foot forward"}]}, {"name": "Weight Shifts", "sequence": 1, "exercises": [{"name": "Side to Side Shift", "sets": 2, "reps": "10 each way"}, {"name": "Forward-Back Shift", "sets": 2, "reps": "10"}]}, {"name": "Reaching", "sequence": 2, "exercises": [{"name": "Clock Reaches", "sets": 2, "reps": "4 directions each leg"}, {"name": "Arm Reaches While Standing", "sets": 2, "reps": "10 each arm"}]}]}'::jsonb,
ARRAY['senior', 'balance', 'fall-prevention', 'beginner'], 'senior_balance_basics.md'),

('00c00001-0009-4000-8000-000000000009', 'Fall Prevention', 'Exercises specifically for fall prevention', 'mobility', 'beginner', 25,
'{"blocks": [{"name": "Ankle Strength", "sequence": 0, "exercises": [{"name": "Heel Raises", "sets": 3, "reps": "12", "notes": "Hold chair"}, {"name": "Toe Raises", "sets": 3, "reps": "12"}]}, {"name": "Leg Strength", "sequence": 1, "exercises": [{"name": "Mini Squats", "sets": 2, "reps": "10", "notes": "Chair for balance"}, {"name": "Side Leg Raise", "sets": 2, "reps": "10 each leg"}, {"name": "Back Leg Raise", "sets": 2, "reps": "10 each leg"}]}, {"name": "Balance Challenges", "sequence": 2, "exercises": [{"name": "Heel-Toe Walk", "sets": 2, "reps": "10 steps"}, {"name": "Single Leg Stand Eyes Closed", "sets": 2, "reps": "10 sec each", "notes": "Chair nearby"}]}]}'::jsonb,
ARRAY['senior', 'balance', 'fall-prevention', 'strength'], 'senior_fall_prevention.md'),

('00c00001-0010-4000-8000-000000000010', 'Tai Chi Inspired', 'Gentle flowing movements for balance and calm', 'mobility', 'beginner', 30,
'{"blocks": [{"name": "Opening", "sequence": 0, "exercises": [{"name": "Standing Meditation", "sets": 1, "reps": "1 min"}, {"name": "Gentle Swaying", "sets": 1, "reps": "1 min"}]}, {"name": "Tai Chi Forms", "sequence": 1, "exercises": [{"name": "Parting Wild Horses Mane", "sets": 1, "reps": "8 each side"}, {"name": "White Crane Spreads Wings", "sets": 1, "reps": "6 each side"}, {"name": "Brush Knee Push", "sets": 1, "reps": "6 each side"}, {"name": "Wave Hands Like Clouds", "sets": 1, "reps": "10"}]}, {"name": "Closing", "sequence": 2, "exercises": [{"name": "Cross Hands", "sets": 1, "reps": "5"}, {"name": "Standing Meditation", "sets": 1, "reps": "2 min"}]}]}'::jsonb,
ARRAY['senior', 'tai-chi', 'balance', 'gentle', 'mindfulness'], 'senior_tai_chi.md'),

('00c00001-0011-4000-8000-000000000011', 'Balance Circuit', 'Progressive balance challenges', 'mobility', 'intermediate', 25,
'{"blocks": [{"name": "Dynamic Warm-Up", "sequence": 0, "exercises": [{"name": "Marching in Place", "sets": 1, "reps": "1 min"}, {"name": "Arm Swings", "sets": 1, "reps": "30 sec"}]}, {"name": "Balance Circuit", "sequence": 1, "exercises": [{"name": "Single Leg Stand", "sets": 3, "reps": "20 sec each"}, {"name": "Tandem Walk", "sets": 2, "reps": "20 steps"}, {"name": "Side Steps Over Line", "sets": 2, "reps": "10 each way"}, {"name": "Backward Walking", "sets": 2, "reps": "10 steps"}]}, {"name": "Strength", "sequence": 2, "exercises": [{"name": "Single Leg Mini Squat", "sets": 2, "reps": "8 each leg"}]}]}'::jsonb,
ARRAY['senior', 'balance', 'circuit', 'intermediate'], 'senior_balance_circuit.md'),

('00c00001-0012-4000-8000-000000000012', 'Walking Program', 'Structured walking workout', 'cardio', 'beginner', 30,
'{"blocks": [{"name": "Warm-Up Walk", "sequence": 0, "exercises": [{"name": "Easy Pace Walk", "sets": 1, "reps": "5 min", "notes": "Conversational pace"}]}, {"name": "Main Walk", "sequence": 1, "exercises": [{"name": "Moderate Pace Walk", "sets": 1, "reps": "15 min", "notes": "Slightly faster, can still talk"}, {"name": "Interval Bursts", "sets": 3, "reps": "30 sec fast, 1 min easy", "notes": "Optional for variety"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Slow Pace Walk", "sets": 1, "reps": "5 min"}, {"name": "Standing Stretches", "sets": 1, "reps": "5 min"}]}]}'::jsonb,
ARRAY['senior', 'walking', 'cardio', 'outdoor'], 'senior_walking.md'),

('00c00001-0013-4000-8000-000000000013', 'Pool Walking', 'Aquatic walking workout', 'cardio', 'beginner', 30,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Forward Walk", "sets": 1, "reps": "3 min", "notes": "Chest-deep water"}, {"name": "Arm Swings Underwater", "sets": 1, "reps": "20"}]}, {"name": "Main Workout", "sequence": 1, "exercises": [{"name": "High Knee Walk", "sets": 2, "reps": "2 min"}, {"name": "Side Shuffle", "sets": 2, "reps": "2 min each way"}, {"name": "Backward Walk", "sets": 2, "reps": "2 min"}, {"name": "Cross-Step Walk", "sets": 2, "reps": "2 min"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Easy Walk", "sets": 1, "reps": "3 min"}, {"name": "Pool Edge Stretches", "sets": 1, "reps": "5 min"}]}]}'::jsonb,
ARRAY['senior', 'aquatic', 'pool', 'cardio', 'low-impact'], 'senior_pool_walking.md'),

-- LOW IMPACT CARDIO (4)
('00c00001-0014-4000-8000-000000000014', 'Gentle Aerobics', 'Low impact aerobic workout', 'cardio', 'beginner', 25,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "March in Place", "sets": 1, "reps": "2 min"}, {"name": "Step Touch", "sets": 1, "reps": "2 min"}]}, {"name": "Cardio", "sequence": 1, "exercises": [{"name": "Grapevine", "sets": 2, "reps": "1 min each way"}, {"name": "V-Step", "sets": 2, "reps": "16 reps"}, {"name": "Hamstring Curl", "sets": 2, "reps": "16 each leg"}, {"name": "Low Impact Jacks", "sets": 2, "reps": "16", "notes": "Step out side to side"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "March", "sets": 1, "reps": "2 min"}, {"name": "Full Body Stretch", "sets": 1, "reps": "5 min"}]}]}'::jsonb,
ARRAY['senior', 'aerobics', 'cardio', 'low-impact'], 'senior_gentle_aerobics.md'),

('00c00001-0015-4000-8000-000000000015', 'Silver Sneakers Classic', 'Silver Sneakers inspired full body', 'full_body', 'beginner', 45,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "March in Place", "sets": 1, "reps": "3 min"}, {"name": "Shoulder Rolls", "sets": 1, "reps": "10 each way"}]}, {"name": "Cardio", "sequence": 1, "exercises": [{"name": "Step Touch", "sets": 1, "reps": "3 min"}, {"name": "Grapevine", "sets": 1, "reps": "3 min"}]}, {"name": "Strength", "sequence": 2, "exercises": [{"name": "Bicep Curl", "sets": 2, "reps": "12", "notes": "Light weights"}, {"name": "Overhead Press", "sets": 2, "reps": "12"}, {"name": "Chair Squat", "sets": 2, "reps": "10"}]}, {"name": "Balance", "sequence": 3, "exercises": [{"name": "Single Leg Stand", "sets": 2, "reps": "15 sec each"}]}, {"name": "Flexibility", "sequence": 4, "exercises": [{"name": "Full Body Stretch Routine", "sets": 1, "reps": "10 min"}]}]}'::jsonb,
ARRAY['senior', 'silver-sneakers', 'full-body', 'low-impact'], 'senior_silver_sneakers.md'),

('00c00001-0016-4000-8000-000000000016', 'Water Aerobics', 'Pool-based aerobic workout', 'cardio', 'beginner', 45,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Water Walking", "sets": 1, "reps": "3 min"}, {"name": "Arm Circles in Water", "sets": 1, "reps": "20 each way"}]}, {"name": "Cardio", "sequence": 1, "exercises": [{"name": "Water Jogging", "sets": 2, "reps": "3 min"}, {"name": "Jumping Jacks", "sets": 2, "reps": "20", "notes": "Water reduces impact"}, {"name": "Cross Country Ski", "sets": 2, "reps": "2 min"}]}, {"name": "Strength", "sequence": 2, "exercises": [{"name": "Water Push-Ups", "sets": 2, "reps": "12", "notes": "Against pool wall"}, {"name": "Leg Kicks", "sets": 2, "reps": "15 each leg"}, {"name": "Arm Curls with Water", "sets": 2, "reps": "15"}]}, {"name": "Cool Down", "sequence": 3, "exercises": [{"name": "Easy Water Walking", "sets": 1, "reps": "3 min"}, {"name": "Pool Stretches", "sets": 1, "reps": "5 min"}]}]}'::jsonb,
ARRAY['senior', 'aquatic', 'water-aerobics', 'cardio', 'low-impact'], 'senior_water_aerobics.md'),

('00c00001-0017-4000-8000-000000000017', 'Recumbent Bike Workout', 'Stationary bike with back support', 'cardio', 'beginner', 25,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Easy Pedaling", "sets": 1, "reps": "5 min", "notes": "Low resistance"}]}, {"name": "Main Workout", "sequence": 1, "exercises": [{"name": "Moderate Pedaling", "sets": 1, "reps": "10 min", "notes": "Comfortable pace"}, {"name": "Intervals", "sets": 4, "reps": "30 sec faster, 1 min easy", "notes": "Optional"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Easy Pedaling", "sets": 1, "reps": "5 min"}, {"name": "Seated Stretches", "sets": 1, "reps": "5 min"}]}]}'::jsonb,
ARRAY['senior', 'bike', 'cardio', 'low-impact', 'recumbent'], 'senior_recumbent_bike.md'),

-- GENTLE STRETCHING & FLEXIBILITY (5)
('00c00001-0018-4000-8000-000000000018', 'Morning Stretch Routine', 'Gentle morning wake-up stretches', 'mobility', 'beginner', 15,
'{"blocks": [{"name": "In Bed", "sequence": 0, "exercises": [{"name": "Full Body Stretch", "sets": 1, "reps": "30 sec"}, {"name": "Knee to Chest", "sets": 1, "reps": "30 sec each"}]}, {"name": "Seated", "sequence": 1, "exercises": [{"name": "Neck Stretches", "sets": 1, "reps": "30 sec each direction"}, {"name": "Shoulder Rolls", "sets": 1, "reps": "10 each way"}, {"name": "Seated Twist", "sets": 1, "reps": "30 sec each side"}]}, {"name": "Standing", "sequence": 2, "exercises": [{"name": "Standing Side Bend", "sets": 1, "reps": "30 sec each side"}, {"name": "Standing Quad Stretch", "sets": 1, "reps": "30 sec each", "notes": "Hold chair"}]}]}'::jsonb,
ARRAY['senior', 'stretching', 'morning', 'gentle', 'flexibility'], 'senior_morning_stretch.md'),

('00c00001-0019-4000-8000-000000000019', 'Evening Relaxation', 'Calming evening stretch routine', 'mobility', 'beginner', 20,
'{"blocks": [{"name": "Breathing", "sequence": 0, "exercises": [{"name": "Deep Breathing", "sets": 1, "reps": "10 breaths"}, {"name": "4-7-8 Breathing", "sets": 1, "reps": "5 cycles"}]}, {"name": "Gentle Stretches", "sequence": 1, "exercises": [{"name": "Neck Rolls", "sets": 1, "reps": "5 each way"}, {"name": "Shoulder Stretch", "sets": 1, "reps": "30 sec each"}, {"name": "Seated Forward Fold", "sets": 1, "reps": "30 sec"}, {"name": "Supine Twist", "sets": 1, "reps": "30 sec each side"}]}, {"name": "Relaxation", "sequence": 2, "exercises": [{"name": "Body Scan", "sets": 1, "reps": "5 min"}]}]}'::jsonb,
ARRAY['senior', 'stretching', 'evening', 'relaxation', 'gentle'], 'senior_evening_relax.md'),

('00c00001-0020-4000-8000-000000000020', 'Joint Mobility', 'Gentle joint mobility routine', 'mobility', 'beginner', 20,
'{"blocks": [{"name": "Upper Body", "sequence": 0, "exercises": [{"name": "Neck Circles", "sets": 1, "reps": "5 each way", "notes": "Slow and gentle"}, {"name": "Shoulder Circles", "sets": 1, "reps": "10 each way"}, {"name": "Wrist Circles", "sets": 1, "reps": "10 each way"}, {"name": "Finger Stretches", "sets": 1, "reps": "5 each hand"}]}, {"name": "Spine", "sequence": 1, "exercises": [{"name": "Cat-Cow", "sets": 1, "reps": "10 slow"}, {"name": "Seated Twist", "sets": 1, "reps": "5 each side"}]}, {"name": "Lower Body", "sequence": 2, "exercises": [{"name": "Hip Circles", "sets": 1, "reps": "10 each way"}, {"name": "Knee Circles", "sets": 1, "reps": "10 each way"}, {"name": "Ankle Circles", "sets": 1, "reps": "10 each way"}]}]}'::jsonb,
ARRAY['senior', 'mobility', 'joints', 'gentle', 'arthritis'], 'senior_joint_mobility.md'),

('00c00001-0021-4000-8000-000000000021', 'Arthritis-Friendly', 'Safe stretches for arthritis management', 'mobility', 'beginner', 20,
'{"blocks": [{"name": "Hand Exercises", "sequence": 0, "exercises": [{"name": "Finger Spread", "sets": 2, "reps": "10"}, {"name": "Finger Touch", "sets": 2, "reps": "5 each finger"}, {"name": "Wrist Flexion", "sets": 2, "reps": "10"}]}, {"name": "Larger Joints", "sequence": 1, "exercises": [{"name": "Gentle Shoulder Rolls", "sets": 1, "reps": "10 each way"}, {"name": "Elbow Flexion", "sets": 2, "reps": "10"}, {"name": "Hip Flexion Seated", "sets": 2, "reps": "10 each"}, {"name": "Ankle Pumps", "sets": 2, "reps": "15"}]}, {"name": "Warm Water Option", "sequence": 2, "exercises": [{"name": "Warm Bath Stretching", "sets": 1, "reps": "10 min", "notes": "If available, do stretches in warm water"}]}]}'::jsonb,
ARRAY['senior', 'arthritis', 'gentle', 'therapeutic', 'joints'], 'senior_arthritis.md'),

('00c00001-0022-4000-8000-000000000022', 'Gentle Floor Stretching', 'Floor-based stretching with modifications', 'mobility', 'beginner', 25,
'{"blocks": [{"name": "Getting Down", "sequence": 0, "exercises": [{"name": "Chair-Assisted Floor Transfer", "sets": 1, "reps": "1", "notes": "Use chair to safely get down"}]}, {"name": "Supine Stretches", "sequence": 1, "exercises": [{"name": "Knee to Chest", "sets": 2, "reps": "30 sec each"}, {"name": "Supine Twist", "sets": 2, "reps": "30 sec each side"}, {"name": "Figure Four Stretch", "sets": 2, "reps": "30 sec each"}]}, {"name": "Side Lying", "sequence": 2, "exercises": [{"name": "Side Lying Quad Stretch", "sets": 1, "reps": "30 sec each"}]}, {"name": "Getting Up", "sequence": 3, "exercises": [{"name": "Chair-Assisted Floor to Stand", "sets": 1, "reps": "1"}]}]}'::jsonb,
ARRAY['senior', 'stretching', 'floor', 'gentle', 'flexibility'], 'senior_floor_stretch.md'),

-- STRENGTH TRAINING (3)
('00c00001-0023-4000-8000-000000000023', 'Resistance Band Full Body', 'Full body workout with light bands', 'strength', 'beginner', 30,
'{"blocks": [{"name": "Upper Body", "sequence": 0, "exercises": [{"name": "Band Chest Press", "sets": 2, "reps": "12"}, {"name": "Band Row", "sets": 2, "reps": "12"}, {"name": "Band Bicep Curl", "sets": 2, "reps": "12"}, {"name": "Band Tricep Extension", "sets": 2, "reps": "12"}]}, {"name": "Lower Body", "sequence": 1, "exercises": [{"name": "Band Leg Press", "sets": 2, "reps": "12"}, {"name": "Band Side Steps", "sets": 2, "reps": "10 each way"}, {"name": "Band Clamshell", "sets": 2, "reps": "12 each side"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Stretching", "sets": 1, "reps": "5 min"}]}]}'::jsonb,
ARRAY['senior', 'resistance-band', 'strength', 'full-body'], 'senior_band_full_body.md'),

('00c00001-0024-4000-8000-000000000024', 'Light Dumbbell Workout', 'Strength training with 1-5 lb weights', 'strength', 'beginner', 30,
'{"blocks": [{"name": "Upper Body", "sequence": 0, "exercises": [{"name": "Dumbbell Chest Press", "sets": 2, "reps": "12", "notes": "Lying on floor or bench"}, {"name": "Dumbbell Row", "sets": 2, "reps": "12 each"}, {"name": "Dumbbell Shoulder Press", "sets": 2, "reps": "10"}, {"name": "Dumbbell Curl", "sets": 2, "reps": "12"}]}, {"name": "Lower Body", "sequence": 1, "exercises": [{"name": "Goblet Squat", "sets": 2, "reps": "10", "notes": "To chair"}, {"name": "Dumbbell Deadlift", "sets": 2, "reps": "10", "notes": "Light weight"}]}, {"name": "Core", "sequence": 2, "exercises": [{"name": "Pallof Press", "sets": 2, "reps": "10 each side", "notes": "With light dumbbell"}]}]}'::jsonb,
ARRAY['senior', 'dumbbell', 'strength', 'light-weight'], 'senior_light_dumbbell.md'),

('00c00001-0025-4000-8000-000000000025', 'Bone Health Workout', 'Weight-bearing exercises for bone density', 'strength', 'beginner', 30,
'{"blocks": [{"name": "Weight Bearing", "sequence": 0, "exercises": [{"name": "Heel Drops", "sets": 3, "reps": "10", "notes": "Rise on toes, drop heels"}, {"name": "Marching", "sets": 2, "reps": "1 min"}, {"name": "Mini Squats", "sets": 2, "reps": "10"}]}, {"name": "Resistance", "sequence": 1, "exercises": [{"name": "Wall Push-Up", "sets": 2, "reps": "10"}, {"name": "Bicep Curl", "sets": 2, "reps": "12", "notes": "With weights"}, {"name": "Hip Extension", "sets": 2, "reps": "10 each leg"}]}, {"name": "Balance", "sequence": 2, "exercises": [{"name": "Single Leg Stand", "sets": 2, "reps": "15 sec each", "notes": "Prevents falls which cause fractures"}]}]}'::jsonb,
ARRAY['senior', 'bone-health', 'osteoporosis', 'weight-bearing', 'strength'], 'senior_bone_health.md');
