-- Seed Calisthenics workout templates (25 templates)
-- Focus: Progressive bodyweight skills, gymnastics-inspired, minimal equipment

INSERT INTO system_workout_templates (id, name, description, category, difficulty, duration_minutes, exercises, tags, source_file) VALUES

-- BEGINNER FOUNDATIONS (6)
('00e00001-0001-4000-8000-000000000001', 'Calisthenics Fundamentals', 'Basic movement patterns for beginners', 'strength', 'beginner', 40,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "sets": 2, "reps": "20"}, {"name": "Arm Circles", "sets": 1, "reps": "10 each way"}, {"name": "Bodyweight Squat", "sets": 2, "reps": "10"}]}, {"name": "Push", "sequence": 1, "exercises": [{"name": "Wall Push-Up", "sets": 3, "reps": "12"}, {"name": "Incline Push-Up", "sets": 3, "reps": "10", "notes": "Hands on bench or stairs"}]}, {"name": "Pull", "sequence": 2, "exercises": [{"name": "Australian Row", "sets": 3, "reps": "10", "notes": "Under table or low bar"}, {"name": "Scapular Pull-Up", "sets": 3, "reps": "8", "notes": "Hang and pull shoulders down"}]}, {"name": "Legs", "sequence": 3, "exercises": [{"name": "Bodyweight Squat", "sets": 3, "reps": "15"}, {"name": "Glute Bridge", "sets": 3, "reps": "12"}]}, {"name": "Core", "sequence": 4, "exercises": [{"name": "Dead Bug", "sets": 3, "reps": "10 each"}, {"name": "Plank", "sets": 3, "reps": "20 sec"}]}]}'::jsonb,
ARRAY['calisthenics', 'beginner', 'fundamentals', 'full-body', 'bodyweight'], 'calisthenics_fundamentals.md'),

('00e00001-0002-4000-8000-000000000002', 'Push-Up Progression', 'Master the push-up from zero to full', 'strength', 'beginner', 30,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Arm Circles", "sets": 1, "reps": "10 each way"}, {"name": "Wall Push-Up", "sets": 2, "reps": "10"}]}, {"name": "Progression Work", "sequence": 1, "exercises": [{"name": "Current Level Push-Up", "sets": 5, "reps": "max", "notes": "Wall → Incline → Knee → Full → Decline"}, {"name": "Negative Push-Up", "sets": 3, "reps": "5", "notes": "5 second lowering"}]}, {"name": "Accessory", "sequence": 2, "exercises": [{"name": "Plank", "sets": 3, "reps": "30 sec"}, {"name": "Tricep Dip on Chair", "sets": 3, "reps": "10"}]}, {"name": "Stretch", "sequence": 3, "exercises": [{"name": "Chest Stretch", "sets": 2, "reps": "30 sec"}, {"name": "Tricep Stretch", "sets": 2, "reps": "30 sec each"}]}]}'::jsonb,
ARRAY['calisthenics', 'beginner', 'push-up', 'progression', 'push'], 'calisthenics_pushup_prog.md'),

('00e00001-0003-4000-8000-000000000003', 'Pull-Up Progression', 'Build towards your first pull-up', 'strength', 'beginner', 30,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Band Pull-Aparts", "sets": 2, "reps": "15"}, {"name": "Dead Hang", "sets": 3, "reps": "15 sec"}]}, {"name": "Progression Work", "sequence": 1, "exercises": [{"name": "Scapular Pull-Up", "sets": 3, "reps": "10"}, {"name": "Australian Row", "sets": 4, "reps": "10", "notes": "Feet elevated for harder"}, {"name": "Band-Assisted Pull-Up", "sets": 4, "reps": "5-8", "notes": "Or negative pull-ups"}]}, {"name": "Accessory", "sequence": 2, "exercises": [{"name": "Bicep Curl", "sets": 3, "reps": "12", "notes": "Band or dumbbell"}, {"name": "Face Pull", "sets": 3, "reps": "15"}]}, {"name": "Grip", "sequence": 3, "exercises": [{"name": "Dead Hang", "sets": 3, "reps": "max time"}]}]}'::jsonb,
ARRAY['calisthenics', 'beginner', 'pull-up', 'progression', 'pull'], 'calisthenics_pullup_prog.md'),

('00e00001-0004-4000-8000-000000000004', 'Squat Progression', 'Bodyweight squat mastery', 'strength', 'beginner', 30,
'{"blocks": [{"name": "Mobility", "sequence": 0, "exercises": [{"name": "Ankle Circles", "sets": 1, "reps": "10 each"}, {"name": "Hip Circles", "sets": 1, "reps": "10 each"}, {"name": "Squat Hold", "sets": 2, "reps": "30 sec"}]}, {"name": "Progression", "sequence": 1, "exercises": [{"name": "Box Squat", "sets": 3, "reps": "12", "notes": "Lower box as you progress"}, {"name": "Bodyweight Squat", "sets": 4, "reps": "15"}, {"name": "Pause Squat", "sets": 3, "reps": "8", "notes": "3 sec pause at bottom"}]}, {"name": "Single Leg", "sequence": 2, "exercises": [{"name": "Split Squat", "sets": 3, "reps": "10 each"}, {"name": "Step-Up", "sets": 3, "reps": "10 each"}]}, {"name": "Stretch", "sequence": 3, "exercises": [{"name": "Couch Stretch", "sets": 2, "reps": "60 sec each"}]}]}'::jsonb,
ARRAY['calisthenics', 'beginner', 'squat', 'progression', 'legs'], 'calisthenics_squat_prog.md'),

('00e00001-0005-4000-8000-000000000005', 'Core Foundation', 'Build a strong core from scratch', 'strength', 'beginner', 25,
'{"blocks": [{"name": "Activation", "sequence": 0, "exercises": [{"name": "Diaphragmatic Breathing", "sets": 1, "reps": "10 breaths"}, {"name": "Dead Bug Hold", "sets": 2, "reps": "20 sec"}]}, {"name": "Anti-Extension", "sequence": 1, "exercises": [{"name": "Plank", "sets": 3, "reps": "30 sec"}, {"name": "Dead Bug", "sets": 3, "reps": "10 each side"}]}, {"name": "Anti-Rotation", "sequence": 2, "exercises": [{"name": "Bird Dog", "sets": 3, "reps": "10 each side"}, {"name": "Pallof Press Hold", "sets": 2, "reps": "15 sec each side", "notes": "With band"}]}, {"name": "Anti-Lateral Flexion", "sequence": 3, "exercises": [{"name": "Side Plank", "sets": 2, "reps": "20 sec each"}, {"name": "Suitcase Carry", "sets": 2, "reps": "30 sec each", "notes": "Or hold weight at side"}]}]}'::jsonb,
ARRAY['calisthenics', 'beginner', 'core', 'foundation', 'stability'], 'calisthenics_core_foundation.md'),

('00e00001-0006-4000-8000-000000000006', 'Dip Progression', 'Build towards parallel bar dips', 'strength', 'beginner', 30,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Arm Circles", "sets": 1, "reps": "10 each"}, {"name": "Push-Ups", "sets": 2, "reps": "10"}]}, {"name": "Progression", "sequence": 1, "exercises": [{"name": "Bench Dip", "sets": 4, "reps": "12", "notes": "Feet on floor"}, {"name": "Elevated Bench Dip", "sets": 3, "reps": "10", "notes": "Feet elevated"}, {"name": "Negative Dip", "sets": 3, "reps": "5", "notes": "5 sec lowering on parallel bars"}]}, {"name": "Accessory", "sequence": 2, "exercises": [{"name": "Close Grip Push-Up", "sets": 3, "reps": "10"}, {"name": "Tricep Extension", "sets": 3, "reps": "12"}]}]}'::jsonb,
ARRAY['calisthenics', 'beginner', 'dip', 'progression', 'push'], 'calisthenics_dip_prog.md'),

-- INTERMEDIATE SKILLS (8)
('00e00001-0007-4000-8000-000000000007', 'Muscle-Up Preparation', 'Build the strength and technique for muscle-ups', 'strength', 'intermediate', 45,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Band Pull-Aparts", "sets": 2, "reps": "15"}, {"name": "Pull-Ups", "sets": 2, "reps": "5"}]}, {"name": "Pulling Power", "sequence": 1, "exercises": [{"name": "High Pull-Up", "sets": 5, "reps": "5", "notes": "Pull to chest, not chin"}, {"name": "Explosive Pull-Up", "sets": 4, "reps": "3-5", "notes": "Pull fast, hands can leave bar"}]}, {"name": "Transition", "sequence": 2, "exercises": [{"name": "Negative Muscle-Up", "sets": 5, "reps": "1", "notes": "Jump up, slow negative through transition"}, {"name": "Banded Muscle-Up", "sets": 3, "reps": "3"}]}, {"name": "Dip Strength", "sequence": 3, "exercises": [{"name": "Straight Bar Dip", "sets": 4, "reps": "8", "notes": "On pull-up bar"}, {"name": "Deep Dip", "sets": 3, "reps": "8"}]}]}'::jsonb,
ARRAY['calisthenics', 'intermediate', 'muscle-up', 'skill', 'pull'], 'calisthenics_muscleup_prep.md'),

('00e00001-0008-4000-8000-000000000008', 'Handstand Progression', 'Learn to balance on your hands', 'strength', 'intermediate', 40,
'{"blocks": [{"name": "Wrist Prep", "sequence": 0, "exercises": [{"name": "Wrist Circles", "sets": 1, "reps": "10 each way"}, {"name": "Wrist Stretches", "sets": 1, "reps": "30 sec each position"}]}, {"name": "Strength", "sequence": 1, "exercises": [{"name": "Pike Push-Up", "sets": 4, "reps": "8"}, {"name": "Box Pike Handstand Push-Up", "sets": 3, "reps": "6", "notes": "Feet on box, pike position"}, {"name": "Wall Walk", "sets": 3, "reps": "3"}]}, {"name": "Balance", "sequence": 2, "exercises": [{"name": "Chest to Wall Handstand", "sets": 5, "reps": "30 sec", "notes": "Face the wall"}, {"name": "Back to Wall Handstand", "sets": 3, "reps": "20 sec", "notes": "Back faces wall"}, {"name": "Toe Pulls", "sets": 3, "reps": "10", "notes": "In chest-to-wall, pull toes off wall briefly"}]}, {"name": "Kick-Up Practice", "sequence": 3, "exercises": [{"name": "Kick-Up Attempts", "sets": 10, "reps": "1", "notes": "Against wall for safety"}]}]}'::jsonb,
ARRAY['calisthenics', 'intermediate', 'handstand', 'skill', 'balance'], 'calisthenics_handstand.md'),

('00e00001-0009-4000-8000-000000000009', 'L-Sit Progression', 'Build towards a full L-sit hold', 'strength', 'intermediate', 30,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Hip Flexor Stretch", "sets": 2, "reps": "30 sec each"}, {"name": "Seated Leg Raises", "sets": 2, "reps": "15"}]}, {"name": "Compression", "sequence": 1, "exercises": [{"name": "Seated Pike Compression", "sets": 4, "reps": "10 sec hold", "notes": "Hands beside hips, press down, lift heels"}, {"name": "Single Leg Tuck L-Sit", "sets": 3, "reps": "10 sec each leg"}]}, {"name": "L-Sit Progression", "sequence": 2, "exercises": [{"name": "Tuck L-Sit", "sets": 5, "reps": "10-15 sec", "notes": "On parallettes or floor"}, {"name": "One Leg Extended L-Sit", "sets": 3, "reps": "10 sec each leg"}, {"name": "Full L-Sit Attempt", "sets": 3, "reps": "max time"}]}, {"name": "Accessory", "sequence": 3, "exercises": [{"name": "V-Up", "sets": 3, "reps": "10"}, {"name": "Hanging Knee Raise", "sets": 3, "reps": "12"}]}]}'::jsonb,
ARRAY['calisthenics', 'intermediate', 'l-sit', 'skill', 'core'], 'calisthenics_lsit.md'),

('00e00001-0010-4000-8000-000000000010', 'Pistol Squat Progression', 'Master the one-legged squat', 'strength', 'intermediate', 35,
'{"blocks": [{"name": "Mobility", "sequence": 0, "exercises": [{"name": "Deep Squat Hold", "sets": 2, "reps": "30 sec"}, {"name": "Ankle Stretch", "sets": 2, "reps": "30 sec each"}]}, {"name": "Progression", "sequence": 1, "exercises": [{"name": "Assisted Pistol", "sets": 4, "reps": "5 each", "notes": "Hold door frame or TRX"}, {"name": "Box Pistol", "sets": 4, "reps": "5 each", "notes": "Sit to box, stand on one leg"}, {"name": "Negative Pistol", "sets": 3, "reps": "3 each", "notes": "5 sec lowering"}]}, {"name": "Strength", "sequence": 2, "exercises": [{"name": "Bulgarian Split Squat", "sets": 3, "reps": "10 each"}, {"name": "Shrimp Squat Progression", "sets": 3, "reps": "6 each"}]}, {"name": "Balance", "sequence": 3, "exercises": [{"name": "Single Leg Balance", "sets": 2, "reps": "30 sec each"}]}]}'::jsonb,
ARRAY['calisthenics', 'intermediate', 'pistol-squat', 'skill', 'legs'], 'calisthenics_pistol.md'),

('00e00001-0011-4000-8000-000000000011', 'Front Lever Progression', 'Train towards the front lever', 'strength', 'intermediate', 40,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Dead Hang", "sets": 2, "reps": "20 sec"}, {"name": "Scapular Pull-Up", "sets": 2, "reps": "10"}]}, {"name": "Lever Progression", "sequence": 1, "exercises": [{"name": "Tuck Front Lever", "sets": 5, "reps": "10 sec hold"}, {"name": "Advanced Tuck FL", "sets": 4, "reps": "8 sec hold", "notes": "Extend hips slightly"}, {"name": "Tuck FL Raises", "sets": 4, "reps": "5", "notes": "From hang to tuck lever"}]}, {"name": "Accessory", "sequence": 2, "exercises": [{"name": "Ice Cream Makers", "sets": 3, "reps": "5", "notes": "Pull-up to tuck lever, repeat"}, {"name": "Dragon Flag Negative", "sets": 3, "reps": "3", "notes": "Slow lowering"}]}, {"name": "Pull Strength", "sequence": 3, "exercises": [{"name": "Pull-Up", "sets": 3, "reps": "max"}, {"name": "Australian Row", "sets": 3, "reps": "12"}]}]}'::jsonb,
ARRAY['calisthenics', 'intermediate', 'front-lever', 'skill', 'pull'], 'calisthenics_front_lever.md'),

('00e00001-0012-4000-8000-000000000012', 'Back Lever Progression', 'Train towards the back lever', 'strength', 'intermediate', 40,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Shoulder Dislocates", "sets": 2, "reps": "10", "notes": "With stick or band"}, {"name": "German Hang", "sets": 2, "reps": "15 sec", "notes": "Hang behind bar, careful on shoulders"}]}, {"name": "Lever Progression", "sequence": 1, "exercises": [{"name": "Tuck Back Lever", "sets": 5, "reps": "10 sec hold"}, {"name": "Advanced Tuck BL", "sets": 4, "reps": "8 sec hold"}, {"name": "Skin the Cat", "sets": 4, "reps": "3", "notes": "Full rotation through back lever"}]}, {"name": "Accessory", "sequence": 2, "exercises": [{"name": "Reverse Planche Lean", "sets": 3, "reps": "15 sec"}, {"name": "Straight Arm Press Down", "sets": 3, "reps": "12", "notes": "Cable or band"}]}, {"name": "Shoulder Health", "sequence": 3, "exercises": [{"name": "Face Pull", "sets": 3, "reps": "15"}, {"name": "External Rotation", "sets": 3, "reps": "12"}]}]}'::jsonb,
ARRAY['calisthenics', 'intermediate', 'back-lever', 'skill', 'pull'], 'calisthenics_back_lever.md'),

('00e00001-0013-4000-8000-000000000013', 'Planche Progression', 'Build planche strength step by step', 'strength', 'intermediate', 45,
'{"blocks": [{"name": "Wrist Prep", "sequence": 0, "exercises": [{"name": "Wrist Stretches", "sets": 1, "reps": "2 min"}, {"name": "Planche Lean", "sets": 3, "reps": "15 sec"}]}, {"name": "Planche Work", "sequence": 1, "exercises": [{"name": "Tuck Planche", "sets": 5, "reps": "10 sec hold", "notes": "On parallettes"}, {"name": "Tuck Planche Push-Up", "sets": 3, "reps": "5"}, {"name": "Frog Stand", "sets": 3, "reps": "20 sec"}]}, {"name": "Straight Arm Strength", "sequence": 2, "exercises": [{"name": "Planche Lean", "sets": 4, "reps": "20 sec", "notes": "Lean as far forward as possible"}, {"name": "Pseudo Planche Push-Up", "sets": 4, "reps": "8", "notes": "Lean forward in push-up"}]}, {"name": "Accessory", "sequence": 3, "exercises": [{"name": "Dip", "sets": 3, "reps": "12"}, {"name": "Straight Arm Band Press", "sets": 3, "reps": "12"}]}]}'::jsonb,
ARRAY['calisthenics', 'intermediate', 'planche', 'skill', 'push'], 'calisthenics_planche.md'),

('00e00001-0014-4000-8000-000000000014', 'Human Flag Progression', 'Train the side lever/human flag', 'strength', 'intermediate', 40,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Side Plank", "sets": 2, "reps": "30 sec each"}, {"name": "Dead Hang", "sets": 2, "reps": "20 sec"}]}, {"name": "Flag Progression", "sequence": 1, "exercises": [{"name": "Vertical Flag", "sets": 4, "reps": "10 sec", "notes": "Body vertical, legs up"}, {"name": "Tuck Flag", "sets": 4, "reps": "8 sec", "notes": "Knees tucked"}, {"name": "Flag Negatives", "sets": 3, "reps": "3 each side", "notes": "From vertical, slowly lower"}]}, {"name": "Strength", "sequence": 2, "exercises": [{"name": "Side Plank with Top Leg Raise", "sets": 3, "reps": "10 each side"}, {"name": "One Arm Hang", "sets": 3, "reps": "10 sec each"}]}, {"name": "Oblique Work", "sequence": 3, "exercises": [{"name": "Hanging Windshield Wipers", "sets": 3, "reps": "6 each way"}, {"name": "Russian Twist", "sets": 3, "reps": "15 each side"}]}]}'::jsonb,
ARRAY['calisthenics', 'intermediate', 'human-flag', 'skill', 'core'], 'calisthenics_flag.md'),

-- ADVANCED PROGRAMS (5)
('00e00001-0015-4000-8000-000000000015', 'Advanced Push Day', 'Advanced pushing movements', 'strength', 'advanced', 50,
'{"blocks": [{"name": "Skill Work", "sequence": 0, "exercises": [{"name": "Handstand Practice", "sets": 5, "reps": "30 sec"}, {"name": "Handstand Push-Up", "sets": 4, "reps": "max", "notes": "Against wall"}]}, {"name": "Planche Work", "sequence": 1, "exercises": [{"name": "Tuck Planche Hold", "sets": 4, "reps": "15 sec"}, {"name": "Pseudo Planche Push-Up", "sets": 4, "reps": "8"}]}, {"name": "Push Strength", "sequence": 2, "exercises": [{"name": "Weighted Dip", "sets": 4, "reps": "8"}, {"name": "Archer Push-Up", "sets": 3, "reps": "6 each side"}, {"name": "Ring Push-Up", "sets": 3, "reps": "10"}]}, {"name": "Finisher", "sequence": 3, "exercises": [{"name": "Diamond Push-Up", "sets": 2, "reps": "max"}, {"name": "Pike Push-Up", "sets": 2, "reps": "max"}]}]}'::jsonb,
ARRAY['calisthenics', 'advanced', 'push', 'handstand', 'planche'], 'calisthenics_adv_push.md'),

('00e00001-0016-4000-8000-000000000016', 'Advanced Pull Day', 'Advanced pulling movements', 'strength', 'advanced', 50,
'{"blocks": [{"name": "Skill Work", "sequence": 0, "exercises": [{"name": "Muscle-Up", "sets": 5, "reps": "3-5"}, {"name": "Typewriter Pull-Up", "sets": 3, "reps": "4 each side"}]}, {"name": "Lever Work", "sequence": 1, "exercises": [{"name": "Front Lever Hold", "sets": 5, "reps": "max", "notes": "Current progression"}, {"name": "Front Lever Raises", "sets": 4, "reps": "3-5"}]}, {"name": "Pull Strength", "sequence": 2, "exercises": [{"name": "Weighted Pull-Up", "sets": 4, "reps": "6-8"}, {"name": "Archer Pull-Up", "sets": 3, "reps": "4 each side"}, {"name": "L-Sit Pull-Up", "sets": 3, "reps": "8"}]}, {"name": "Grip", "sequence": 3, "exercises": [{"name": "One Arm Hang", "sets": 3, "reps": "15 sec each"}, {"name": "Towel Pull-Up", "sets": 2, "reps": "max"}]}]}'::jsonb,
ARRAY['calisthenics', 'advanced', 'pull', 'muscle-up', 'front-lever'], 'calisthenics_adv_pull.md'),

('00e00001-0017-4000-8000-000000000017', 'Advanced Leg Day', 'Advanced single leg training', 'strength', 'advanced', 45,
'{"blocks": [{"name": "Mobility", "sequence": 0, "exercises": [{"name": "Deep Squat Hold", "sets": 2, "reps": "30 sec"}, {"name": "Cossack Squat", "sets": 2, "reps": "8 each side"}]}, {"name": "Single Leg", "sequence": 1, "exercises": [{"name": "Pistol Squat", "sets": 5, "reps": "5 each"}, {"name": "Shrimp Squat", "sets": 4, "reps": "5 each"}, {"name": "Dragon Pistol", "sets": 3, "reps": "3 each", "notes": "Rear leg hooks around front leg"}]}, {"name": "Plyometrics", "sequence": 2, "exercises": [{"name": "Box Jump", "sets": 4, "reps": "5"}, {"name": "Single Leg Box Jump", "sets": 3, "reps": "3 each"}, {"name": "Broad Jump", "sets": 3, "reps": "5"}]}, {"name": "Nordic", "sequence": 3, "exercises": [{"name": "Nordic Curl Negative", "sets": 3, "reps": "5"}, {"name": "Nordic Curl", "sets": 2, "reps": "max"}]}]}'::jsonb,
ARRAY['calisthenics', 'advanced', 'legs', 'pistol', 'nordic'], 'calisthenics_adv_legs.md'),

('00e00001-0018-4000-8000-000000000018', 'Ring Mastery', 'Advanced ring training', 'strength', 'advanced', 50,
'{"blocks": [{"name": "Ring Basics", "sequence": 0, "exercises": [{"name": "Ring Support Hold", "sets": 3, "reps": "20 sec", "notes": "Rings turned out"}, {"name": "Ring Dip", "sets": 3, "reps": "10"}]}, {"name": "Ring Skills", "sequence": 1, "exercises": [{"name": "Ring Muscle-Up", "sets": 5, "reps": "3"}, {"name": "Ring L-Sit", "sets": 4, "reps": "10 sec"}, {"name": "Back Lever on Rings", "sets": 4, "reps": "8 sec"}]}, {"name": "Ring Strength", "sequence": 2, "exercises": [{"name": "Ring Pull-Up", "sets": 4, "reps": "8"}, {"name": "Ring Push-Up", "sets": 4, "reps": "12"}, {"name": "Ring Rollout", "sets": 3, "reps": "8"}]}, {"name": "Ring Core", "sequence": 3, "exercises": [{"name": "Ring Body Saw", "sets": 3, "reps": "10"}, {"name": "Ring Pike", "sets": 3, "reps": "8"}]}]}'::jsonb,
ARRAY['calisthenics', 'advanced', 'rings', 'gymnastics', 'full-body'], 'calisthenics_ring_mastery.md'),

('00e00001-0019-4000-8000-000000000019', 'One Arm Pull-Up Progression', 'Train towards the one arm pull-up', 'strength', 'advanced', 45,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Pull-Up", "sets": 2, "reps": "8"}, {"name": "One Arm Hang", "sets": 2, "reps": "15 sec each"}]}, {"name": "OAP Progressions", "sequence": 1, "exercises": [{"name": "Archer Pull-Up", "sets": 5, "reps": "5 each side"}, {"name": "One Arm Negative", "sets": 4, "reps": "2 each", "notes": "10+ sec lowering"}, {"name": "Pulley Assisted OAP", "sets": 3, "reps": "3 each", "notes": "Hold rope with other hand"}]}, {"name": "Unilateral Strength", "sequence": 2, "exercises": [{"name": "Weighted One Arm Row", "sets": 4, "reps": "8 each"}, {"name": "Typewriter Pull-Up", "sets": 3, "reps": "4 each"}]}, {"name": "Grip", "sequence": 3, "exercises": [{"name": "One Arm Dead Hang", "sets": 4, "reps": "max time each"}]}]}'::jsonb,
ARRAY['calisthenics', 'advanced', 'one-arm-pullup', 'skill', 'pull'], 'calisthenics_oap.md'),

-- WORKOUT ROUTINES (6)
('00e00001-0020-4000-8000-000000000020', 'Full Body Calisthenics A', 'Balanced full body routine', 'full_body', 'intermediate', 50,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "sets": 1, "reps": "30"}, {"name": "Arm Circles", "sets": 1, "reps": "10 each"}, {"name": "Bodyweight Squat", "sets": 1, "reps": "15"}]}, {"name": "Push", "sequence": 1, "exercises": [{"name": "Push-Up", "sets": 4, "reps": "12"}, {"name": "Dip", "sets": 3, "reps": "10"}, {"name": "Pike Push-Up", "sets": 3, "reps": "8"}]}, {"name": "Pull", "sequence": 2, "exercises": [{"name": "Pull-Up", "sets": 4, "reps": "8"}, {"name": "Australian Row", "sets": 3, "reps": "12"}]}, {"name": "Legs", "sequence": 3, "exercises": [{"name": "Pistol Squat", "sets": 3, "reps": "5 each", "notes": "Or progression"}, {"name": "Nordic Curl Negative", "sets": 3, "reps": "5"}]}, {"name": "Core", "sequence": 4, "exercises": [{"name": "L-Sit Hold", "sets": 3, "reps": "15 sec"}, {"name": "Ab Wheel", "sets": 3, "reps": "10"}]}]}'::jsonb,
ARRAY['calisthenics', 'intermediate', 'full-body', 'routine'], 'calisthenics_fullbody_a.md'),

('00e00001-0021-4000-8000-000000000021', 'Full Body Calisthenics B', 'Alternative full body routine', 'full_body', 'intermediate', 50,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "High Knees", "sets": 1, "reps": "30 sec"}, {"name": "Push-Up", "sets": 1, "reps": "10"}, {"name": "Squat", "sets": 1, "reps": "15"}]}, {"name": "Pull", "sequence": 1, "exercises": [{"name": "Pull-Up", "sets": 4, "reps": "8"}, {"name": "Ring Row", "sets": 3, "reps": "12"}, {"name": "Face Pull", "sets": 3, "reps": "15"}]}, {"name": "Push", "sequence": 2, "exercises": [{"name": "Ring Push-Up", "sets": 4, "reps": "10"}, {"name": "Handstand Hold", "sets": 3, "reps": "20 sec"}]}, {"name": "Legs", "sequence": 3, "exercises": [{"name": "Bulgarian Split Squat", "sets": 3, "reps": "10 each"}, {"name": "Glute Ham Raise", "sets": 3, "reps": "8"}]}, {"name": "Core", "sequence": 4, "exercises": [{"name": "Hanging Leg Raise", "sets": 3, "reps": "12"}, {"name": "Plank", "sets": 2, "reps": "45 sec"}]}]}'::jsonb,
ARRAY['calisthenics', 'intermediate', 'full-body', 'routine'], 'calisthenics_fullbody_b.md'),

('00e00001-0022-4000-8000-000000000022', 'Upper/Lower Split - Upper', 'Upper body calisthenics focus', 'upper', 'intermediate', 45,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Band Pull-Aparts", "sets": 2, "reps": "15"}, {"name": "Push-Up", "sets": 2, "reps": "10"}]}, {"name": "Vertical Push", "sequence": 1, "exercises": [{"name": "Pike Push-Up", "sets": 4, "reps": "8"}, {"name": "Handstand Hold", "sets": 3, "reps": "20 sec"}]}, {"name": "Vertical Pull", "sequence": 2, "exercises": [{"name": "Pull-Up", "sets": 4, "reps": "8"}, {"name": "Chin-Up", "sets": 3, "reps": "8"}]}, {"name": "Horizontal Push", "sequence": 3, "exercises": [{"name": "Dip", "sets": 4, "reps": "10"}, {"name": "Push-Up Variation", "sets": 3, "reps": "12"}]}, {"name": "Horizontal Pull", "sequence": 4, "exercises": [{"name": "Australian Row", "sets": 4, "reps": "10"}, {"name": "Face Pull", "sets": 3, "reps": "15"}]}]}'::jsonb,
ARRAY['calisthenics', 'intermediate', 'upper', 'split'], 'calisthenics_upper.md'),

('00e00001-0023-4000-8000-000000000023', 'Upper/Lower Split - Lower', 'Lower body and core calisthenics', 'lower', 'intermediate', 45,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "sets": 1, "reps": "30"}, {"name": "Leg Swings", "sets": 1, "reps": "10 each"}]}, {"name": "Quad Dominant", "sequence": 1, "exercises": [{"name": "Pistol Squat Progression", "sets": 4, "reps": "5 each"}, {"name": "Bulgarian Split Squat", "sets": 3, "reps": "10 each"}, {"name": "Sissy Squat", "sets": 3, "reps": "10"}]}, {"name": "Hip Dominant", "sequence": 2, "exercises": [{"name": "Single Leg RDL", "sets": 3, "reps": "10 each"}, {"name": "Nordic Curl", "sets": 3, "reps": "5"}, {"name": "Glute Bridge", "sets": 3, "reps": "15"}]}, {"name": "Core", "sequence": 3, "exercises": [{"name": "Dragon Flag Progression", "sets": 3, "reps": "5"}, {"name": "Hanging Leg Raise", "sets": 3, "reps": "10"}, {"name": "Ab Wheel", "sets": 3, "reps": "10"}]}, {"name": "Calves", "sequence": 4, "exercises": [{"name": "Single Leg Calf Raise", "sets": 3, "reps": "15 each"}]}]}'::jsonb,
ARRAY['calisthenics', 'intermediate', 'lower', 'core', 'split'], 'calisthenics_lower.md'),

('00e00001-0024-4000-8000-000000000024', 'Calisthenics HIIT', 'High intensity bodyweight circuits', 'cardio', 'intermediate', 30,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Jumping Jacks", "sets": 1, "reps": "30"}, {"name": "High Knees", "sets": 1, "reps": "20"}, {"name": "Bodyweight Squat", "sets": 1, "reps": "10"}]}, {"name": "Circuit 1 (3 rounds)", "sequence": 1, "exercises": [{"name": "Burpee", "sets": 1, "reps": "10"}, {"name": "Pull-Up", "sets": 1, "reps": "8"}, {"name": "Jump Squat", "sets": 1, "reps": "12"}, {"name": "Push-Up", "sets": 1, "reps": "15"}, {"name": "Rest", "sets": 1, "reps": "60 sec"}]}, {"name": "Circuit 2 (3 rounds)", "sequence": 2, "exercises": [{"name": "Mountain Climber", "sets": 1, "reps": "20 each"}, {"name": "Dip", "sets": 1, "reps": "10"}, {"name": "Jump Lunge", "sets": 1, "reps": "10 each"}, {"name": "Hanging Knee Raise", "sets": 1, "reps": "12"}, {"name": "Rest", "sets": 1, "reps": "60 sec"}]}]}'::jsonb,
ARRAY['calisthenics', 'intermediate', 'hiit', 'cardio', 'circuit'], 'calisthenics_hiit.md'),

('00e00001-0025-4000-8000-000000000025', 'Park Workout', 'Outdoor calisthenics at any park', 'full_body', 'intermediate', 45,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Jog", "sets": 1, "reps": "2 min"}, {"name": "Arm Circles", "sets": 1, "reps": "10 each"}, {"name": "Leg Swings", "sets": 1, "reps": "10 each"}]}, {"name": "Bar Work", "sequence": 1, "exercises": [{"name": "Pull-Up", "sets": 4, "reps": "8", "notes": "Monkey bars or pull-up bar"}, {"name": "Chin-Up", "sets": 3, "reps": "8"}, {"name": "Hanging Leg Raise", "sets": 3, "reps": "10"}]}, {"name": "Bench Work", "sequence": 2, "exercises": [{"name": "Incline Push-Up", "sets": 3, "reps": "15"}, {"name": "Decline Push-Up", "sets": 3, "reps": "12"}, {"name": "Bench Dip", "sets": 3, "reps": "12"}, {"name": "Bulgarian Split Squat", "sets": 3, "reps": "10 each"}]}, {"name": "Ground Work", "sequence": 3, "exercises": [{"name": "Pistol Squat", "sets": 3, "reps": "5 each"}, {"name": "Plank", "sets": 2, "reps": "45 sec"}, {"name": "Burpee", "sets": 2, "reps": "10"}]}, {"name": "Cool Down", "sequence": 4, "exercises": [{"name": "Stretching", "sets": 1, "reps": "5 min"}]}]}'::jsonb,
ARRAY['calisthenics', 'intermediate', 'outdoor', 'park', 'full-body'], 'calisthenics_park.md');
