-- Seed Rehab/PT workout templates (25 templates)
-- Focus: Physical therapy protocols, injury rehab, return to activity

INSERT INTO system_workout_templates (id, name, description, category, difficulty, duration_minutes, exercises, tags, source_file) VALUES

-- SHOULDER REHAB (5)
('00d00001-0001-4000-8000-000000000001', 'Rotator Cuff Rehab Phase 1', 'Early stage rotator cuff rehabilitation - pain reduction and mobility', 'mobility', 'beginner', 25,
'{"blocks": [{"name": "Pain Modulation", "sequence": 0, "exercises": [{"name": "Pendulum Swings", "sets": 3, "reps": "30 sec each direction", "notes": "Lean forward, let arm hang"}, {"name": "Passive ROM with Stick", "sets": 2, "reps": "10", "notes": "Use good arm to assist"}]}, {"name": "Isometrics", "sequence": 1, "exercises": [{"name": "Isometric External Rotation", "sets": 3, "reps": "10 sec hold", "notes": "Elbow at side, push into wall"}, {"name": "Isometric Internal Rotation", "sets": 3, "reps": "10 sec hold"}, {"name": "Isometric Abduction", "sets": 3, "reps": "10 sec hold"}]}, {"name": "Gentle Mobility", "sequence": 2, "exercises": [{"name": "Supine Flexion", "sets": 2, "reps": "10", "notes": "Assist with other arm"}]}]}'::jsonb,
ARRAY['rehab', 'shoulder', 'rotator-cuff', 'phase-1', 'isometric'], 'rehab_rotator_cuff_1.md'),

('00d00001-0002-4000-8000-000000000002', 'Rotator Cuff Rehab Phase 2', 'Intermediate rotator cuff - strength building', 'strength', 'intermediate', 30,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Pendulum Swings", "sets": 1, "reps": "1 min"}]}, {"name": "Strengthening", "sequence": 1, "exercises": [{"name": "Side-Lying External Rotation", "sets": 3, "reps": "12", "notes": "Light dumbbell or no weight"}, {"name": "Prone Y Raise", "sets": 3, "reps": "10"}, {"name": "Prone T Raise", "sets": 3, "reps": "10"}, {"name": "Prone W Raise", "sets": 3, "reps": "10"}]}, {"name": "Scapular Control", "sequence": 2, "exercises": [{"name": "Wall Slides", "sets": 3, "reps": "10"}, {"name": "Serratus Punch", "sets": 3, "reps": "12"}]}]}'::jsonb,
ARRAY['rehab', 'shoulder', 'rotator-cuff', 'phase-2', 'strengthening'], 'rehab_rotator_cuff_2.md'),

('00d00001-0003-4000-8000-000000000003', 'Rotator Cuff Rehab Phase 3', 'Advanced rotator cuff - return to function', 'strength', 'intermediate', 35,
'{"blocks": [{"name": "Dynamic Warm-Up", "sequence": 0, "exercises": [{"name": "Arm Circles", "sets": 1, "reps": "10 each way"}, {"name": "Band Pull-Aparts", "sets": 2, "reps": "15"}]}, {"name": "Strengthening", "sequence": 1, "exercises": [{"name": "External Rotation with Band", "sets": 3, "reps": "15"}, {"name": "Internal Rotation with Band", "sets": 3, "reps": "15"}, {"name": "Standing Y Raise", "sets": 3, "reps": "12"}, {"name": "Face Pull", "sets": 3, "reps": "15"}]}, {"name": "Functional", "sequence": 2, "exercises": [{"name": "Push-Up Plus", "sets": 2, "reps": "10"}, {"name": "Wall Push-Up", "sets": 2, "reps": "12"}]}]}'::jsonb,
ARRAY['rehab', 'shoulder', 'rotator-cuff', 'phase-3', 'functional'], 'rehab_rotator_cuff_3.md'),

('00d00001-0004-4000-8000-000000000004', 'Frozen Shoulder Protocol', 'Adhesive capsulitis rehabilitation', 'mobility', 'beginner', 30,
'{"blocks": [{"name": "Heat Application", "sequence": 0, "exercises": [{"name": "Moist Heat", "sets": 1, "reps": "10 min", "notes": "Before exercises"}]}, {"name": "Stretching", "sequence": 1, "exercises": [{"name": "Cross Body Stretch", "sets": 3, "reps": "30 sec hold"}, {"name": "Sleeper Stretch", "sets": 3, "reps": "30 sec hold"}, {"name": "Towel Internal Rotation", "sets": 3, "reps": "30 sec hold"}, {"name": "Corner Stretch", "sets": 3, "reps": "30 sec hold"}]}, {"name": "Mobility", "sequence": 2, "exercises": [{"name": "Finger Wall Walk", "sets": 2, "reps": "10 each direction"}, {"name": "Pendulum Swings", "sets": 2, "reps": "1 min each direction"}]}]}'::jsonb,
ARRAY['rehab', 'shoulder', 'frozen-shoulder', 'adhesive-capsulitis', 'mobility'], 'rehab_frozen_shoulder.md'),

('00d00001-0005-4000-8000-000000000005', 'Post-Surgical Shoulder', 'General post-operative shoulder protocol weeks 4-8', 'mobility', 'beginner', 25,
'{"blocks": [{"name": "Passive ROM", "sequence": 0, "exercises": [{"name": "Table Slides", "sets": 3, "reps": "15", "notes": "Slide arm on table"}, {"name": "Supine Flexion Assist", "sets": 3, "reps": "10", "notes": "Use good arm or wand"}]}, {"name": "Active Assist", "sequence": 1, "exercises": [{"name": "Pulley Flexion", "sets": 2, "reps": "15"}, {"name": "Pulley Abduction", "sets": 2, "reps": "15"}]}, {"name": "Isometrics", "sequence": 2, "exercises": [{"name": "Isometric Flexion", "sets": 3, "reps": "5 sec hold"}, {"name": "Isometric Extension", "sets": 3, "reps": "5 sec hold"}]}]}'::jsonb,
ARRAY['rehab', 'shoulder', 'post-surgical', 'gentle', 'early-phase'], 'rehab_post_surgery_shoulder.md'),

-- KNEE REHAB (5)
('00d00001-0006-4000-8000-000000000006', 'ACL Rehab Phase 1', 'ACL reconstruction early phase - weeks 1-4', 'mobility', 'beginner', 30,
'{"blocks": [{"name": "Pain/Swelling", "sequence": 0, "exercises": [{"name": "Quad Sets", "sets": 4, "reps": "10 sec hold each", "notes": "Push knee into surface"}, {"name": "Ankle Pumps", "sets": 3, "reps": "20"}]}, {"name": "ROM", "sequence": 1, "exercises": [{"name": "Heel Slides", "sets": 3, "reps": "15"}, {"name": "Prone Knee Flexion", "sets": 2, "reps": "10", "notes": "Gravity assist"}]}, {"name": "Strengthening", "sequence": 2, "exercises": [{"name": "Straight Leg Raise", "sets": 3, "reps": "10", "notes": "Lock knee first"}, {"name": "Side Lying Hip Abduction", "sets": 3, "reps": "10"}]}, {"name": "Gait", "sequence": 3, "exercises": [{"name": "Weight Shifting", "sets": 2, "reps": "10 each way", "notes": "With crutches"}]}]}'::jsonb,
ARRAY['rehab', 'knee', 'acl', 'phase-1', 'post-surgical'], 'rehab_acl_1.md'),

('00d00001-0007-4000-8000-000000000007', 'ACL Rehab Phase 2', 'ACL reconstruction intermediate - weeks 4-12', 'strength', 'intermediate', 40,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Stationary Bike", "sets": 1, "reps": "10 min", "notes": "Low resistance"}]}, {"name": "Strength", "sequence": 1, "exercises": [{"name": "Mini Squats", "sets": 3, "reps": "15", "notes": "0-60 degrees only"}, {"name": "Leg Press", "sets": 3, "reps": "12", "notes": "Limited range"}, {"name": "Step-Ups", "sets": 3, "reps": "10 each", "notes": "Low step"}, {"name": "Calf Raises", "sets": 3, "reps": "15"}]}, {"name": "Balance", "sequence": 2, "exercises": [{"name": "Single Leg Balance", "sets": 3, "reps": "30 sec"}, {"name": "Tandem Stance", "sets": 2, "reps": "30 sec"}]}]}'::jsonb,
ARRAY['rehab', 'knee', 'acl', 'phase-2', 'strengthening'], 'rehab_acl_2.md'),

('00d00001-0008-4000-8000-000000000008', 'Patellofemoral Pain Protocol', 'Exercises for anterior knee pain', 'strength', 'beginner', 30,
'{"blocks": [{"name": "VMO Activation", "sequence": 0, "exercises": [{"name": "Terminal Knee Extension", "sets": 3, "reps": "15", "notes": "Towel under knee"}, {"name": "Quad Set with Adduction", "sets": 3, "reps": "10 sec hold", "notes": "Squeeze ball between knees"}]}, {"name": "Hip Strengthening", "sequence": 1, "exercises": [{"name": "Clamshell", "sets": 3, "reps": "15 each"}, {"name": "Side-Lying Hip Abduction", "sets": 3, "reps": "15 each"}, {"name": "Bridges", "sets": 3, "reps": "12"}]}, {"name": "Stretching", "sequence": 2, "exercises": [{"name": "Quad Stretch", "sets": 2, "reps": "30 sec each"}, {"name": "IT Band Stretch", "sets": 2, "reps": "30 sec each"}]}]}'::jsonb,
ARRAY['rehab', 'knee', 'patellofemoral', 'anterior-knee-pain', 'runners-knee'], 'rehab_pfp.md'),

('00d00001-0009-4000-8000-000000000009', 'Meniscus Rehab', 'Post-meniscus surgery or conservative treatment', 'strength', 'beginner', 30,
'{"blocks": [{"name": "ROM", "sequence": 0, "exercises": [{"name": "Heel Slides", "sets": 3, "reps": "15"}, {"name": "Seated Knee Extension", "sets": 3, "reps": "12"}]}, {"name": "Strengthening", "sequence": 1, "exercises": [{"name": "Quad Sets", "sets": 3, "reps": "10 sec hold"}, {"name": "Straight Leg Raise", "sets": 3, "reps": "12"}, {"name": "Hip Abduction", "sets": 3, "reps": "12"}, {"name": "Mini Squats", "sets": 2, "reps": "10", "notes": "Pain-free range only"}]}, {"name": "Balance", "sequence": 2, "exercises": [{"name": "Weight Shifts", "sets": 2, "reps": "10 each way"}, {"name": "Single Leg Balance", "sets": 2, "reps": "20 sec"}]}]}'::jsonb,
ARRAY['rehab', 'knee', 'meniscus', 'strengthening'], 'rehab_meniscus.md'),

('00d00001-0010-4000-8000-000000000010', 'Total Knee Replacement Rehab', 'TKR rehabilitation protocol', 'strength', 'beginner', 35,
'{"blocks": [{"name": "ROM", "sequence": 0, "exercises": [{"name": "Seated Knee Extension", "sets": 3, "reps": "15", "notes": "Straighten fully"}, {"name": "Heel Slides", "sets": 3, "reps": "15"}, {"name": "Stationary Bike", "sets": 1, "reps": "10 min", "notes": "Rock back and forth initially"}]}, {"name": "Strengthening", "sequence": 1, "exercises": [{"name": "Quad Sets", "sets": 3, "reps": "10 sec hold"}, {"name": "Straight Leg Raise", "sets": 3, "reps": "10"}, {"name": "Ankle Pumps", "sets": 3, "reps": "20"}]}, {"name": "Functional", "sequence": 2, "exercises": [{"name": "Sit to Stand", "sets": 3, "reps": "10", "notes": "Use armrests"}, {"name": "Stair Practice", "sets": 2, "reps": "5 each way", "notes": "Rail support"}]}]}'::jsonb,
ARRAY['rehab', 'knee', 'tkr', 'total-knee', 'post-surgical'], 'rehab_tkr.md'),

-- BACK REHAB (5)
('00d00001-0011-4000-8000-000000000011', 'Low Back Pain Phase 1', 'Acute low back pain - pain relief and mobility', 'mobility', 'beginner', 20,
'{"blocks": [{"name": "Pain Relief", "sequence": 0, "exercises": [{"name": "Supine Knee to Chest", "sets": 3, "reps": "30 sec hold each"}, {"name": "Supine Pelvic Tilt", "sets": 3, "reps": "10"}]}, {"name": "Gentle Movement", "sequence": 1, "exercises": [{"name": "Cat-Cow", "sets": 2, "reps": "10 slow"}, {"name": "Supine Twist", "sets": 2, "reps": "30 sec each side"}, {"name": "Child Pose", "sets": 2, "reps": "30 sec"}]}, {"name": "Walking", "sequence": 2, "exercises": [{"name": "Short Walk", "sets": 1, "reps": "5-10 min", "notes": "Flat surface, comfortable pace"}]}]}'::jsonb,
ARRAY['rehab', 'back', 'low-back-pain', 'acute', 'phase-1'], 'rehab_lbp_1.md'),

('00d00001-0012-4000-8000-000000000012', 'Low Back Pain Phase 2', 'Subacute back pain - core stability', 'strength', 'beginner', 30,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Pelvic Tilts", "sets": 2, "reps": "10"}, {"name": "Cat-Cow", "sets": 2, "reps": "10"}]}, {"name": "Core Stability", "sequence": 1, "exercises": [{"name": "Dead Bug", "sets": 3, "reps": "10 each side"}, {"name": "Bird Dog", "sets": 3, "reps": "10 each side"}, {"name": "Glute Bridge", "sets": 3, "reps": "12"}, {"name": "Side Plank", "sets": 2, "reps": "15 sec each", "notes": "Modified on knees"}]}, {"name": "Hip Mobility", "sequence": 2, "exercises": [{"name": "Hip Flexor Stretch", "sets": 2, "reps": "30 sec each"}, {"name": "Piriformis Stretch", "sets": 2, "reps": "30 sec each"}]}]}'::jsonb,
ARRAY['rehab', 'back', 'low-back-pain', 'core', 'phase-2'], 'rehab_lbp_2.md'),

('00d00001-0013-4000-8000-000000000013', 'McKenzie Extension Protocol', 'Extension-based treatment for disc issues', 'mobility', 'beginner', 15,
'{"blocks": [{"name": "Prone Progression", "sequence": 0, "exercises": [{"name": "Prone Lying", "sets": 1, "reps": "2 min", "notes": "Flat on stomach"}, {"name": "Prone on Elbows", "sets": 1, "reps": "2 min", "notes": "Sphinx position"}, {"name": "Prone Press-Up", "sets": 10, "reps": "1", "notes": "Push up, hips stay down"}]}, {"name": "Standing", "sequence": 1, "exercises": [{"name": "Standing Extension", "sets": 5, "reps": "1", "notes": "Hands on low back, lean back"}]}, {"name": "Maintenance", "sequence": 2, "exercises": [{"name": "Prone Press-Up", "sets": 1, "reps": "10 reps every 2 hours", "notes": "Throughout the day"}]}]}'::jsonb,
ARRAY['rehab', 'back', 'mckenzie', 'extension', 'disc'], 'rehab_mckenzie.md'),

('00d00001-0014-4000-8000-000000000014', 'Sciatica Relief Protocol', 'Exercises for sciatic nerve pain', 'mobility', 'beginner', 25,
'{"blocks": [{"name": "Nerve Glides", "sequence": 0, "exercises": [{"name": "Sciatic Nerve Floss", "sets": 3, "reps": "10 each leg", "notes": "Seated, extend knee while looking up"}, {"name": "Slump Stretch", "sets": 2, "reps": "30 sec each"}]}, {"name": "Mobility", "sequence": 1, "exercises": [{"name": "Piriformis Stretch", "sets": 3, "reps": "30 sec each"}, {"name": "Figure Four Stretch", "sets": 3, "reps": "30 sec each"}, {"name": "Knee to Opposite Chest", "sets": 3, "reps": "30 sec each"}]}, {"name": "Core", "sequence": 2, "exercises": [{"name": "Pelvic Tilts", "sets": 2, "reps": "10"}, {"name": "Bird Dog", "sets": 2, "reps": "8 each side"}]}]}'::jsonb,
ARRAY['rehab', 'back', 'sciatica', 'nerve', 'piriformis'], 'rehab_sciatica.md'),

('00d00001-0015-4000-8000-000000000015', 'Post-Laminectomy Rehab', 'Rehabilitation after spinal decompression', 'strength', 'beginner', 30,
'{"blocks": [{"name": "Walking", "sequence": 0, "exercises": [{"name": "Flat Surface Walking", "sets": 1, "reps": "10-15 min", "notes": "Primary exercise early on"}]}, {"name": "Core Bracing", "sequence": 1, "exercises": [{"name": "Abdominal Bracing", "sets": 3, "reps": "10 sec hold"}, {"name": "Pelvic Tilts", "sets": 3, "reps": "10"}, {"name": "Glute Bridge", "sets": 3, "reps": "10"}]}, {"name": "Mobility", "sequence": 2, "exercises": [{"name": "Knee to Chest", "sets": 2, "reps": "30 sec each"}, {"name": "Hamstring Stretch", "sets": 2, "reps": "30 sec each"}]}]}'::jsonb,
ARRAY['rehab', 'back', 'laminectomy', 'post-surgical', 'spinal'], 'rehab_laminectomy.md'),

-- HIP REHAB (5)
('00d00001-0016-4000-8000-000000000016', 'Hip Impingement Protocol', 'FAI rehabilitation exercises', 'strength', 'beginner', 30,
'{"blocks": [{"name": "Hip Mobility", "sequence": 0, "exercises": [{"name": "Supine Hip Flexor Stretch", "sets": 3, "reps": "30 sec each"}, {"name": "Supine Figure Four", "sets": 3, "reps": "30 sec each"}, {"name": "90/90 Hip Stretch", "sets": 2, "reps": "30 sec each"}]}, {"name": "Strengthening", "sequence": 1, "exercises": [{"name": "Clamshell", "sets": 3, "reps": "15 each"}, {"name": "Side-Lying Hip Abduction", "sets": 3, "reps": "15 each"}, {"name": "Glute Bridge", "sets": 3, "reps": "12"}, {"name": "Fire Hydrant", "sets": 3, "reps": "10 each"}]}, {"name": "Control", "sequence": 2, "exercises": [{"name": "Single Leg Balance", "sets": 2, "reps": "30 sec each"}]}]}'::jsonb,
ARRAY['rehab', 'hip', 'impingement', 'fai', 'mobility'], 'rehab_hip_impingement.md'),

('00d00001-0017-4000-8000-000000000017', 'Total Hip Replacement Rehab', 'THR rehabilitation with precautions', 'strength', 'beginner', 30,
'{"blocks": [{"name": "Precautions Review", "sequence": 0, "exercises": [{"name": "Posterior Precautions", "sets": 1, "reps": "review", "notes": "No hip flexion >90°, no adduction past midline, no internal rotation"}]}, {"name": "Early Exercises", "sequence": 1, "exercises": [{"name": "Ankle Pumps", "sets": 3, "reps": "20"}, {"name": "Quad Sets", "sets": 3, "reps": "10 sec hold"}, {"name": "Gluteal Squeeze", "sets": 3, "reps": "10 sec hold"}, {"name": "Heel Slides", "sets": 3, "reps": "15", "notes": "Within precautions"}]}, {"name": "Standing", "sequence": 2, "exercises": [{"name": "Standing Hip Abduction", "sets": 3, "reps": "10 each", "notes": "Hold support"}, {"name": "Standing Hip Extension", "sets": 3, "reps": "10 each"}]}]}'::jsonb,
ARRAY['rehab', 'hip', 'thr', 'total-hip', 'post-surgical'], 'rehab_thr.md'),

('00d00001-0018-4000-8000-000000000018', 'IT Band Syndrome Protocol', 'Exercises for iliotibial band syndrome', 'strength', 'beginner', 30,
'{"blocks": [{"name": "Foam Rolling", "sequence": 0, "exercises": [{"name": "IT Band Foam Roll", "sets": 1, "reps": "2 min each side", "notes": "Avoid rolling directly on bone"}, {"name": "Quad Foam Roll", "sets": 1, "reps": "1 min each"}]}, {"name": "Stretching", "sequence": 1, "exercises": [{"name": "Standing IT Band Stretch", "sets": 3, "reps": "30 sec each"}, {"name": "Pigeon Pose", "sets": 2, "reps": "30 sec each"}]}, {"name": "Hip Strengthening", "sequence": 2, "exercises": [{"name": "Clamshell", "sets": 3, "reps": "15 each"}, {"name": "Side-Lying Hip Abduction", "sets": 3, "reps": "15 each"}, {"name": "Single Leg Bridge", "sets": 2, "reps": "10 each"}]}]}'::jsonb,
ARRAY['rehab', 'hip', 'it-band', 'runners', 'lateral-knee'], 'rehab_itband.md'),

('00d00001-0019-4000-8000-000000000019', 'Hip Bursitis Protocol', 'Greater trochanteric bursitis rehabilitation', 'strength', 'beginner', 25,
'{"blocks": [{"name": "Avoid Aggravators", "sequence": 0, "exercises": [{"name": "Side-Lying Precautions", "sets": 1, "reps": "review", "notes": "Pillow between knees when sleeping on side"}]}, {"name": "Gentle Stretching", "sequence": 1, "exercises": [{"name": "Standing IT Band Stretch", "sets": 2, "reps": "30 sec each", "notes": "Gentle only"}, {"name": "Piriformis Stretch", "sets": 2, "reps": "30 sec each"}]}, {"name": "Hip Strengthening", "sequence": 2, "exercises": [{"name": "Clamshell", "sets": 3, "reps": "12 each", "notes": "Pain-free only"}, {"name": "Prone Hip Extension", "sets": 3, "reps": "10 each"}, {"name": "Glute Bridge", "sets": 3, "reps": "12"}]}]}'::jsonb,
ARRAY['rehab', 'hip', 'bursitis', 'trochanteric', 'lateral-hip'], 'rehab_hip_bursitis.md'),

('00d00001-0020-4000-8000-000000000020', 'Piriformis Syndrome Protocol', 'Exercises for piriformis-related symptoms', 'mobility', 'beginner', 25,
'{"blocks": [{"name": "Stretching", "sequence": 0, "exercises": [{"name": "Supine Piriformis Stretch", "sets": 3, "reps": "30 sec each"}, {"name": "Seated Piriformis Stretch", "sets": 3, "reps": "30 sec each"}, {"name": "Pigeon Pose", "sets": 2, "reps": "30 sec each"}]}, {"name": "Nerve Glides", "sequence": 1, "exercises": [{"name": "Sciatic Nerve Floss", "sets": 2, "reps": "10 each"}]}, {"name": "Strengthening", "sequence": 2, "exercises": [{"name": "Clamshell", "sets": 3, "reps": "12 each"}, {"name": "Fire Hydrant", "sets": 3, "reps": "10 each"}, {"name": "Glute Bridge", "sets": 3, "reps": "12"}]}]}'::jsonb,
ARRAY['rehab', 'hip', 'piriformis', 'sciatica', 'glute'], 'rehab_piriformis.md'),

-- ANKLE/FOOT REHAB (3)
('00d00001-0021-4000-8000-000000000021', 'Ankle Sprain Rehab', 'Lateral ankle sprain rehabilitation', 'strength', 'beginner', 25,
'{"blocks": [{"name": "Early Phase", "sequence": 0, "exercises": [{"name": "Ankle Alphabet", "sets": 2, "reps": "A-Z"}, {"name": "Ankle Pumps", "sets": 3, "reps": "20"}, {"name": "Towel Scrunches", "sets": 3, "reps": "15"}]}, {"name": "Strengthening", "sequence": 1, "exercises": [{"name": "4-Way Ankle Resistance", "sets": 3, "reps": "15 each direction", "notes": "Band around foot"}, {"name": "Heel Raises", "sets": 3, "reps": "15"}]}, {"name": "Balance", "sequence": 2, "exercises": [{"name": "Single Leg Balance", "sets": 3, "reps": "30 sec"}, {"name": "Single Leg Balance on Pillow", "sets": 2, "reps": "20 sec"}]}]}'::jsonb,
ARRAY['rehab', 'ankle', 'sprain', 'lateral', 'balance'], 'rehab_ankle_sprain.md'),

('00d00001-0022-4000-8000-000000000022', 'Plantar Fasciitis Protocol', 'Exercises for plantar fascia pain', 'mobility', 'beginner', 20,
'{"blocks": [{"name": "Morning Routine", "sequence": 0, "exercises": [{"name": "Towel Stretch", "sets": 3, "reps": "30 sec", "notes": "Before getting out of bed"}, {"name": "Plantar Fascia Stretch", "sets": 3, "reps": "30 sec each foot"}]}, {"name": "Throughout Day", "sequence": 1, "exercises": [{"name": "Calf Stretch on Step", "sets": 3, "reps": "30 sec each"}, {"name": "Frozen Water Bottle Roll", "sets": 1, "reps": "5 min each foot", "notes": "Ice massage"}, {"name": "Towel Scrunches", "sets": 3, "reps": "15"}]}, {"name": "Strengthening", "sequence": 2, "exercises": [{"name": "Calf Raises", "sets": 3, "reps": "15"}, {"name": "Toe Yoga", "sets": 2, "reps": "10", "notes": "Lift big toe, then other toes separately"}]}]}'::jsonb,
ARRAY['rehab', 'foot', 'plantar-fasciitis', 'heel-pain', 'stretching'], 'rehab_plantar_fasciitis.md'),

('00d00001-0023-4000-8000-000000000023', 'Achilles Tendinopathy Protocol', 'Eccentric loading program for Achilles', 'strength', 'intermediate', 25,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Stationary Bike", "sets": 1, "reps": "5 min"}, {"name": "Calf Stretch", "sets": 2, "reps": "30 sec each"}]}, {"name": "Eccentric Loading", "sequence": 1, "exercises": [{"name": "Eccentric Heel Drop - Straight Knee", "sets": 3, "reps": "15 each leg", "notes": "Rise on both feet, lower on affected only"}, {"name": "Eccentric Heel Drop - Bent Knee", "sets": 3, "reps": "15 each leg", "notes": "Targets soleus"}]}, {"name": "Isometric", "sequence": 2, "exercises": [{"name": "Isometric Calf Raise Hold", "sets": 3, "reps": "45 sec", "notes": "For pain relief"}]}]}'::jsonb,
ARRAY['rehab', 'ankle', 'achilles', 'tendinopathy', 'eccentric'], 'rehab_achilles.md'),

-- GENERAL REHAB (2)
('00d00001-0024-4000-8000-000000000024', 'Return to Running Protocol', 'Progressive return to running after injury', 'cardio', 'intermediate', 40,
'{"blocks": [{"name": "Warm-Up", "sequence": 0, "exercises": [{"name": "Walking", "sets": 1, "reps": "5 min"}, {"name": "Dynamic Stretches", "sets": 1, "reps": "5 min"}]}, {"name": "Walk/Run Intervals", "sequence": 1, "exercises": [{"name": "Run/Walk Intervals", "sets": 6, "reps": "1 min run / 2 min walk", "notes": "Progress weekly by adding 30 sec run time"}]}, {"name": "Cool Down", "sequence": 2, "exercises": [{"name": "Walking", "sets": 1, "reps": "5 min"}, {"name": "Static Stretching", "sets": 1, "reps": "10 min"}]}, {"name": "Progression", "sequence": 3, "exercises": [{"name": "Week 1: 1 run/2 walk x 6", "sets": 1, "reps": "note"}, {"name": "Week 2: 2 run/2 walk x 5", "sets": 1, "reps": "note"}, {"name": "Week 3: 3 run/2 walk x 4", "sets": 1, "reps": "note"}]}]}'::jsonb,
ARRAY['rehab', 'running', 'return-to-sport', 'cardio', 'progressive'], 'rehab_return_to_running.md'),

('00d00001-0025-4000-8000-000000000025', 'Post-Injury Deconditioning', 'General reconditioning after prolonged rest', 'full_body', 'beginner', 35,
'{"blocks": [{"name": "Cardio Base", "sequence": 0, "exercises": [{"name": "Walking or Bike", "sets": 1, "reps": "10 min", "notes": "Easy pace"}]}, {"name": "Full Body Strength", "sequence": 1, "exercises": [{"name": "Wall Push-Up", "sets": 2, "reps": "10"}, {"name": "Bodyweight Squat", "sets": 2, "reps": "10", "notes": "To chair"}, {"name": "Standing Row with Band", "sets": 2, "reps": "12"}, {"name": "Glute Bridge", "sets": 2, "reps": "12"}]}, {"name": "Core", "sequence": 2, "exercises": [{"name": "Dead Bug", "sets": 2, "reps": "8 each side"}, {"name": "Bird Dog", "sets": 2, "reps": "8 each side"}]}, {"name": "Flexibility", "sequence": 3, "exercises": [{"name": "Full Body Stretch", "sets": 1, "reps": "5 min"}]}]}'::jsonb,
ARRAY['rehab', 'deconditioning', 'general', 'full-body', 'beginner'], 'rehab_deconditioning.md');
